/* ==================================================================
   VERSE CONTEXT NOTES — historical, thematic & authorial context.

   Provides one-line context notes (author, audience, occasion/theme)
   keyed by stable verseId() ids for core scripture verses.
   Rendered in resolution lines, Study Hall cards, and learning flows.
   ================================================================== */
const VERSE_NOTES = {
  "genesis-1-1~heaven-and-the-earth": "Moses to Israel in the wilderness: the absolute beginning and sovereignty of God over all creation.",
  "genesis-2-7~living-soul": "Moses recording the creation of man from the dust with the breath of life given by God.",
  "genesis-9-13~bow": "God's covenant with Noah and all creation following the flood, setting the bow in the cloud.",
  "genesis-50-20~alive": "Joseph to his brothers in Egypt, declaring God's sovereign providence over human malice.",
  "genesis-12-1~a-land-that-i": "God calling Abram out of Haran into Canaan with the promise of a great nation.",
  "genesis-15-6~for-righteousness": "Abram believing the LORD, credited to him for righteousness before circumcision.",
  "genesis-22-8~god-will-provide-himself": "Abraham answering Isaac on Mount Moriah, prophesying God providing Himself a lamb.",
  "genesis-28-15~whither-thou-goest": "The LORD assuring Jacob at Bethel that He will be with him and bring him back to the land.",
  "exodus-3-14~i-am-that-i": "God revealing His eternal self-existent name 'I AM THAT I AM' to Moses at the burning bush.",
  "exodus-14-14~hold-your-peace": "Moses to trembling Israel before the Red Sea, proclaiming God will fight for them.",
  "exodus-20-3~before-me": "The first commandment given to Israel at Mount Sinai, demanding exclusive worship of the LORD.",
  "exodus-33-14~i-will-give-thee": "The LORD assuring Moses that His presence would go with him and give Israel rest.",
  "leviticus-19-18~i-am-the-lord": "The law of holiness given to Israel, commanding love of neighbour as oneself.",
  "leviticus-17-11~atonement": "The law of atonement: the life of the flesh is in the blood given upon the altar.",
  "numbers-6-24~bless-thee-and-keep": "The Aaronic priestly blessing ordained by God to place His name upon the children of Israel.",
  "numbers-23-19~repent": "Balaam's oracle before Balak, declaring God cannot lie nor repent of His word.",
  "deuteronomy-6-5~might": "The Great Shema given by Moses to Israel before entering Canaan: wholehearted love for God.",
  "deuteronomy-31-6~fail-thee-nor-forsake": "Moses encouraging Israel before the Jordan crossing: the LORD will not fail nor forsake them.",
  "deuteronomy-29-29~all-the-words-of": "Moses distinguishing secret things belonging to God from revealed things given to Israel.",
  "joshua-1-9~dismayed": "The LORD charging Joshua to be strong and courageous taking command after Moses' death.",
  "joshua-24-15~serve-the-lord": "Joshua's farewell challenge at Shechem: 'as for me and my house, we will serve the LORD'.",
  "judges-5-31~might": "The song of Deborah and Barak celebrating the victory over Sisera and the might of God's people.",
  "judges-6-12~valour": "The Angel of the LORD greeting Gideon hiding in the winepress as a 'mighty man of valour'.",
  "ruth-1-16~thy-god-my-god": "Ruth's steadfast covenant vow of loyalty to Naomi and Naomi's God on the road to Bethlehem.",
  "1-samuel-16-7~heart": "The LORD instructing Samuel in Jesse's house: God looketh on the heart, not outward appearance.",
  "1-samuel-15-22~fat-of-rams": "Samuel rebuking king Saul: 'to obey is better than sacrifice, and to hearken than fat of rams'.",
  "2-samuel-7-12~set-up-thy-seed": "Nathan the prophet conveying the Davidic covenant of an everlasting kingdom.",
  "2-samuel-22-2~deliverer": "David's psalm of deliverance after being saved from Saul and all his enemies.",
  "1-kings-18-21~opinions": "Elijah confronting Israel on Mount Carmel: 'How long halt ye between two opinions?'",
  "1-kings-19-12~still-small-voice": "God revealing Himself to Elijah at Mount Horeb not in wind or quake, but in a still small voice.",
  "2-kings-6-16~more-than-they-that": "Elisha comforting his servant in Dothan: 'they that be with us are more than they that be with them'.",
  "1-chronicles-16-34~endureth-for-ever": "David delivering a psalm of thanksgiving to Asaph upon bringing the ark to Jerusalem.",
  "2-chronicles-7-14~heal-their-land": "The LORD's covenant promise to Solomon for healing the land upon humble prayer and repentance.",
  "ezra-7-10~statutes-and-judgments": "Ezra preparing his heart to seek the law of the LORD, do it, and teach statutes in Israel.",
  "nehemiah-8-10~joy-of-the-lord": "Nehemiah and Ezra encouraging the weeping people: 'the joy of the LORD is your strength'.",
  "esther-4-14~such-a-time-as": "Mordecai challenging queen Esther: 'who knoweth whether thou art come to the kingdom for such a time as this?'",
  "job-19-25~latter-day": "Job's triumphant confession in agony: 'I know that my redeemer liveth, and shall stand at the latter day'.",
  "job-23-10~i-shall-come-forth": "Job trusting God's testing: 'when he hath tried me, I shall come forth as gold'.",
  "job-38-4~i-laid-the-foundations": "The LORD answering Job out of the whirlwind: 'Where wast thou when I laid the foundations of the earth?'",
  "psalm-1-1~seat-of-the-scornful": "David describing the blessed man who delights in the law of the LORD rather than wicked counsel.",
  "psalm-19-1~handywork": "David celebrating general revelation: 'The heavens declare the glory of God; and the firmament sheweth his handywork'.",
  "psalm-23-1~not-want": "David resting in the LORD as his faithful Shepherd providing in green pastures and the valley of shadow.",
  "psalm-27-1~strength": "David declaring the LORD his light and salvation, dispelling all fear in time of trouble.",
  "psalm-34-8~taste-and-see": "David praising God after feigning madness before Abimelech: 'O taste and see that the LORD is good'.",
  "psalm-37-4~desires-of-thine-heart": "David counseling trust: 'Delight thyself also in the LORD; and he shall give thee the desires of thine heart'.",
  "psalm-46-1~help": "The sons of Korah singing of God as refuge, strength, and a very present help in trouble.",
  "psalm-46-10~i-will-be-exalted": "God commanding the nations: 'Be still, and know that I am God: I will be exalted in the earth'.",
  "psalm-51-10~right-spirit": "David's penitential prayer after his sin with Bathsheba: 'Create in me a clean heart, O God'.",
  "psalm-90-12~wisdom": "Moses praying: 'So teach us to number our days, that we may apply our hearts unto wisdom'.",
  "psalm-91-1~abide": "The psalm of refuge: dwelling in the secret place of the most High under the shadow of the Almighty.",
  "psalm-103-1~bless-his-holy-name": "David commanding his soul to bless the LORD and forget not all His benefits.",
  "psalm-118-24~rejoice-and-be-glad": "The festive psalm of praise: 'This is the day which the LORD hath made; we will rejoice and be glad in it'.",
  "psalm-119-105~light": "The psalmist praising the Word: 'Thy word is a lamp unto my feet, and a light unto my path'.",
  "psalm-121-1~help": "The Song of Degrees: lifting eyes unto the hills, knowing help cometh from the LORD.",
  "psalm-139-14~marvellous": "David praising God's omniscient workmanship: 'I am fearfully and wonderfully made'.",
  "proverbs-3-5~thine-own-understanding": "Solomon instructing his son: 'Trust in the LORD with all thine heart; and lean not unto thine own understanding'.",
  "proverbs-4-23~issues-of-life": "Solomon's counsel on vigilance: 'Keep thy heart with all diligence; for out of it are the issues of life'.",
  "proverbs-9-10~the-knowledge-of-the": "The foundational wisdom principle: 'The fear of the LORD is the beginning of wisdom'.",
  "proverbs-18-10~safe": "Solomon on divine security: 'The name of the LORD is a strong tower: the righteous runneth into it, and is safe'.",
  "proverbs-27-17~countenance": "Solomon on fellowship: 'Iron sharpeneth iron; so a man sharpeneth the countenance of his friend'.",
  "ecclesiastes-3-1~purpose": "Solomon observing divine timing: 'To every thing there is a season, and a time to every purpose'.",
  "ecclesiastes-12-13~whole-duty-of-man": "The conclusion of the whole matter: 'Fear God, and keep his commandments: for this is the whole duty of man'.",
  "isaiah-6-8~here-am-i-send": "Isaiah responding to the Lord's call in the temple vision: 'Here am I; send me'.",
  "isaiah-7-14~call-his-name-immanuel": "Isaiah giving king Ahaz the sign of the virgin birth of Immanuel.",
  "isaiah-9-6~prince-of-peace": "Isaiah foretelling the birth of the Prince of Peace who shall reign upon David's throne.",
  "isaiah-26-3~stayed": "Isaiah praising God: 'Thou wilt keep him in perfect peace, whose mind is stayed on thee'.",
  "isaiah-40-31~eagles": "Isaiah encouraging exiles: 'they that wait upon the LORD shall renew their strength; they shall mount up with wings'.",
  "isaiah-53-5~bruised": "Isaiah describing the Suffering Servant: 'He was wounded for our transgressions, he was bruised for our iniquities'.",
  "isaiah-55-6~call-ye-upon-him": "Isaiah extending the gospel invitation: 'Seek ye the LORD while he may be found, call ye upon him while he is near'.",
  "jeremiah-29-11~expected-end": "Jeremiah's letter to exiles in Babylon: 'I know the thoughts that I think toward you, saith the LORD, thoughts of peace'.",
  "jeremiah-33-3~mighty-things": "The LORD in the court of the prison: 'Call unto me, and I will answer thee, and shew thee great and mighty things'.",
  "lamentations-3-22~compassions": "Jeremiah amidst Jerusalem's ruins: 'It is of the LORD's mercies that we are not consumed, because his compassions fail not'.",
  "ezekiel-36-26~stony-heart": "The LORD promising the new covenant: a new heart and a new spirit, replacing the stony heart.",
  "daniel-12-3~firmament": "The angel revealing the end times: they that turn many to righteousness shall shine as the stars forever.",
  "micah-6-8~humbly": "Micah summarizing God's requirement: 'to do justly, and to love mercy, and to walk humbly with thy God'.",
  "habakkuk-2-4~faith": "The prophet's foundational principle quoted throughout the epistles: 'the just shall live by his faith'.",
  "zechariah-4-6~lord-of-hosts": "The word of the LORD unto Zerubbabel: 'Not by might, nor by power, but by my spirit, saith the LORD of hosts'.",
  "malachi-3-10~windows-of-heaven": "The LORD challenging Israel to bring all tithes into the storehouse and prove His open windows of heaven.",
  "matthew-5-3~theirs-is-the-kingdom": "Jesus opening the Sermon on the Mount with the Beatitudes: 'Blessed are the poor in spirit'.",
  "matthew-6-33~added": "Jesus teaching against anxiety: 'Seek ye first the kingdom of God, and his righteousness'.",
  "matthew-11-28~rest": "Jesus extending the great invitation: 'Come unto me, all ye that labour and are heavy laden, and I will give you rest'.",
  "matthew-28-19~teach-all-nations": "The Great Commission: 'Go ye therefore, and teach all nations, baptizing them in the name of the Father, and of the Son, and of the Holy Ghost'.",
  "mark-8-36~lose-his-own-soul": "Jesus warning His disciples: 'For what shall it profit a man, if he shall gain the whole world, and lose his own soul?'",
  "mark-10-45~a-ransom-for-many": "Jesus defining His mission: 'For even the Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many'.",
  "luke-1-37~impossible": "Gabriel assuring Mary at the Annunciation: 'For with God nothing shall be impossible'.",
  "luke-2-14~good-will-toward-men": "The heavenly host praising God at Bethlehem: 'Glory to God in the highest, and on earth peace, good will toward men'.",
  "luke-19-10~that-which-was-lost": "Jesus in Zacchaeus' house: 'For the Son of man is come to seek and to save that which was lost'.",
  "john-1-1~was-god": "John opening the Gospel: 'In the beginning was the Word, and the Word was with God, and the Word was God'.",
  "john-1-14~full-of-grace-and": "The incarnation of the Son of God: 'And the Word was made flesh, and dwelt among us'.",
  "john-3-16~everlasting-life": "Jesus to Nicodemus: 'For God so loved the world, that he gave his only begotten Son'.",
  "john-10-10~more-abundantly": "Jesus contrasting the thief: 'I am come that they might have life, and that they might have it more abundantly'.",
  "john-11-25~yet-shall-he-live": "Jesus comforting Martha at Lazarus' tomb: 'I am the resurrection, and the life'.",
  "john-14-6~but-by-me": "Jesus answering Thomas: 'I am the way, the truth, and the life: no man cometh unto the Father, but by me'.",
  "john-15-5~nothing": "Jesus teaching the Vine and branches: 'without me ye can do nothing'.",
  "acts-1-8~witnesses-unto-me": "The risen Jesus commissioning the apostles: 'ye shall receive power, after that the Holy Ghost is come upon you'.",
  "acts-4-12~must-be-saved": "Peter declaring to the Sanhedrin: 'Neither is there salvation in any other: for there is none other name under heaven given among men'.",
  "acts-16-31~believe-on-the-lord": "Paul and Silas answering the Philippian jailer: 'Believe on the Lord Jesus Christ, and thou shalt be saved'.",
  "romans-1-16~also-to-the-greek": "Paul declaring his confidence: 'For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation'.",
  "romans-3-23~glory": "Paul establishing universal need: 'For all have sinned, and come short of the glory of God'.",
  "romans-5-8~for-us": "Paul demonstrating divine love: 'God commendeth his love toward us, in that, while we were yet sinners, Christ died for us'.",
  "romans-6-23~eternal-life": "Paul contrasting sin and grace: 'For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord'.",
  "romans-8-28~purpose": "Paul assuring believers: 'all things work together for good to them that love God, to them who are the called according to his purpose'.",
  "romans-10-9~saved": "Paul explaining the word of faith: confessing the Lord Jesus and believing in the heart that God raised Him.",
  "romans-12-1~your-reasonable-service": "Paul urging consecration: presenting bodies a living sacrifice, holy, acceptable unto God.",
  "romans-12-2~renewing": "Paul on renewal: 'be not conformed to this world: but be ye transformed by the renewing of your mind'.",
  "1-corinthians-10-13~way-to-escape": "Paul assuring the church: God is faithful and will not suffer you to be tempted above that ye are able.",
  "1-corinthians-13-13~the-greatest-of-these": "Paul concluding the love chapter: 'now abideth faith, hope, charity, these three; but the greatest of these is charity'.",
  "1-corinthians-15-55~victory": "Paul celebrating victory over death: 'O death, where is thy sting? O grave, where is thy victory?'",
  "2-corinthians-5-17~creature": "Paul on the new creation: 'if any man be in Christ, he is a new creature: old things are passed away'.",
  "2-corinthians-12-9~weakness": "The Lord to Paul concerning his thorn: 'My grace is sufficient for thee: for my strength is made perfect in weakness'.",
  "galatians-2-20~liveth": "Paul's testimony of union with Christ: 'I am crucified with Christ: nevertheless I live; yet not I, but Christ liveth in me'.",
  "galatians-5-22~longsuffering": "Paul listing the fruit of the Spirit: love, joy, peace, longsuffering, gentleness, goodness, faith.",
  "ephesians-2-8~gift": "Paul explaining salvation by grace through faith, not of works lest any man should boast.",
  "ephesians-4-32~as-god-for-christ": "Paul urging kindness: 'be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you'.",
  "ephesians-6-11~wiles-of-the-devil": "Paul on spiritual warfare: 'Put on the whole armour of God, that ye may be able to stand against the wiles of the devil'.",
  "philippians-1-6~the-day-of-jesus": "Paul expressing confidence: He which hath begun a good work in you will perform it until the day of Jesus Christ.",
  "philippians-4-6~requests-be-made-known": "Paul counseling peace: 'Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your requests be made known'.",
  "philippians-4-13~strengtheneth": "Paul declaring strength: 'I can do all things through Christ which strengtheneth me'.",
  "colossians-3-23~heartily": "Paul setting heavenly perspective: 'Set your affection on things above, not on things on the earth'.",
  "2-timothy-1-7~sound-mind": "Paul encouraging young Timothy: 'God hath not given us the spirit of fear; but of power, and of love, and of a sound mind'.",
  "2-timothy-3-16~inspiration-of-god": "Paul confirming biblical authority: 'All scripture is given by inspiration of God, and is profitable for doctrine'.",
  "hebrews-4-12~twoedged-sword": "The author describing scripture: 'the word of God is quick, and powerful, and sharper than any twoedged sword'.",
  "hebrews-11-1~evidence": "The definition of faith: 'the substance of things hoped for, the evidence of things not seen'.",
  "hebrews-12-1~beset": "The author exhorting believers: laying aside every weight and running with patience the race set before us.",
  "hebrews-12-2~the-author-and-finisher": "The author focusing our gaze: 'Looking unto Jesus the author and finisher of our faith'.",
  "james-1-22~deceiving": "James warning against deception: 'be ye doers of the word, and not hearers only'.",
  "1-peter-5-7~careth": "Peter counseling the scattered saints: 'Casting all your care upon him; for he careth for you'.",
  "1-john-1-9~unrighteousness": "John assuring forgiveness: 'If we confess our sins, he is faithful and just to forgive us our sins'.",
  "1-john-4-19~because-he-first-loved": "John explaining love's origin: 'We love him, because he first loved us'.",
  "revelation-3-20~sup": "Jesus to the church in Laodicea: 'Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in'.",
  "revelation-21-4~former-things": "The glorious promise of the New Jerusalem: God shall wipe away all tears from their eyes; and there shall be no more death."
};

if (typeof module !== "undefined" && module.exports){
  module.exports = { VERSE_NOTES };
}
