const BOOKS_ORDER = ["Genesis","Exodus","Leviticus","Numbers","Deuteronomy","Joshua","Judges","Ruth","1 Samuel","2 Samuel","1 Kings","2 Kings","1 Chronicles","2 Chronicles","Ezra","Nehemiah","Esther","Job","Psalms","Proverbs","Ecclesiastes","Song of Solomon","Isaiah","Jeremiah","Lamentations","Ezekiel","Daniel","Hosea","Joel","Amos","Obadiah","Jonah","Micah","Nahum","Habakkuk","Zephaniah","Haggai","Zechariah","Malachi","Matthew","Mark","Luke","John","Acts","Romans","1 Corinthians","2 Corinthians","Galatians","Ephesians","Philippians","Colossians","1 Thessalonians","2 Thessalonians","1 Timothy","2 Timothy","Titus","Philemon","Hebrews","James","1 Peter","2 Peter","1 John","2 John","3 John","Jude","Revelation"];

const VERSES = [
/* ---------- LAW ---------- */
{b:"Genesis",r:"Genesis 1:1",t:1,p:"In the beginning God created the",a:"heaven and the earth",s:".",d:["heavens and the earth","earth and the heaven","heavens and earth"]},
{b:"Genesis",r:"Genesis 2:7",t:3,p:"And the LORD God formed man of the dust of the ground, and breathed into his nostrils the breath of life; and man became a",a:"living soul",s:".",d:["living being","living spirit","soul that liveth"]},
{b:"Genesis",r:"Genesis 9:13",t:4,p:"I do set my",a:"bow",s:"in the cloud, and it shall be for a token of a covenant between me and the earth.",d:["rainbow","sign","arch"]},
{b:"Genesis",r:"Genesis 50:20",t:4,p:"But as for you, ye thought evil against me; but God meant it unto good, to bring to pass, as it is this day, to save much people",a:"alive",s:".",d:["from death","from famine","therefrom"]},
{b:"Exodus",r:"Exodus 14:14",t:2,p:"The LORD shall fight for you, and ye shall",a:"hold your peace",s:".",d:["keep silent","be still","hold your tongue"]},
{b:"Exodus",r:"Exodus 20:3",t:1,p:"Thou shalt have no other gods",a:"before me",s:".",d:["besides me","but me","before mine eyes"]},
{b:"Exodus",r:"Exodus 3:14",t:3,p:"And God said unto Moses,",a:"I AM THAT I AM",s:": and he said, Thus shalt thou say unto the children of Israel, I AM hath sent me unto you.",d:["I AM WHO I AM","I AM WHAT I AM","I AM HE THAT IS"]},
{b:"Leviticus",r:"Leviticus 19:18",t:4,p:"but thou shalt love thy neighbour as thyself:",a:"I am the LORD",s:".",d:["I am the LORD thy God","saith the LORD","I am the LORD your God"]},
{b:"Leviticus",r:"Leviticus 17:11",t:5,p:"For the life of the flesh is in the blood: and I have given it to you upon the altar to make an",a:"atonement",s:"for your souls.",d:["offering","expiation","intercession"]},
{b:"Numbers",r:"Numbers 6:24",t:3,p:"The LORD",a:"bless thee, and keep thee",s:":",d:["keep thee, and bless thee","bless and preserve thee","bless thee, and hold thee"]},
{b:"Numbers",r:"Numbers 23:19",t:4,p:"God is not a man, that he should lie; neither the son of man, that he should",a:"repent",s:": hath he said, and shall he not do it?",d:["relent","change","turn"]},
{b:"Deuteronomy",r:"Deuteronomy 6:5",t:2,p:"And thou shalt love the LORD thy God with all thine heart, and with all thy soul, and with all thy",a:"might",s:".",d:["strength","mind","power"]},
{b:"Deuteronomy",r:"Deuteronomy 31:6",t:3,p:"for the LORD thy God, he it is that doth go with thee; he will not",a:"fail thee, nor forsake thee",s:".",d:["forsake thee, nor fail thee","leave thee, nor forsake thee","fail thee, nor leave thee"]},

/* ---------- HISTORY ---------- */
{b:"Joshua",r:"Joshua 1:9",t:1,p:"Be strong and of a good courage; be not afraid, neither be thou",a:"dismayed",s:": for the LORD thy God is with thee whithersoever thou goest.",d:["discouraged","confounded","troubled"]},
{b:"Joshua",r:"Joshua 24:15",t:2,p:"choose you this day whom ye will serve … but as for me and my house, we will",a:"serve the LORD",s:".",d:["follow the LORD","worship the LORD","serve the Lord GOD"]},
{b:"Judges",r:"Judges 6:12",t:4,p:"And the angel of the LORD appeared unto him, and said unto him, The LORD is with thee, thou mighty man of",a:"valour",s:".",d:["war","courage","might"]},
{b:"Judges",r:"Judges 5:31",t:5,p:"but let them that love him be as the sun when he goeth forth in his",a:"might",s:".",d:["strength","glory","splendour"]},
{b:"Ruth",r:"Ruth 1:16",t:3,p:"Whither thou goest, I will go; and where thou lodgest, I will lodge: thy people shall be my people, and",a:"thy God my God",s:":",d:["thy God shall be my God","my God thy God","thy LORD my LORD"]},
{b:"1 Samuel",r:"1 Samuel 16:7",t:3,p:"for man looketh on the outward appearance, but the LORD looketh on the",a:"heart",s:".",d:["inward man","soul","spirit"]},
{b:"1 Samuel",r:"1 Samuel 15:22",t:4,p:"Behold, to obey is better than sacrifice, and to hearken than the",a:"fat of rams",s:".",d:["blood of rams","fat of lambs","fat of bullocks"]},
{b:"2 Samuel",r:"2 Samuel 22:2",t:4,p:"The LORD is my rock, and my fortress, and my",a:"deliverer",s:";",d:["redeemer","salvation","shield"]},
{b:"1 Kings",r:"1 Kings 18:21",t:4,p:"How long halt ye between two",a:"opinions",s:"? if the LORD be God, follow him: but if Baal, then follow him.",d:["masters","ways","altars"]},
{b:"1 Kings",r:"1 Kings 19:12",t:3,p:"and after the earthquake a fire; but the LORD was not in the fire: and after the fire a",a:"still small voice",s:".",d:["small still voice","soft low voice","still quiet voice"]},
{b:"2 Kings",r:"2 Kings 6:16",t:4,p:"Fear not: for they that be with us are",a:"more than they that be with them",s:".",d:["greater than they that be with them","more than those against us","mightier than they that be with them"]},
{b:"1 Chronicles",r:"1 Chronicles 16:34",t:3,p:"O give thanks unto the LORD; for he is good; for his mercy",a:"endureth for ever",s:".",d:["lasteth for ever","abideth for ever","faileth never"]},
{b:"1 Chronicles",r:"1 Chronicles 4:10",t:5,p:"And Jabez called on the God of Israel, saying, Oh that thou wouldest bless me indeed, and enlarge my",a:"coast",s:",",d:["border","territory","inheritance"]},
{b:"2 Chronicles",r:"2 Chronicles 7:14",t:2,p:"then will I hear from heaven, and will forgive their sin, and will",a:"heal their land",s:".",d:["restore their land","heal their nation","bless their land"]},
{b:"2 Chronicles",r:"2 Chronicles 16:9",t:5,p:"For the eyes of the LORD run to and fro throughout the whole earth, to shew himself strong in the behalf of them whose heart is",a:"perfect",s:"toward him.",d:["upright","whole","steadfast"]},
{b:"Ezra",r:"Ezra 7:10",t:5,p:"For Ezra had prepared his heart to seek the law of the LORD, and to do it, and to teach in Israel",a:"statutes and judgments",s:".",d:["judgments and statutes","his statutes and laws","statutes and ordinances"]},
{b:"Nehemiah",r:"Nehemiah 8:10",t:2,p:"neither be ye sorry; for the",a:"joy of the LORD",s:"is your strength.",d:["strength of the LORD","peace of the LORD","joy of our God"]},
{b:"Nehemiah",r:"Nehemiah 6:3",t:5,p:"I am doing a",a:"great work",s:", so that I cannot come down:",d:["mighty work","good work","great labour"]},
{b:"Esther",r:"Esther 4:14",t:3,p:"and who knoweth whether thou art come to the kingdom for",a:"such a time as this?",s:"",d:["such a time as now?","a time such as this?","this very hour?"]},
{b:"Esther",r:"Esther 4:16",t:4,p:"and so will I go in unto the king, which is not according to the law: and if I perish,",a:"I perish",s:".",d:["then I perish","so I perish","I shall perish"]},

/* ---------- WISDOM ---------- */
{b:"Job",r:"Job 1:21",t:3,p:"the LORD gave, and the LORD hath taken away; blessed be the",a:"name of the LORD",s:".",d:["LORD","name of our God","name of the Lord GOD"]},
{b:"Job",r:"Job 19:25",t:3,p:"For I know that my redeemer liveth, and that he shall stand at the",a:"latter day",s:"upon the earth:",d:["last day","latter days","day of judgment"]},
{b:"Job",r:"Job 13:15",t:5,p:"Though he slay me, yet will I",a:"trust",s:"in him:",d:["hope","believe","abide"]},
{b:"Psalms",r:"Psalm 23:1",t:1,p:"The LORD is my shepherd; I shall",a:"not want",s:".",d:["not fear","lack nothing","want for nothing"]},
{b:"Psalms",r:"Psalm 46:1",t:1,p:"God is our refuge and strength, a very present",a:"help",s:"in trouble.",d:["helper","refuge","deliverance"]},
{b:"Psalms",r:"Psalm 119:105",t:1,p:"Thy word is a lamp unto my feet, and a",a:"light",s:"unto my path.",d:["lamp","guide","beacon"]},
{b:"Psalms",r:"Psalm 27:1",t:2,p:"The LORD is my light and my salvation; whom shall I fear? the LORD is the",a:"strength",s:"of my life; of whom shall I be afraid?",d:["stronghold","fortress","defence"]},
{b:"Psalms",r:"Psalm 51:10",t:2,p:"Create in me a clean heart, O God; and renew a",a:"right spirit",s:"within me.",d:["steadfast spirit","righteous spirit","new spirit"]},
{b:"Psalms",r:"Psalm 37:4",t:2,p:"Delight thyself also in the LORD; and he shall give thee the",a:"desires of thine heart",s:".",d:["desires of thy heart","longings of thine heart","wishes of thine heart"]},
{b:"Psalms",r:"Psalm 118:24",t:2,p:"This is the day which the LORD hath made; we will",a:"rejoice and be glad in it",s:".",d:["be glad and rejoice in it","rejoice and be joyful in it","rejoice and be glad therein"]},
{b:"Psalms",r:"Psalm 121:1",t:2,p:"I will lift up mine eyes unto the hills, from whence cometh my",a:"help",s:".",d:["strength","hope","salvation"]},
{b:"Psalms",r:"Psalm 1:1",t:2,p:"Blessed is the man that walketh not in the counsel of the ungodly, nor standeth in the way of sinners, nor sitteth in the",a:"seat of the scornful",s:".",d:["seat of scoffers","seat of the mockers","place of the scornful"]},
{b:"Psalms",r:"Psalm 34:8",t:3,p:"O",a:"taste and see",s:"that the LORD is good: blessed is the man that trusteth in him.",d:["see and taste","taste and know","come and see"]},
{b:"Psalms",r:"Psalm 19:1",t:3,p:"The heavens declare the glory of God; and the firmament sheweth his",a:"handywork",s:".",d:["glory","majesty","wondrous works"]},
{b:"Psalms",r:"Psalm 139:14",t:3,p:"I will praise thee; for I am fearfully and wonderfully made:",a:"marvellous",s:"are thy works; and that my soul knoweth right well.",d:["wonderful","glorious","excellent"]},
{b:"Psalms",r:"Psalm 91:1",t:3,p:"He that dwelleth in the secret place of the most High shall",a:"abide",s:"under the shadow of the Almighty.",d:["rest","dwell","remain"]},
{b:"Psalms",r:"Psalm 147:3",t:3,p:"He healeth the broken in heart, and",a:"bindeth up their wounds",s:".",d:["bindeth up their sorrows","healeth their wounds","bindeth their wounds"]},
{b:"Psalms",r:"Psalm 56:3",t:3,p:"What time I am afraid, I will",a:"trust in thee",s:".",d:["put my trust in thee","hope in thee","call upon thee"]},
{b:"Psalms",r:"Psalm 100:4",t:3,p:"Enter into his gates with thanksgiving, and into his",a:"courts with praise",s:":",d:["courts with singing","gates with praise","courts with thanksgiving"]},
{b:"Psalms",r:"Psalm 30:5",t:4,p:"weeping may endure for a night, but",a:"joy",s:"cometh in the morning.",d:["gladness","rejoicing","singing"]},
{b:"Psalms",r:"Psalm 42:1",t:4,p:"As the hart panteth after the water brooks, so panteth my soul after thee,",a:"O God",s:".",d:["O LORD","O God my strength","O Lord GOD"]},
{b:"Psalms",r:"Psalm 90:12",t:4,p:"So teach us to number our days, that we may apply our hearts unto",a:"wisdom",s:".",d:["understanding","thy statutes","knowledge"]},
{b:"Psalms",r:"Psalm 133:1",t:4,p:"Behold, how good and how pleasant it is for brethren to dwell together in",a:"unity",s:"!",d:["peace","harmony","one accord"]},
{b:"Psalms",r:"Psalm 22:1",t:5,p:"My God, my God, why hast thou forsaken me? why art thou so far from helping me, and from the words of my",a:"roaring",s:"?",d:["groaning","crying","distress"]},
{b:"Psalms",r:"Psalm 84:10",t:5,p:"I had rather be a",a:"doorkeeper",s:"in the house of my God, than to dwell in the tents of wickedness.",d:["servant","gatekeeper","porter"]},
{b:"Proverbs",r:"Proverbs 3:5",t:1,p:"Trust in the LORD with all thine heart; and lean not unto",a:"thine own understanding",s:".",d:["thine own wisdom","thy own understanding","thine own devices"]},
{b:"Proverbs",r:"Proverbs 18:10",t:2,p:"The name of the LORD is a strong tower: the righteous runneth into it, and is",a:"safe",s:".",d:["saved","secure","delivered"]},
{b:"Proverbs",r:"Proverbs 22:6",t:2,p:"Train up a child in the way he should go: and when he is old, he will not",a:"depart from it",s:".",d:["turn from it","depart therefrom","stray from it"]},
{b:"Proverbs",r:"Proverbs 15:1",t:3,p:"A soft answer turneth away wrath: but grievous words",a:"stir up anger",s:".",d:["stir up wrath","kindle anger","provoke anger"]},
{b:"Proverbs",r:"Proverbs 27:17",t:3,p:"Iron sharpeneth iron; so a man sharpeneth the",a:"countenance",s:"of his friend.",d:["character","spirit","face"]},
{b:"Proverbs",r:"Proverbs 4:23",t:4,p:"Keep thy heart with all diligence; for out of it are the",a:"issues of life",s:".",d:["springs of life","wellsprings of life","ways of life"]},
{b:"Proverbs",r:"Proverbs 16:3",t:4,p:"Commit thy works unto the LORD, and thy",a:"thoughts",s:"shall be established.",d:["plans","ways","purposes"]},
{b:"Ecclesiastes",r:"Ecclesiastes 3:1",t:2,p:"To every thing there is a season, and a time to every",a:"purpose",s:"under the heaven.",d:["matter","work","thing"]},
{b:"Ecclesiastes",r:"Ecclesiastes 12:13",t:4,p:"Fear God, and keep his commandments: for this is the",a:"whole duty of man",s:".",d:["duty of all men","whole of man","chief duty of man"]},
{b:"Song of Solomon",r:"Song of Solomon 2:1",t:4,p:"I am the rose of Sharon, and the",a:"lily of the valleys",s:".",d:["lily of the valley","lilies of the valley","rose of the valleys"]},
{b:"Song of Solomon",r:"Song of Solomon 8:7",t:5,p:"Many waters cannot quench love, neither can the",a:"floods drown it",s:":",d:["rivers drown it","waters drown it","floods quench it"]},

/* ---------- MAJOR PROPHETS ---------- */
{b:"Isaiah",r:"Isaiah 40:31",t:1,p:"But they that wait upon the LORD shall renew their strength; they shall mount up with wings as",a:"eagles",s:".",d:["angels","doves","the eagle"]},
{b:"Isaiah",r:"Isaiah 41:10",t:2,p:"I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my",a:"righteousness",s:".",d:["power","strength","holiness"]},
{b:"Isaiah",r:"Isaiah 53:5",t:2,p:"But he was wounded for our transgressions, he was",a:"bruised",s:"for our iniquities.",d:["crushed","broken","smitten"]},
{b:"Isaiah",r:"Isaiah 9:6",t:3,p:"and his name shall be called Wonderful, Counsellor, The mighty God, The everlasting Father, The",a:"Prince of Peace",s:".",d:["Prince of Life","King of Peace","Prince of Glory"]},
{b:"Isaiah",r:"Isaiah 1:18",t:3,p:"though your sins be as scarlet, they shall be as white as",a:"snow",s:"; though they be red like crimson, they shall be as wool.",d:["wool","light","the morning"]},
{b:"Isaiah",r:"Isaiah 55:8",t:3,p:"For my thoughts are not your thoughts, neither are your ways my ways,",a:"saith the LORD",s:".",d:["saith the Lord GOD","saith the LORD of hosts","declareth the LORD"]},
{b:"Isaiah",r:"Isaiah 43:2",t:3,p:"When thou passest through the waters, I will be with thee; and through the rivers, they shall not",a:"overflow thee",s:":",d:["overwhelm thee","sweep over thee","cover thee"]},
{b:"Isaiah",r:"Isaiah 26:3",t:4,p:"Thou wilt keep him in perfect peace, whose mind is",a:"stayed",s:"on thee: because he trusteth in thee.",d:["fixed","set","established"]},
{b:"Isaiah",r:"Isaiah 6:8",t:4,p:"Also I heard the voice of the Lord, saying, Whom shall I send, and who will go for us? Then said I,",a:"Here am I; send me.",s:"",d:["Here I am; send me.","Behold me; send me.","Here am I, Lord; send me."]},
{b:"Jeremiah",r:"Jeremiah 29:11",t:2,p:"For I know the thoughts that I think toward you, saith the LORD, thoughts of peace, and not of evil, to give you an",a:"expected end",s:".",d:["hope and a future","end and a hope","appointed end"]},
{b:"Jeremiah",r:"Jeremiah 17:9",t:3,p:"The heart is deceitful above all things, and desperately",a:"wicked",s:": who can know it?",d:["sick","corrupt","evil"]},
{b:"Jeremiah",r:"Jeremiah 33:3",t:3,p:"Call unto me, and I will answer thee, and shew thee great and",a:"mighty things",s:", which thou knowest not.",d:["marvellous things","hidden things","wondrous things"]},
{b:"Lamentations",r:"Lamentations 3:22",t:3,p:"It is of the LORD's mercies that we are not consumed, because his",a:"compassions",s:"fail not.",d:["mercies","lovingkindnesses","tender mercies"]},
{b:"Lamentations",r:"Lamentations 3:23",t:3,p:"They are new every morning: great is thy",a:"faithfulness",s:".",d:["mercy","compassion","goodness"]},
{b:"Ezekiel",r:"Ezekiel 36:26",t:3,p:"A new heart also will I give you, and a new spirit will I put within you: and I will take away the",a:"stony heart",s:"out of your flesh.",d:["heart of stone","hardened heart","heart of flesh"]},
{b:"Ezekiel",r:"Ezekiel 37:4",t:5,p:"Prophesy upon these bones, and say unto them, O ye",a:"dry bones",s:", hear the word of the LORD.",d:["dead bones","bones","withered bones"]},
{b:"Daniel",r:"Daniel 3:18",t:3,p:"But if not, be it known unto thee, O king, that we will not serve thy gods, nor worship the",a:"golden image",s:"which thou hast set up.",d:["image of gold","graven image","molten image"]},
{b:"Daniel",r:"Daniel 12:3",t:5,p:"And they that be wise shall shine as the brightness of the",a:"firmament",s:"; and they that turn many to righteousness as the stars for ever and ever.",d:["heavens","sky","sun"]},

/* ---------- MINOR PROPHETS ---------- */
{b:"Hosea",r:"Hosea 4:6",t:3,p:"My people are destroyed for lack of",a:"knowledge",s:".",d:["wisdom","understanding","faith"]},
{b:"Hosea",r:"Hosea 6:6",t:5,p:"For I desired mercy, and not sacrifice; and the knowledge of God more than",a:"burnt offerings",s:".",d:["offerings","sacrifices","whole burnt offerings"]},
{b:"Joel",r:"Joel 2:28",t:3,p:"I will pour out my spirit upon all flesh; and your sons and your daughters shall",a:"prophesy",s:".",d:["see visions","dream dreams","declare my name"]},
{b:"Joel",r:"Joel 3:14",t:5,p:"Multitudes, multitudes in the valley of",a:"decision",s:": for the day of the LORD is near in the valley of decision.",d:["judgment","the shadow","Jehoshaphat"]},
{b:"Amos",r:"Amos 3:3",t:3,p:"Can two walk together,",a:"except they be agreed?",s:"",d:["unless they be agreed?","except they agree?","save they be agreed?"]},
{b:"Amos",r:"Amos 5:24",t:4,p:"But let judgment run down as waters, and righteousness as a",a:"mighty stream",s:".",d:["ever-flowing stream","mighty river","rushing stream"]},
{b:"Obadiah",r:"Obadiah 1:15",t:4,p:"as thou hast done, it shall be done unto thee: thy reward shall return upon",a:"thine own head",s:".",d:["thine own hand","thy own head","thine head"]},
{b:"Obadiah",r:"Obadiah 1:3",t:5,p:"The",a:"pride of thine heart",s:"hath deceived thee, thou that dwellest in the clefts of the rock",d:["pride of thy heart","pride of thine eyes","boast of thine heart"]},
{b:"Jonah",r:"Jonah 2:9",t:3,p:"But I will sacrifice unto thee with the voice of",a:"thanksgiving",s:"; I will pay that that I have vowed.",d:["praise","rejoicing","singing"]},
{b:"Jonah",r:"Jonah 1:17",t:4,p:"Now the LORD had prepared a",a:"great fish",s:"to swallow up Jonah.",d:["whale","great whale","huge fish"]},
{b:"Micah",r:"Micah 6:8",t:2,p:"and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk",a:"humbly",s:"with thy God?",d:["uprightly","meekly","faithfully"]},
{b:"Micah",r:"Micah 5:2",t:4,p:"But thou, Bethlehem Ephratah, though thou be little among the",a:"thousands of Judah",s:", yet out of thee shall he come forth unto me that is to be ruler in Israel",d:["clans of Judah","cities of Judah","tribes of Judah"]},
{b:"Nahum",r:"Nahum 1:7",t:3,p:"The LORD is good, a",a:"strong hold",s:"in the day of trouble; and he knoweth them that trust in him.",d:["strong tower","refuge","fortress"]},
{b:"Nahum",r:"Nahum 1:3",t:5,p:"The LORD is slow to anger, and great in power, and will not at all",a:"acquit the wicked",s:":",d:["clear the guilty","spare the wicked","acquit the guilty"]},
{b:"Habakkuk",r:"Habakkuk 2:4",t:3,p:"Behold, his soul which is lifted up is not upright in him: but the just shall live by his",a:"faith",s:".",d:["faithfulness","righteousness","trust"]},
{b:"Habakkuk",r:"Habakkuk 3:19",t:5,p:"The LORD God is my strength, and he will make my feet like",a:"hinds' feet",s:", and he will make me to walk upon mine high places.",d:["harts' feet","the feet of deer","the feet of hinds"]},
{b:"Zephaniah",r:"Zephaniah 3:17",t:3,p:"he will rest in his love, he will joy over thee with",a:"singing",s:".",d:["gladness","rejoicing","shouting"]},
{b:"Haggai",r:"Haggai 2:9",t:4,p:"The glory of this",a:"latter",s:"house shall be greater than of the former, saith the LORD of hosts.",d:["latter day","last","second"]},
{b:"Haggai",r:"Haggai 1:6",t:5,p:"Ye have sown much, and bring in",a:"little",s:"; ye eat, but ye have not enough",d:["nothing","a little","scarcely"]},
{b:"Zechariah",r:"Zechariah 4:6",t:3,p:"Not by might, nor by power, but by my spirit, saith the",a:"LORD of hosts",s:".",d:["LORD God","LORD of heaven","God of hosts"]},
{b:"Zechariah",r:"Zechariah 9:9",t:5,p:"behold, thy King cometh unto thee: he is just, and having salvation; lowly, and riding upon an",a:"ass",s:", and upon a colt the foal of an ass.",d:["colt","ass's colt","young ass"]},
{b:"Malachi",r:"Malachi 3:10",t:3,p:"prove me now herewith, saith the LORD of hosts, if I will not open you the",a:"windows of heaven",s:", and pour you out a blessing.",d:["gates of heaven","floodgates of heaven","doors of heaven"]},
{b:"Malachi",r:"Malachi 4:2",t:4,p:"But unto you that fear my name shall the Sun of righteousness arise with",a:"healing in his wings",s:";",d:["healing in his rays","health in his wings","healing in his hands"]},

/* ---------- GOSPELS & ACTS ---------- */
{b:"Matthew",r:"Matthew 6:33",t:1,p:"But seek ye first the kingdom of God, and his righteousness; and all these things shall be",a:"added",s:"unto you.",d:["given","granted","supplied"]},
{b:"Matthew",r:"Matthew 11:28",t:1,p:"Come unto me, all ye that labour and are heavy laden, and I will give you",a:"rest",s:".",d:["peace","comfort","life"]},
{b:"Matthew",r:"Matthew 5:14",t:1,p:"Ye are the light of the world. A city that is set on an hill",a:"cannot be hid",s:".",d:["cannot be hidden","shall not be hid","can never be hid"]},
{b:"Matthew",r:"Matthew 7:7",t:2,p:"Ask, and it shall be given you; seek, and ye shall find; knock, and it shall be",a:"opened unto you",s:":",d:["shewed unto you","added unto you","opened before you"]},
{b:"Matthew",r:"Matthew 5:16",t:2,p:"Let your light so shine before men, that they may see your good works, and",a:"glorify your Father which is in heaven",s:".",d:["glorify your Father in heaven","praise your Father which is in heaven","glorify our Father which is in heaven"]},
{b:"Matthew",r:"Matthew 28:19",t:2,p:"Go ye therefore, and",a:"teach all nations",s:", baptizing them in the name of the Father, and of the Son, and of the Holy Ghost:",d:["make disciples of all nations","preach to all nations","teach all the nations"]},
{b:"Matthew",r:"Matthew 5:6",t:3,p:"Blessed are they which do hunger and thirst after righteousness: for they shall be",a:"filled",s:".",d:["satisfied","fed","made full"]},
{b:"Matthew",r:"Matthew 16:26",t:4,p:"For what is a man profited, if he shall gain the whole world, and lose his own soul? or what shall a man give in",a:"exchange",s:"for his soul?",d:["ransom","return","payment"]},
{b:"Mark",r:"Mark 16:15",t:2,p:"Go ye into all the world, and preach the gospel to",a:"every creature",s:".",d:["all creation","every nation","all creatures"]},
{b:"Mark",r:"Mark 10:27",t:3,p:"With men it is impossible, but not with God: for with God",a:"all things are possible",s:".",d:["nothing is impossible","all is possible","all things shall be possible"]},
{b:"Mark",r:"Mark 11:24",t:4,p:"What things soever ye desire, when ye pray, believe that ye",a:"receive them",s:", and ye shall have them.",d:["have received them","shall receive them","will receive them"]},
{b:"Luke",r:"Luke 1:37",t:3,p:"For with God nothing shall be",a:"impossible",s:".",d:["withheld","too hard","denied"]},
{b:"Luke",r:"Luke 6:31",t:3,p:"And as ye would that men should do to you, do ye also to them",a:"likewise",s:".",d:["in like manner","the same","even so"]},
{b:"Luke",r:"Luke 19:10",t:3,p:"For the Son of man is come to seek and to save",a:"that which was lost",s:".",d:["those who were lost","the lost","them that were lost"]},
{b:"John",r:"John 3:16",t:1,p:"For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have",a:"everlasting life",s:".",d:["eternal life","life eternal","immortal life"]},
{b:"John",r:"John 14:6",t:1,p:"Jesus saith unto him, I am the way, the truth, and the life: no man cometh unto the Father,",a:"but by me",s:".",d:["but through me","except by me","save by me"]},
/* qaOk: "was with God" is lifted from the verse on purpose — the distinction
   between "was with God" and "was God" is the whole weight of John 1:1. */
{b:"John",r:"John 1:1",t:1,p:"In the beginning was the Word, and the Word was with God, and the Word",a:"was God",s:".",d:["was a God","is God","was with God"],qaOk:["recycled"]},
{b:"John",r:"John 8:32",t:2,p:"And ye shall know the truth, and the truth shall",a:"make you free",s:".",d:["set you free","free you","make you whole"]},
{b:"John",r:"John 15:5",t:3,p:"I am the vine, ye are the branches … for without me ye can do",a:"nothing",s:".",d:["no thing","not any thing","nought"]},
{b:"John",r:"John 10:10",t:3,p:"I am come that they might have life, and that they might have it",a:"more abundantly",s:".",d:["abundantly","in abundance","more fully"]},
{b:"John",r:"John 11:35",t:5,p:"Jesus",a:"wept",s:".",d:["groaned","mourned","sighed"]},
{b:"Acts",r:"Acts 1:8",t:3,p:"But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be",a:"witnesses unto me",s:"both in Jerusalem, and in all Judaea, and in Samaria, and unto the uttermost part of the earth.",d:["my witnesses","witnesses for me","witnesses of me"]},
{b:"Acts",r:"Acts 4:12",t:4,p:"Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we",a:"must be saved",s:".",d:["may be saved","shall be saved","can be saved"]},
{b:"Acts",r:"Acts 17:28",t:4,p:"For in him we live, and move, and have our",a:"being",s:".",d:["existence","life","dwelling"]},

/* ---------- EPISTLES ---------- */
{b:"Romans",r:"Romans 3:23",t:1,p:"For all have sinned, and come short of the",a:"glory",s:"of God.",d:["righteousness","holiness","grace"]},
{b:"Romans",r:"Romans 6:23",t:1,p:"For the wages of sin is death; but the gift of God is",a:"eternal life",s:"through Jesus Christ our Lord.",d:["everlasting life","life eternal","life everlasting"]},
{b:"Romans",r:"Romans 8:28",t:1,p:"And we know that all things work together for good to them that love God, to them who are the called according to his",a:"purpose",s:".",d:["will","counsel","good pleasure"]},
{b:"Romans",r:"Romans 12:2",t:2,p:"And be not conformed to this world: but be ye transformed by the",a:"renewing",s:"of your mind.",d:["renewal","washing","transforming"]},
{b:"Romans",r:"Romans 10:9",t:2,p:"That if thou shalt confess with thy mouth the Lord Jesus, and shalt believe in thine heart that God hath raised him from the dead, thou shalt be",a:"saved",s:".",d:["justified","redeemed","made whole"]},
{b:"Romans",r:"Romans 10:17",t:3,p:"So then faith cometh by hearing, and hearing by the",a:"word of God",s:".",d:["word of Christ","hearing of God","preaching of God"]},
{b:"Romans",r:"Romans 5:8",t:3,p:"But God commendeth his love toward us, in that, while we were yet sinners, Christ died",a:"for us",s:".",d:["in our stead","on our behalf","for our sins"]},
{b:"Romans",r:"Romans 8:39",t:5,p:"shall be able to separate us from the love of God, which is in",a:"Christ Jesus our Lord",s:".",d:["Jesus Christ our Lord","Christ Jesus our Saviour","our Lord Christ Jesus"]},
{b:"1 Corinthians",r:"1 Corinthians 13:4",t:2,p:"Charity suffereth long, and is kind; charity envieth not; charity vaunteth not itself, is not",a:"puffed up",s:",",d:["lifted up","proud","boastful"]},
{b:"1 Corinthians",r:"1 Corinthians 10:13",t:4,p:"but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a",a:"way to escape",s:",",d:["way of escape","means of escape","door of escape"]},
{b:"1 Corinthians",r:"1 Corinthians 13:12",t:4,p:"For now we see through a glass,",a:"darkly",s:"; but then face to face.",d:["dimly","as in a riddle","obscurely"]},
{b:"1 Corinthians",r:"1 Corinthians 15:55",t:5,p:"O death, where is thy sting? O grave, where is thy",a:"victory",s:"?",d:["triumph","power","dominion"]},
{b:"2 Corinthians",r:"2 Corinthians 5:17",t:2,p:"Therefore if any man be in Christ, he is a new",a:"creature",s:": old things are passed away.",d:["creation","man","spirit"]},
{b:"2 Corinthians",r:"2 Corinthians 5:7",t:3,p:"For we walk by faith, not by",a:"sight",s:".",d:["seeing","what we see","the eye"]},
{b:"2 Corinthians",r:"2 Corinthians 12:9",t:5,p:"And he said unto me, My grace is sufficient for thee: for my strength is made perfect in",a:"weakness",s:".",d:["thy weakness","infirmity","frailty"]},
{b:"Galatians",r:"Galatians 5:22",t:2,p:"But the fruit of the Spirit is love, joy, peace,",a:"longsuffering",s:", gentleness, goodness, faith,",d:["patience","forbearance","kindness"]},
{b:"Galatians",r:"Galatians 6:9",t:3,p:"And let us not be weary in well doing: for in due season we shall reap, if we",a:"faint not",s:".",d:["give not up","lose not heart","grow not weary"]},
{b:"Galatians",r:"Galatians 2:20",t:4,p:"I am crucified with Christ: nevertheless I live; yet not I, but Christ",a:"liveth",s:"in me.",d:["dwelleth","abideth","reigneth"]},
{b:"Ephesians",r:"Ephesians 2:8",t:2,p:"For by grace are ye saved through faith; and that not of yourselves: it is the",a:"gift",s:"of God.",d:["work","calling","mercy"]},
{b:"Ephesians",r:"Ephesians 6:11",t:3,p:"Put on the whole armour of God, that ye may be able to stand against the",a:"wiles of the devil",s:".",d:["works of the devil","schemes of the devil","snares of the devil"]},
{b:"Ephesians",r:"Ephesians 6:12",t:4,p:"For we wrestle not against flesh and blood, but against principalities, against powers, against the rulers of the",a:"darkness",s:"of this world.",d:["dark places","present darkness","night"]},
{b:"Philippians",r:"Philippians 4:13",t:1,p:"I can do all things through Christ which",a:"strengtheneth",s:"me.",d:["comforteth","upholdeth","quickeneth"]},
{b:"Philippians",r:"Philippians 4:6",t:2,p:"Be careful for nothing; but in every thing by prayer and supplication with thanksgiving let your",a:"requests be made known unto God",s:".",d:["petitions be made known unto God","requests be known unto God","requests be made unto God"]},
{b:"Philippians",r:"Philippians 2:10",t:4,p:"That at the name of Jesus every knee should bow, of things in heaven, and things in earth, and things",a:"under the earth",s:";",d:["beneath the earth","under the world","in the grave"]},
{b:"Colossians",r:"Colossians 3:23",t:4,p:"And whatsoever ye do, do it",a:"heartily",s:", as to the Lord, and not unto men;",d:["with all your heart","willingly","gladly"]},
{b:"Colossians",r:"Colossians 1:17",t:4,p:"And he is before all things, and by him all things",a:"consist",s:".",d:["hold together","subsist","are sustained"]},
{b:"1 Thessalonians",r:"1 Thessalonians 5:17",t:2,p:"Rejoice evermore. Pray",a:"without ceasing",s:".",d:["continually","always","without end"]},
{b:"1 Thessalonians",r:"1 Thessalonians 5:18",t:3,p:"In every thing give thanks: for this is the",a:"will of God in Christ Jesus",s:"concerning you.",d:["will of God in Jesus Christ","purpose of God in Christ Jesus","good will of God in Christ Jesus"]},
{b:"2 Thessalonians",r:"2 Thessalonians 3:3",t:4,p:"But the Lord is faithful, who shall",a:"stablish you",s:", and keep you from evil.",d:["establish you","strengthen you","uphold you"]},
{b:"2 Thessalonians",r:"2 Thessalonians 3:13",t:5,p:"But ye, brethren, be not weary in",a:"well doing",s:".",d:["doing good","good works","doing well"]},
{b:"1 Timothy",r:"1 Timothy 6:10",t:2,p:"For the love of money is the",a:"root of all evil",s:":",d:["root of all kinds of evil","source of all evil","root of every evil"]},
{b:"1 Timothy",r:"1 Timothy 4:12",t:4,p:"Let no man despise thy youth; but be thou an example of the believers, in word, in",a:"conversation",s:", in charity, in spirit, in faith, in purity.",d:["conduct","behaviour","manner of life"]},
{b:"2 Timothy",r:"2 Timothy 1:7",t:1,p:"For God hath not given us the spirit of fear; but of power, and of love, and of a",a:"sound mind",s:".",d:["sober mind","steadfast mind","sound heart"]},
{b:"2 Timothy",r:"2 Timothy 3:16",t:2,p:"All scripture is given by",a:"inspiration of God",s:", and is profitable for doctrine, for reproof, for correction, for instruction in righteousness:",d:["the inspiration of God","breath of God","revelation of God"]},
{b:"2 Timothy",r:"2 Timothy 2:15",t:3,p:"Study to shew thyself approved unto God, a workman that needeth not to be ashamed,",a:"rightly dividing",s:"the word of truth.",d:["rightly handling","truly dividing","rightly discerning"]},
{b:"Titus",r:"Titus 3:5",t:4,p:"but according to his mercy he saved us, by the washing of",a:"regeneration",s:", and renewing of the Holy Ghost;",d:["rebirth","the new birth","water"]},
{b:"Titus",r:"Titus 2:11",t:5,p:"For the grace of God that bringeth salvation hath",a:"appeared to all men",s:",",d:["appeared to all nations","been made known to all men","shined upon all men"]},
{b:"Philemon",r:"Philemon 1:6",t:4,p:"That the communication of thy faith may become effectual by the acknowledging of every good thing which is in you in",a:"Christ Jesus",s:".",d:["Jesus Christ","Christ our Lord","the Lord Jesus"]},
{b:"Hebrews",r:"Hebrews 11:1",t:1,p:"Now faith is the substance of things hoped for, the",a:"evidence",s:"of things not seen.",d:["assurance","witness","conviction"]},
{b:"Hebrews",r:"Hebrews 13:8",t:2,p:"Jesus Christ the same yesterday, and to day, and",a:"for ever",s:".",d:["for evermore","unto the ages","world without end"]},
{b:"Hebrews",r:"Hebrews 4:12",t:3,p:"For the word of God is quick, and powerful, and sharper than any",a:"twoedged sword",s:",",d:["sword of the Spirit","sharpened sword","sword that is whet"]},
{b:"Hebrews",r:"Hebrews 12:1",t:4,p:"let us lay aside every weight, and the sin which doth so easily",a:"beset",s:"us.",d:["ensnare","entangle","encompass"]},
{b:"James",r:"James 4:7",t:2,p:"Submit yourselves therefore to God. Resist the devil, and he will",a:"flee from you",s:".",d:["fly from you","depart from you","flee before you"]},
{b:"James",r:"James 1:22",t:3,p:"But be ye doers of the word, and not hearers only,",a:"deceiving",s:"your own selves.",d:["beguiling","deluding","betraying"]},
{b:"James",r:"James 1:17",t:4,p:"Every good gift and every perfect gift is from above, and cometh down from the Father of lights, with whom is no",a:"variableness",s:", neither shadow of turning.",d:["variation","changing","wavering"]},
{b:"1 Peter",r:"1 Peter 5:7",t:2,p:"Casting all your care upon him; for he",a:"careth",s:"for you.",d:["cares","provideth","watcheth"]},
{b:"1 Peter",r:"1 Peter 2:9",t:3,p:"But ye are a chosen generation, a royal priesthood, an holy nation, a",a:"peculiar people",s:";",d:["people for his possession","special people","purchased people"]},
{b:"2 Peter",r:"2 Peter 3:9",t:4,p:"but is longsuffering to us-ward, not willing that any should perish, but that all should come to",a:"repentance",s:".",d:["salvation","the truth","knowledge"]},
{b:"2 Peter",r:"2 Peter 1:21",t:5,p:"For the prophecy came not in old time by the will of man: but holy men of God spake as they were",a:"moved by the Holy Ghost",s:".",d:["led by the Holy Ghost","carried by the Holy Ghost","moved of the Holy Spirit"]},
{b:"1 John",r:"1 John 1:9",t:1,p:"If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all",a:"unrighteousness",s:".",d:["iniquity","wickedness","unrighteous deeds"]},
{b:"1 John",r:"1 John 4:8",t:2,p:"He that loveth not knoweth not God; for",a:"God is love",s:".",d:["God is charity","love is of God","God is loving"]},
{b:"1 John",r:"1 John 4:4",t:3,p:"greater is he that is in you, than he that is in",a:"the world",s:".",d:["this world","the earth","you"]},
{b:"2 John",r:"2 John 1:6",t:4,p:"And this is love, that we walk after his",a:"commandments",s:".",d:["commands","statutes","precepts"]},
{b:"3 John",r:"3 John 1:2",t:4,p:"Beloved, I wish above all things that thou mayest prosper and be in health, even as thy soul",a:"prospereth",s:".",d:["liveth","increaseth","flourisheth"]},
{b:"3 John",r:"3 John 1:4",t:5,p:"I have no greater joy than to hear that my children",a:"walk in truth",s:".",d:["walk in the truth","abide in truth","live in truth"]},
{b:"Jude",r:"Jude 1:24",t:4,p:"Now unto him that is able to keep you from falling, and to present you",a:"faultless",s:"before the presence of his glory with exceeding joy,",d:["blameless","spotless","without blemish"]},
{b:"Jude",r:"Jude 1:3",t:5,p:"ye should earnestly contend for the faith which was once",a:"delivered unto the saints",s:".",d:["delivered unto the church","given unto the saints","entrusted unto the saints"]},
{b:"Revelation",r:"Revelation 3:20",t:2,p:"Behold, I stand at the door, and knock: if any man hear my voice, and open the door, I will come in to him, and will",a:"sup",s:"with him, and he with me.",d:["dine","eat","abide"]},
{b:"Revelation",r:"Revelation 21:4",t:3,p:"neither shall there be any more pain: for the",a:"former things",s:"are passed away.",d:["first things","old things","things of old"]},
{b:"Revelation",r:"Revelation 1:8",t:4,p:"I am Alpha and Omega, the beginning and the ending, saith the Lord, which is, and which was, and which is to come, the",a:"Almighty",s:".",d:["Most High","Lord God","King of kings"]},
{b:"Revelation",r:"Revelation 12:11",t:4,p:"And they overcame him by the blood of the Lamb, and by the word of their",a:"testimony",s:";",d:["witness","confession","testimonies"]},
{b:"Revelation",r:"Revelation 22:13",t:5,p:"I am Alpha and Omega, the beginning and the end, the",a:"first and the last",s:".",d:["last and the first","Almighty","alpha and the omega"]}
];

