/* ==================================================================
   VERSES — ASCENT. Hand-authored climb that raises the ceiling.

   Kept separate from verses-extra.js (regenerated) and verses-more.js
   (first hand pack). Same three rules: no single-word blanks, distractors
   wrong about Scripture, no reference the bank already uses.
   King James throughout, public domain.
   ================================================================== */

var VERSES_ASCENT = [

/* ---------------------------- LAW ---------------------------- */
{b:"Genesis",r:"Genesis 1:3",t:1,p:"And God said, Let there be light: and",a:"there was light",s:".",d:["the darkness fled","the day was made","the heavens opened"]},
{b:"Genesis",r:"Genesis 1:26",t:2,p:"And God said, Let us make man",a:"in our image, after our likeness",s:": and let them have dominion over the fish of the sea.",d:["after our glory and honour","in the likeness of angels","as living souls of the earth"]},
{b:"Genesis",r:"Genesis 2:18",t:2,p:"And the LORD God said, It is not good that the man should be alone; I will make him",a:"an help meet for him",s:".",d:["a companion of his house","a wife after his kind","a friend to walk with him"]},
{b:"Genesis",r:"Genesis 3:19",t:3,p:"In the sweat of thy face shalt thou eat bread, till thou return unto the ground; for out of it wast thou taken: for dust thou art, and",a:"unto dust shalt thou return",s:".",d:["to the earth shalt thou go","into the grave shalt thou fall","unto ashes shalt thou turn"]},
{b:"Genesis",r:"Genesis 9:16",t:3,p:"And the bow shall be in the cloud; and I will look upon it, that I may remember",a:"the everlasting covenant between God",s:" and every living creature of all flesh that is upon the earth.",d:["the token I set in the cloud","the oath I sware unto Noah","the promise I made with the earth"]},
{b:"Genesis",r:"Genesis 12:2",t:2,p:"And I will make of thee a great nation, and I will bless thee, and make thy name great; and",a:"thou shalt be a blessing",s:".",d:["the nations shall serve thee","thy seed shall fill the land","thou shalt inherit the earth"]},
{b:"Genesis",r:"Genesis 12:3",t:3,p:"And I will bless them that bless thee, and curse him that curseth thee: and in thee shall",a:"all families of the earth be blessed",s:".",d:["the seed of Abraham be saved","the nations of the earth be judged","the kings of the earth be established"]},
{b:"Genesis",r:"Genesis 18:14",t:3,p:"Is any thing too hard for the LORD? At the time appointed I will return unto thee, according to the time of life, and",a:"Sarah shall have a son",s:".",d:["Isaac shall be born","the child shall be given","thy wife shall conceive"]},
{b:"Genesis",r:"Genesis 32:28",t:4,p:"And he said, Thy name shall be called no more Jacob, but Israel: for as a prince hast thou power with God and with men, and",a:"hast prevailed",s:".",d:["hast been delivered","hast obtained mercy","hast found favour"]},
{b:"Genesis",r:"Genesis 45:8",t:4,p:"So now it was not you that sent me hither, but God: and he hath made me a father to Pharaoh, and lord of all his house, and",a:"a ruler throughout all the land of Egypt",s:".",d:["a prince over all the land of Goshen","a steward of all Pharaoh's house","a judge throughout all the earth"]},

{b:"Exodus",r:"Exodus 15:26",t:3,p:"If thou wilt diligently hearken to the voice of the LORD thy God, and wilt do that which is right in his sight, and wilt give ear to his commandments, and keep all his statutes, I will put none of these diseases upon thee, which I have brought upon the Egyptians: for",a:"I am the LORD that healeth thee",s:".",d:["I am the LORD that keepeth thee","I am the God that spareth thee","I am the LORD thy physician"]},
{b:"Exodus",r:"Exodus 20:8",t:2,p:"Remember the sabbath day,",a:"to keep it holy",s:".",d:["to rest therein","to honour the LORD","to sanctify the week"]},
{b:"Exodus",r:"Exodus 20:12",t:2,p:"Honour thy father and thy mother: that",a:"thy days may be long",s:" in the land which the LORD thy God giveth thee.",d:["thou mayest live in peace","thy house may be blessed","thou mayest inherit the land"]},
{b:"Exodus",r:"Exodus 33:18",t:4,p:"And he said, I beseech thee,",a:"shew me thy glory",s:".",d:["shew me thy face","let me see thy way","reveal thy holy name"]},

{b:"Leviticus",r:"Leviticus 20:7",t:4,p:"Sanctify yourselves therefore, and",a:"be ye holy",s:": for I am the LORD your God.",d:["walk ye uprightly","keep yourselves clean","be ye separate"]},
{b:"Leviticus",r:"Leviticus 20:26",t:4,p:"And ye shall be holy unto me: for I the LORD am holy, and have severed you from other people, that ye should be",a:"a people unto me",s:".",d:["a nation among the heathen","a kingdom of priests only","a remnant in the land"]},

{b:"Numbers",r:"Numbers 6:25",t:3,p:"The LORD make his face shine upon thee, and",a:"be gracious unto thee",s:":",d:["give thee his peace","lift up his countenance","keep thee from evil"]},
{b:"Numbers",r:"Numbers 11:23",t:4,p:"And the LORD said unto Moses, Is the LORD'S hand waxed short? thou shalt see now whether",a:"my word shall come to pass unto thee",s:" or not.",d:["my promise shall fail thee","this thing shall be done","the flesh shall be given"]},
{b:"Numbers",r:"Numbers 14:21",t:5,p:"But as truly as I live, all the earth shall be filled with",a:"the glory of the LORD",s:".",d:["the fear of my name","the praise of Israel","the knowledge of my law"]},

{b:"Deuteronomy",r:"Deuteronomy 4:29",t:3,p:"But if from thence thou shalt seek the LORD thy God, thou shalt find him, if thou seek him",a:"with all thy heart",s:" and with all thy soul.",d:["with a perfect way","in the days of thy trouble","while he may be found"]},
{b:"Deuteronomy",r:"Deuteronomy 7:9",t:3,p:"Know therefore that the LORD thy God, he is God, the faithful God, which keepeth covenant and mercy with them that love him and keep his commandments",a:"to a thousand generations",s:".",d:["unto the children's children","for ever and ever","through all thy days"]},
{b:"Deuteronomy",r:"Deuteronomy 29:29",t:4,p:"The secret things belong unto the LORD our God: but those things which are revealed belong unto us and to our children for ever, that we may do",a:"all the words of this law",s:".",d:["the mind of the LORD","the statutes only","the whole counsel of men"]},
{b:"Deuteronomy",r:"Deuteronomy 30:14",t:4,p:"But the word is very nigh unto thee,",a:"in thy mouth, and in thy heart",s:", that thou mayest do it.",d:["in the book, and in the ark","upon the tables of stone","in the ears of the people"]},
{b:"Deuteronomy",r:"Deuteronomy 31:8",t:2,p:"And the LORD, he it is that doth go before thee; he will be with thee, he will not fail thee, neither forsake thee:",a:"fear not, neither be dismayed",s:".",d:["stand still, and see","be strong in thy heart","go forth without fear"]},

/* ---------------------------- HISTORY ---------------------------- */
{b:"Joshua",r:"Joshua 24:14",t:3,p:"Now therefore fear the LORD, and serve him in sincerity and in truth: and",a:"put away the gods which your fathers served",s:" on the other side of the flood, and in Egypt.",d:["break down the altars of Baal","forget the gods of the land","leave the idols of Canaan"]},
{b:"Judges",r:"Judges 6:24",t:4,p:"Then Gideon built an altar there unto the LORD, and called it Jehovahshalom:",a:"unto this day it is yet",s:" in Ophrah of the Abiezrites.",d:["unto this hour it standeth","unto this hour it remaineth","unto this generation it abides"]},
{b:"1 Samuel",r:"1 Samuel 1:27",t:4,p:"For this child I prayed; and the LORD hath given me my petition",a:"which I asked of him",s:".",d:["according to my vow","as he promised Hannah","out of his abundant mercy"]},
{b:"1 Samuel",r:"1 Samuel 12:23",t:4,p:"Moreover as for me, God forbid that I should sin against the LORD",a:"in ceasing to pray for you",s:": but I will teach you the good and the right way.",d:["in refusing to judge you","in turning from your cry","in forgetting the anointed"]},
{b:"2 Samuel",r:"2 Samuel 22:33",t:4,p:"God is my strength and power: and",a:"he maketh my way perfect",s:".",d:["he teacheth my hands to war","he setteth me on high places","he girdeth me with might"]},
{b:"1 Kings",r:"1 Kings 8:56",t:4,p:"Blessed be the LORD, that hath given rest unto his people Israel, according to all that he promised: there hath not failed",a:"one word of all his good promise",s:", which he promised by the hand of Moses his servant.",d:["one oath of all his good statutes","one thing of all his commandments","one jot of all his judgments"]},
{b:"1 Kings",r:"1 Kings 19:11",t:4,p:"And he said, Go forth, and stand upon the mount before the LORD. And, behold, the LORD passed by, and",a:"a great and strong wind rent the mountains",s:", and brake in pieces the rocks before the LORD; but the LORD was not in the wind.",d:["a fire fell from heaven","an earthquake shook the cave","a still small voice went forth"]},
{b:"2 Kings",r:"2 Kings 20:6",t:4,p:"And I will add unto thy days fifteen years; and I will deliver thee and this city out of the hand of the king of Assyria; and",a:"I will defend this city",s:" for mine own sake, and for my servant David's sake.",d:["I will spare this house","I will keep this remnant","I will save this people"]},
{b:"1 Chronicles",r:"1 Chronicles 16:25",t:3,p:"For great is the LORD, and greatly to be praised: he also is",a:"to be feared above all gods",s:".",d:["to be served by all nations","to be named above every name","to be sought in every place"]},
{b:"2 Chronicles",r:"2 Chronicles 20:12",t:4,p:"O our God, wilt thou not judge them? for we have no might against this great company that cometh against us; neither know we what to do: but",a:"our eyes are upon thee",s:".",d:["our hands are upon the sword","our hearts are upon Zion","our hope is upon Egypt"]},
{b:"Ezra",r:"Ezra 3:13",t:4,p:"So that the people could not discern the noise of the shout of joy from the noise of the weeping of the people: for the people shouted with a loud shout, and",a:"the noise was heard afar off",s:".",d:["the sound was heard in Judah","the cry was heard in Babylon","the song was heard in Zion"]},
{b:"Nehemiah",r:"Nehemiah 1:5",t:4,p:"And said, I beseech thee, O LORD God of heaven, the great and terrible God, that keepeth covenant and mercy for them that love him and",a:"observe his commandments",s:":",d:["walk in his statutes","fear his holy name","seek his face always"]},
{b:"Esther",r:"Esther 5:2",t:4,p:"And it was so, when the king saw Esther the queen standing in the court, that she obtained favour in his sight: and the king held out to Esther",a:"the golden sceptre that was in his hand",s:". So Esther drew near, and touched the top of the sceptre.",d:["the royal ring that was upon his hand","the silver cup that was by his throne","the purple robe that was on his shoulders"]},

/* ---------------------------- WISDOM ---------------------------- */
{b:"Job",r:"Job 1:8",t:4,p:"And the LORD said unto Satan, Hast thou considered my servant Job, that there is none like him in the earth, a perfect and an upright man,",a:"one that feareth God, and escheweth evil",s:"?",d:["one that keepeth the law, and hateth pride","one that offereth sacrifice, and walketh justly","one that blesseth the LORD, and hateth sin"]},
{b:"Job",r:"Job 5:19",t:5,p:"He shall deliver thee in six troubles: yea, in seven",a:"there shall no evil touch thee",s:".",d:["he shall not forsake thee","the wicked shall not prosper","thy tabernacle shall be in peace"]},
{b:"Job",r:"Job 14:1",t:3,p:"Man that is born of a woman is",a:"of few days, and full of trouble",s:".",d:["of short time, and full of sorrow","as grass, and withereth away","born to labour, and to die"]},
{b:"Job",r:"Job 28:28",t:3,p:"And unto man he said, Behold, the fear of the Lord, that is wisdom; and",a:"to depart from evil is understanding",s:".",d:["to keep the law is knowledge","to seek his face is prudence","to hate pride is understanding"]},
{b:"Job",r:"Job 38:4",t:4,p:"Where wast thou when",a:"I laid the foundations of the earth",s:"? declare, if thou hast understanding.",d:["I stretched out the heavens","I shut up the sea","I formed the first man"]},

{b:"Psalm",r:"Psalm 16:11",t:3,p:"Thou wilt shew me the path of life: in thy presence is fulness of joy; at thy right hand there are",a:"pleasures for evermore",s:".",d:["riches and honour","rivers of living water","crowns that fade not"]},
{b:"Psalm",r:"Psalm 18:2",t:2,p:"The LORD is my rock, and my fortress, and my deliverer; my God, my strength, in whom I will trust; my buckler, and",a:"the horn of my salvation",s:", and my high tower.",d:["the light of my countenance","the shield of my faith","the song of my deliverance"]},
{b:"Psalm",r:"Psalm 23:4",t:2,p:"Yea, though I walk through the valley of the shadow of death, I will fear no evil: for thou art with me;",a:"thy rod and thy staff they comfort me",s:".",d:["thy hand and thy word they keep me","thy light and thy truth they lead me","thy mercy and thy truth they follow me"]},
{b:"Psalm",r:"Psalm 24:1",t:2,p:"The earth is the LORD'S, and the fulness thereof; the world, and",a:"they that dwell therein",s:".",d:["all that is therein","the cattle upon a thousand hills","the heavens and the seas"]},
{b:"Psalm",r:"Psalm 27:14",t:2,p:"Wait on the LORD: be of good courage, and he shall strengthen thine heart:",a:"wait, I say, on the LORD",s:".",d:["trust, I say, in his name","hope, I say, in his mercy","rest, I say, in his word"]},
{b:"Psalm",r:"Psalm 32:8",t:3,p:"I will instruct thee and teach thee in the way which thou shalt go:",a:"I will guide thee with mine eye",s:".",d:["I will keep thee with my hand","I will lead thee by still waters","I will shew thee my salvation"]},
{b:"Psalm",r:"Psalm 34:18",t:3,p:"The LORD is nigh unto them that are of a broken heart; and saveth such as",a:"be of a contrite spirit",s:".",d:["call upon his name","walk in his statutes","wait upon his word"]},
{b:"Psalm",r:"Psalm 37:5",t:3,p:"Commit thy way unto the LORD; trust also in him; and",a:"he shall bring it to pass",s:".",d:["he shall give thee thy desire","he shall establish thy thoughts","he shall make thy path straight"]},
{b:"Psalm",r:"Psalm 40:1",t:3,p:"I waited patiently for the LORD; and",a:"he inclined unto me, and heard my cry",s:".",d:["he delivered me from the pit","he set my feet upon a rock","he put a new song in my mouth"]},
{b:"Psalm",r:"Psalm 46:10",t:2,p:"Be still, and know that I am God: I will be exalted among the heathen,",a:"I will be exalted in the earth",s:".",d:["I will be feared in Zion","I will be praised for ever","I will be known in Israel"]},
{b:"Psalm",r:"Psalm 51:17",t:3,p:"The sacrifices of God are a broken spirit: a broken and a contrite heart, O God,",a:"thou wilt not despise",s:".",d:["thou wilt not forget","thou wilt not refuse","thou wilt not cast off"]},
{b:"Psalm",r:"Psalm 55:22",t:3,p:"Cast thy burden upon the LORD, and he shall sustain thee: he shall never suffer",a:"the righteous to be moved",s:".",d:["the faithful to be ashamed","the poor to be forgotten","the just to be forsaken"]},
{b:"Psalm",r:"Psalm 62:1",t:3,p:"Truly my soul waiteth upon God: from him cometh",a:"my salvation",s:".",d:["my strength","my defence","my reward"]},
{b:"Psalm",r:"Psalm 73:26",t:3,p:"My flesh and my heart faileth: but God is the strength of my heart, and",a:"my portion for ever",s:".",d:["my refuge in trouble","my song in the night","my hope in death"]},
{b:"Psalm",r:"Psalm 103:1",t:2,p:"Bless the LORD, O my soul: and all that is within me,",a:"bless his holy name",s:".",d:["forget not his benefits","praise him in the congregation","sing unto him a new song"]},
{b:"Psalm",r:"Psalm 103:12",t:3,p:"As far as the east is from the west, so far hath he removed",a:"our transgressions from us",s:".",d:["our iniquities from us","our sins into the sea","our guilt from his sight"]},
{b:"Psalm",r:"Psalm 119:11",t:2,p:"Thy word have I hid in mine heart, that",a:"I might not sin against thee",s:".",d:["I might walk in thy truth","I might teach thy statutes","I might keep thy testimonies"]},
{b:"Psalm",r:"Psalm 127:1",t:2,p:"Except the LORD build the house, they labour in vain that build it: except the LORD keep the city,",a:"the watchman waketh but in vain",s:".",d:["the walls shall surely fall","the people dwell without rest","the gate is opened in vain"]},
{b:"Psalm",r:"Psalm 139:23",t:3,p:"Search me, O God, and know my heart: try me, and",a:"know my thoughts",s:".",d:["know my ways","see my secret sins","prove my reins"]},
{b:"Psalm",r:"Psalm 145:18",t:3,p:"The LORD is nigh unto all them that call upon him, to all that",a:"call upon him in truth",s:".",d:["seek him with the whole heart","fear him in every generation","wait upon him continually"]},

{b:"Proverbs",r:"Proverbs 1:5",t:3,p:"A wise man will hear, and will increase learning; and a man of understanding shall",a:"attain unto wise counsels",s:".",d:["attain unto great riches","attain unto a good name","attain unto long life"]},
{b:"Proverbs",r:"Proverbs 3:7",t:2,p:"Be not wise in thine own eyes:",a:"fear the LORD, and depart from evil",s:".",d:["trust the king, and keep from strife","honour the rich, and flee from want","serve the law, and hate the simple"]},
{b:"Proverbs",r:"Proverbs 9:10",t:2,p:"The fear of the LORD is the beginning of wisdom: and",a:"the knowledge of the holy is understanding",s:".",d:["the love of the law is knowledge","the fear of man is a snare","the instruction of the wise is life"]},
{b:"Proverbs",r:"Proverbs 11:14",t:4,p:"Where no counsel is, the people fall: but",a:"in the multitude of counsellors there is safety",s:".",d:["in the wisdom of princes there is peace","in the word of the king there is power","in the gathering of elders there is rest"]},
{b:"Proverbs",r:"Proverbs 14:12",t:3,p:"There is a way which seemeth right unto a man, but",a:"the end thereof are the ways of death",s:".",d:["the end thereof is destruction","the latter end is vanity","the path thereof leadeth to the grave"]},
{b:"Proverbs",r:"Proverbs 16:9",t:3,p:"A man's heart deviseth his way: but",a:"the LORD directeth his steps",s:".",d:["the LORD establisheth his thoughts","the LORD ordereth his days","the LORD numbereth his goings"]},
{b:"Proverbs",r:"Proverbs 16:18",t:3,p:"Pride goeth before destruction, and",a:"an haughty spirit before a fall",s:".",d:["a froward mouth before shame","a lying tongue before ruin","a scornful look before death"]},
{b:"Proverbs",r:"Proverbs 17:17",t:3,p:"A friend loveth at all times, and",a:"a brother is born for adversity",s:".",d:["a neighbour is near in trouble","a companion stayeth in the night","a kinsman redeemeth in the day"]},
{b:"Proverbs",r:"Proverbs 19:21",t:3,p:"There are many devices in a man's heart; nevertheless",a:"the counsel of the LORD, that shall stand",s:".",d:["the purpose of the king shall stand","the word of the wise shall stand","the thought of the just shall stand"]},
{b:"Proverbs",r:"Proverbs 21:31",t:4,p:"The horse is prepared against the day of battle: but",a:"safety is of the LORD",s:".",d:["victory is of the king","strength is of the mighty","deliverance is of the host"]},
{b:"Proverbs",r:"Proverbs 29:18",t:3,p:"Where there is no vision, the people perish: but he that keepeth the law,",a:"happy is he",s:".",d:["wise is he","blessed is he","safe is he"]},

{b:"Ecclesiastes",r:"Ecclesiastes 1:2",t:2,p:"Vanity of vanities, saith the Preacher, vanity of vanities;",a:"all is vanity",s:".",d:["all is sorrow","all is labour","all is dust"]},
{b:"Ecclesiastes",r:"Ecclesiastes 12:1",t:3,p:"Remember now thy Creator",a:"in the days of thy youth",s:", while the evil days come not, nor the years draw nigh, when thou shalt say, I have no pleasure in them.",d:["in the days of thy strength","while the sun is not darkened","before the silver cord be loosed"]},
{b:"Song of Solomon",r:"Song of Solomon 2:11",t:3,p:"For, lo, the winter is past,",a:"the rain is over and gone",s:".",d:["the summer is come at last","the storm is spent and done","the cold is lifted away"]},

/* ---------------------------- PROPHETS ---------------------------- */
{b:"Isaiah",r:"Isaiah 7:14",t:3,p:"Therefore the Lord himself shall give you a sign; Behold, a virgin shall conceive, and bear a son, and shall",a:"call his name Immanuel",s:".",d:["call his name Wonderful","call his name Israel","call his name David"]},
{b:"Isaiah",r:"Isaiah 26:4",t:3,p:"Trust ye in the LORD for ever: for in the LORD JEHOVAH is",a:"everlasting strength",s:".",d:["everlasting mercy","everlasting light","everlasting peace"]},
{b:"Isaiah",r:"Isaiah 40:8",t:2,p:"The grass withereth, the flower fadeth: but the word of our God",a:"shall stand for ever",s:".",d:["shall not return void","shall judge the nations","shall not pass away"]},
{b:"Isaiah",r:"Isaiah 40:29",t:3,p:"He giveth power to the faint; and to them that have no might",a:"he increaseth strength",s:".",d:["he giveth rest","he sendeth help","he restoreth life"]},
{b:"Isaiah",r:"Isaiah 43:1",t:3,p:"But now thus saith the LORD that created thee, O Jacob, and he that formed thee, O Israel, Fear not: for I have redeemed thee,",a:"I have called thee by thy name",s:": thou art mine.",d:["I have chosen thee from the nations","I have loved thee from of old","I have written thee upon my hands"]},
{b:"Isaiah",r:"Isaiah 43:19",t:3,p:"Behold, I will do a new thing; now it shall spring forth; shall ye not know it? I will even make a way in the wilderness, and",a:"rivers in the desert",s:".",d:["pools in the dry land","streams upon the mountains","wells in the valley"]},
{b:"Isaiah",r:"Isaiah 53:6",t:2,p:"All we like sheep have gone astray; we have turned every one to his own way; and the LORD hath laid on him",a:"the iniquity of us all",s:".",d:["the sins of his people","the transgression of Israel","the guilt of the nations"]},
{b:"Isaiah",r:"Isaiah 54:17",t:3,p:"No weapon that is formed against thee shall prosper; and every tongue that shall rise against thee in judgment thou shalt condemn. This is the heritage of the servants of the LORD, and",a:"their righteousness is of me",s:", saith the LORD.",d:["their reward is with me","their defence is of me","their victory is from me"]},
{b:"Isaiah",r:"Isaiah 55:6",t:2,p:"Seek ye the LORD while he may be found,",a:"call ye upon him while he is near",s:".",d:["return ye unto him with the heart","wait ye upon him in the night","trust ye in him with all your soul"]},
{b:"Isaiah",r:"Isaiah 55:11",t:3,p:"So shall my word be that goeth forth out of my mouth: it shall not return unto me void, but it shall accomplish that which I please, and it shall prosper in",a:"the thing whereto I sent it",s:".",d:["the land whereto I called it","the work that I appointed","the day that I declared"]},
{b:"Isaiah",r:"Isaiah 61:1",t:3,p:"The Spirit of the Lord GOD is upon me; because the LORD hath anointed me to preach good tidings unto the meek; he hath sent me to bind up the brokenhearted, to proclaim",a:"liberty to the captives",s:", and the opening of the prison to them that are bound.",d:["the year of his favour","the day of vengeance","recovery of sight to the blind"]},

{b:"Jeremiah",r:"Jeremiah 17:7",t:3,p:"Blessed is the man that",a:"trusteth in the LORD",s:", and whose hope the LORD is.",d:["trusteth in princes","trusteth in riches","trusteth in Egypt"]},
{b:"Jeremiah",r:"Jeremiah 17:14",t:4,p:"Heal me, O LORD, and I shall be healed; save me, and I shall be saved: for",a:"thou art my praise",s:".",d:["thou art my hope","thou art my healer","thou art my God"]},
{b:"Jeremiah",r:"Jeremiah 20:9",t:4,p:"Then I said, I will not make mention of him, nor speak any more in his name. But his word was in mine heart as a burning fire shut up in my bones, and I was weary with forbearing, and",a:"I could not stay",s:".",d:["I could not rest","I could not keep silence","I could not refrain"]},
{b:"Jeremiah",r:"Jeremiah 23:29",t:4,p:"Is not my word like as a fire? saith the LORD; and like a hammer that",a:"breaketh the rock in pieces",s:"?",d:["divideth asunder the soul","overfloweth the banks","shineth in the darkness"]},
{b:"Jeremiah",r:"Jeremiah 32:17",t:3,p:"Ah Lord GOD! behold, thou hast made the heaven and the earth by thy great power and stretched out arm, and",a:"there is nothing too hard for thee",s:".",d:["there is none like unto thee","there is no God beside thee","there is no secret with thee"]},

{b:"Lamentations",r:"Lamentations 3:21",t:4,p:"This I recall to my mind, therefore",a:"have I hope",s:".",d:["have I peace","have I rest","have I comfort"]},
{b:"Ezekiel",r:"Ezekiel 11:19",t:4,p:"And I will give them one heart, and I will put a new spirit within you; and I will take the stony heart out of their flesh, and will give them",a:"an heart of flesh",s:".",d:["an heart to know me","an heart that is clean","an heart after my own"]},
{b:"Ezekiel",r:"Ezekiel 36:27",t:4,p:"And I will put my spirit within you, and cause you to walk in my statutes, and",a:"ye shall keep my judgments, and do them",s:".",d:["ye shall be my people, and I your God","ye shall dwell in the land in peace","ye shall remember your evil ways"]},
{b:"Daniel",r:"Daniel 3:25",t:3,p:"He answered and said, Lo, I see four men loose, walking in the midst of the fire, and they have no hurt; and the form of the fourth is",a:"like the Son of God",s:".",d:["like an angel of the LORD","like a man of fire","like the God of Israel"]},
{b:"Daniel",r:"Daniel 6:22",t:4,p:"My God hath sent his angel, and hath shut the lions' mouths, that they have not hurt me: forasmuch as",a:"before him innocency was found in me",s:"; and also before thee, O king, have I done no hurt.",d:["he found no fault in me","I served him continually","I was faithful in the matter"]},

{b:"Hosea",r:"Hosea 6:3",t:4,p:"Then shall we know, if we follow on to know the LORD: his going forth is prepared as the morning; and he shall come unto us as the rain, as",a:"the latter and former rain unto the earth",s:".",d:["the dew upon the grass in the field","the flood upon the land in the night","the snow upon the hills in winter"]},
{b:"Hosea",r:"Hosea 11:4",t:5,p:"I drew them with cords of a man, with bands of love: and I was to them as they that take off the yoke on their jaws, and",a:"I laid meat unto them",s:".",d:["I taught them to go","I healed their backsliding","I called my son out of Egypt"]},
{b:"Amos",r:"Amos 3:7",t:4,p:"Surely the Lord GOD will do nothing, but he revealeth his secret unto",a:"his servants the prophets",s:".",d:["the house of Israel","them that fear him","the remnant of Jacob"]},
{b:"Micah",r:"Micah 7:7",t:4,p:"Therefore I will look unto the LORD; I will wait for the God of my salvation:",a:"my God will hear me",s:".",d:["my God will save me","my God will arise","my God will not fail"]},
{b:"Habakkuk",r:"Habakkuk 2:20",t:3,p:"But the LORD is in his holy temple:",a:"let all the earth keep silence before him",s:".",d:["let all flesh fear before him","let the nations be still","let Zion rejoice in him"]},
{b:"Zechariah",r:"Zechariah 13:1",t:4,p:"In that day there shall be a fountain opened to the house of David and to the inhabitants of Jerusalem",a:"for sin and for uncleanness",s:".",d:["for healing and for peace","for Judah and for Israel","for the remnant and for the stranger"]},
{b:"Malachi",r:"Malachi 3:1",t:3,p:"Behold, I will send my messenger, and he shall prepare the way before me: and the Lord, whom ye seek, shall suddenly come to his temple, even the messenger of the covenant, whom ye delight in: behold,",a:"he shall come, saith the LORD of hosts",s:".",d:["he shall sit as a refiner","he shall purify the sons of Levi","he shall suddenly appear"]},

/* ---------------------------- GOSPELS ---------------------------- */
{b:"Matthew",r:"Matthew 4:4",t:2,p:"But he answered and said, It is written, Man shall not live by bread alone, but by every word that proceedeth out of",a:"the mouth of God",s:".",d:["the law of Moses","the mouth of the prophets","the book of the LORD"]},
{b:"Matthew",r:"Matthew 5:3",t:2,p:"Blessed are the poor in spirit: for",a:"theirs is the kingdom of heaven",s:".",d:["they shall inherit the earth","they shall be comforted","they shall see God"]},
{b:"Matthew",r:"Matthew 5:8",t:2,p:"Blessed are the pure in heart: for",a:"they shall see God",s:".",d:["they shall obtain mercy","they shall be called the children of God","theirs is the kingdom of heaven"]},
{b:"Matthew",r:"Matthew 5:9",t:2,p:"Blessed are the peacemakers: for",a:"they shall be called the children of God",s:".",d:["they shall inherit the earth","they shall see God","theirs is the kingdom of heaven"]},
{b:"Matthew",r:"Matthew 5:44",t:3,p:"But I say unto you, Love your enemies, bless them that curse you, do good to them that hate you, and pray for them which",a:"despitefully use you, and persecute you",s:".",d:["despitefully speak against you","would take your coat also","smite you on the right cheek"]},
{b:"Matthew",r:"Matthew 6:9",t:1,p:"After this manner therefore pray ye:",a:"Our Father which art in heaven",s:", Hallowed be thy name.",d:["Our Father which art above","Our God which dwellest in Zion","Our Lord which sittest on high"]},
{b:"Matthew",r:"Matthew 7:14",t:3,p:"Because strait is the gate, and",a:"narrow is the way",s:", which leadeth unto life, and few there be that find it.",d:["broad is the path","crooked is the path","dark is the road"]},
{b:"Matthew",r:"Matthew 6:34",t:3,p:"Take therefore no thought for the morrow: for the morrow shall take thought for the things of itself.",a:"Sufficient unto the day is the evil thereof",s:".",d:["The morrow shall care for itself","Each day hath its own trouble","Let the day suffice for itself"]},
{b:"Matthew",r:"Matthew 7:13",t:3,p:"Enter ye in at the strait gate: for wide is the gate, and broad is the way, that leadeth to destruction, and",a:"many there be which go in thereat",s:".",d:["few there be that find it","many there be that seek it","few there be which walk therein"]},
{b:"Matthew",r:"Matthew 9:37",t:3,p:"Then saith he unto his disciples, The harvest truly is plenteous, but",a:"the labourers are few",s:".",d:["the fields are white","the time is short","the reapers are weary"]},
{b:"Matthew",r:"Matthew 10:28",t:3,p:"And fear not them which kill the body, but are not able to kill the soul: but rather fear him which is able to destroy",a:"both soul and body in hell",s:".",d:["both flesh and spirit in the grave","both the soul and the life","both man and beast in the pit"]},
{b:"Matthew",r:"Matthew 11:29",t:3,p:"Take my yoke upon you, and learn of me; for I am meek and lowly in heart: and",a:"ye shall find rest unto your souls",s:".",d:["ye shall be free indeed","ye shall inherit the earth","ye shall have peace with God"]},
{b:"Matthew",r:"Matthew 16:24",t:3,p:"Then said Jesus unto his disciples, If any man will come after me, let him deny himself, and take up his cross, and",a:"follow me",s:".",d:["keep my words","lose his life","come after me daily"]},
{b:"Matthew",r:"Matthew 18:20",t:2,p:"For where two or three are gathered together in my name, there am I",a:"in the midst of them",s:".",d:["in the midst of the church","among them that believe","with them that gather"]},
{b:"Matthew",r:"Matthew 22:37",t:2,p:"Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and",a:"with all thy mind",s:".",d:["with all thy strength","with all thy might","with all thy understanding"]},
{b:"Matthew",r:"Matthew 24:35",t:2,p:"Heaven and earth shall pass away, but",a:"my words shall not pass away",s:".",d:["my kingdom shall not pass away","my law shall not pass away","my name shall not pass away"]},
{b:"Matthew",r:"Matthew 25:21",t:3,p:"His lord said unto him, Well done, thou good and faithful servant: thou hast been faithful over a few things, I will make thee ruler over many things:",a:"enter thou into the joy of thy lord",s:".",d:["enter thou into my rest","sit thou at my right hand","inherit the kingdom prepared for thee"]},

{b:"Mark",r:"Mark 1:17",t:2,p:"And Jesus said unto them, Come ye after me, and I will make you to become",a:"fishers of men",s:".",d:["teachers of the law","shepherds of the flock","witnesses unto me"]},
{b:"Mark",r:"Mark 9:23",t:3,p:"Jesus said unto him, If thou canst believe,",a:"all things are possible to him that believeth",s:".",d:["nothing shall be impossible unto you","all things are possible with God","thy faith hath made thee whole"]},
{b:"Mark",r:"Mark 10:14",t:3,p:"But when Jesus saw it, he was much displeased, and said unto them, Suffer the little children to come unto me, and forbid them not: for",a:"of such is the kingdom of God",s:".",d:["of such is the kingdom of heaven","to such belongeth the promise","these are the least in the kingdom"]},

{b:"Luke",r:"Luke 6:27",t:3,p:"But I say unto you which hear, Love your enemies,",a:"do good to them which hate you",s:".",d:["bless them that curse you","pray for them which despitefully use you","give to every man that asketh of thee"]},
{b:"Luke",r:"Luke 9:24",t:3,p:"For whosoever will save his life shall lose it: but whosoever will lose his life for my sake,",a:"the same shall save it",s:".",d:["the same shall find it","the same shall keep it","the same shall live"]},
{b:"Luke",r:"Luke 12:15",t:3,p:"And he said unto them, Take heed, and beware of covetousness: for a man's life consisteth not in",a:"the abundance of the things which he possesseth",s:".",d:["the length of his days","the honour that men give him","the treasure that he layeth up"]},
{b:"Luke",r:"Luke 12:32",t:3,p:"Fear not, little flock; for it is your Father's good pleasure",a:"to give you the kingdom",s:".",d:["to give you the Spirit","to give you rest","to give you the inheritance"]},
{b:"Luke",r:"Luke 18:27",t:3,p:"And he said, The things which are impossible with men are",a:"possible with God",s:".",d:["possible to them that believe","easy with the Father","nothing with God"]},

{b:"John",r:"John 1:14",t:2,p:"And the Word was made flesh, and dwelt among us, (and we beheld his glory, the glory as of the only begotten of the Father,)",a:"full of grace and truth",s:".",d:["full of glory and power","full of mercy and peace","full of light and life"]},
{b:"John",r:"John 1:29",t:2,p:"The next day John seeth Jesus coming unto him, and saith, Behold the Lamb of God, which",a:"taketh away the sin of the world",s:".",d:["taketh away the sins of his people","beareth the iniquity of us all","was slain from the foundation"]},
{b:"John",r:"John 3:3",t:2,p:"Jesus answered and said unto him, Verily, verily, I say unto thee, Except a man be born again, he cannot",a:"see the kingdom of God",s:".",d:["enter into life eternal","inherit the kingdom of heaven","come unto the Father"]},
{b:"John",r:"John 3:30",t:3,p:"He must increase, but",a:"I must decrease",s:".",d:["I must give place","I must be silent","I must go before him"]},
{b:"John",r:"John 4:24",t:2,p:"God is a Spirit: and they that worship him must worship him",a:"in spirit and in truth",s:".",d:["in holiness and in fear","in faith and in love","in the beauty of holiness"]},
{b:"John",r:"John 5:24",t:3,p:"Verily, verily, I say unto you, He that heareth my word, and believeth on him that sent me, hath everlasting life, and shall not come into condemnation; but",a:"is passed from death unto life",s:".",d:["is born of water and of the Spirit","is sealed unto the day of redemption","is hid with Christ in God"]},
{b:"John",r:"John 6:35",t:2,p:"And Jesus said unto them, I am the bread of life: he that cometh to me shall never hunger; and he that believeth on me",a:"shall never thirst",s:".",d:["shall never perish","shall never walk in darkness","shall never see death"]},
{b:"John",r:"John 8:12",t:2,p:"Then spake Jesus again unto them, saying, I am the light of the world: he that followeth me shall not walk in darkness, but shall have",a:"the light of life",s:".",d:["the light of men","the light of the knowledge of God","the true light"]},
{b:"John",r:"John 10:11",t:2,p:"I am the good shepherd: the good shepherd",a:"giveth his life for the sheep",s:".",d:["knoweth his sheep by name","leadeth them beside still waters","calleth his own sheep by name"]},
{b:"John",r:"John 11:25",t:2,p:"Jesus said unto her, I am the resurrection, and the life: he that believeth in me, though he were dead,",a:"yet shall he live",s:".",d:["yet shall he rise","yet shall he not die","yet shall he see God"]},
{b:"John",r:"John 13:34",t:2,p:"A new commandment I give unto you, That ye love one another; as I have loved you, that",a:"ye also love one another",s:".",d:["ye also keep my words","ye also follow me","ye also abide in me"]},
{b:"John",r:"John 14:1",t:2,p:"Let not your heart be troubled: ye believe in God,",a:"believe also in me",s:".",d:["believe also my words","believe also the works","believe also the Father"]},
{b:"John",r:"John 14:27",t:2,p:"Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither",a:"let it be afraid",s:".",d:["let it be dismayed","let it be shaken","let it be divided"]},
{b:"John",r:"John 15:13",t:2,p:"Greater love hath no man than this, that a man",a:"lay down his life for his friends",s:".",d:["give his goods to the poor","love his neighbour as himself","forgive his brother seventy times"]},
{b:"John",r:"John 16:33",t:2,p:"These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer;",a:"I have overcome the world",s:".",d:["I have finished the work","I have kept my own","I have conquered death"]},
{b:"John",r:"John 17:17",t:3,p:"Sanctify them through thy truth:",a:"thy word is truth",s:".",d:["thy law is truth","thy name is truth","thy way is truth"]},
{b:"John",r:"John 20:29",t:3,p:"Jesus saith unto him, Thomas, because thou hast seen me, thou hast believed: blessed are they that have not seen, and",a:"yet have believed",s:".",d:["yet have followed","yet have loved me","yet have kept my word"]},

/* ---------------------------- ACTS / EPISTLES ---------------------------- */
{b:"Acts",r:"Acts 4:31",t:4,p:"And when they had prayed, the place was shaken where they were assembled together; and they were all filled with the Holy Ghost, and they",a:"spake the word of God with boldness",s:".",d:["went forth preaching the kingdom","continued in the apostles' doctrine","sold their possessions and goods"]},
{b:"Acts",r:"Acts 16:9",t:4,p:"And a vision appeared to Paul in the night; There stood a man of Macedonia, and prayed him, saying, Come over into Macedonia, and",a:"help us",s:".",d:["preach unto us","teach us the way","save us"]},

{b:"Romans",r:"Romans 1:16",t:2,p:"For I am not ashamed of the gospel of Christ: for it is the power of God unto salvation to every one that believeth; to the Jew first, and",a:"also to the Greek",s:".",d:["also to the Gentile","also to the nations","also to the barbarian"]},
{b:"Romans",r:"Romans 5:1",t:2,p:"Therefore being justified by faith, we have",a:"peace with God through our Lord Jesus Christ",s:".",d:["access by faith into this grace","the love of God shed abroad","joy in the Holy Ghost"]},
{b:"Romans",r:"Romans 8:1",t:2,p:"There is therefore now no condemnation to them which are in Christ Jesus, who walk not after the flesh, but",a:"after the Spirit",s:".",d:["after the law","after the letter","after their own hearts"]},
{b:"Romans",r:"Romans 8:31",t:2,p:"What shall we then say to these things? If God be for us,",a:"who can be against us",s:"?",d:["who shall separate us","who shall lay any thing to our charge","who shall condemn us"]},
{b:"Romans",r:"Romans 10:13",t:2,p:"For whosoever shall call upon the name of the Lord",a:"shall be saved",s:".",d:["shall not be ashamed","shall be justified","shall not perish"]},
{b:"Romans",r:"Romans 12:1",t:3,p:"I beseech you therefore, brethren, by the mercies of God, that ye present your bodies a living sacrifice, holy, acceptable unto God, which is",a:"your reasonable service",s:".",d:["your spiritual worship","your acceptable offering","your holy calling"]},
{b:"Romans",r:"Romans 12:21",t:3,p:"Be not overcome of evil, but",a:"overcome evil with good",s:".",d:["overcome evil with faith","overcome evil with truth","overcome evil with prayer"]},
{b:"Romans",r:"Romans 15:13",t:3,p:"Now the God of hope fill you with all joy and peace in believing, that ye may abound in hope, through",a:"the power of the Holy Ghost",s:".",d:["the comfort of the scriptures","the grace of our Lord","the love of God"]},

{b:"1 Corinthians",r:"1 Corinthians 1:18",t:3,p:"For the preaching of the cross is to them that perish foolishness; but unto us which are saved it is",a:"the power of God",s:".",d:["the wisdom of God","the savour of life","the gospel of peace"]},
{b:"1 Corinthians",r:"1 Corinthians 6:19",t:3,p:"What? know ye not that your body is the temple of the Holy Ghost which is in you, which ye have of God, and",a:"ye are not your own",s:"?",d:["ye are bought with a price","ye are the body of Christ","ye are sealed unto the day"]},
{b:"1 Corinthians",r:"1 Corinthians 15:58",t:3,p:"Therefore, my beloved brethren, be ye stedfast, unmoveable, always abounding in the work of the Lord, forasmuch as ye know that your labour is",a:"not in vain in the Lord",s:".",d:["not forgotten before God","not without a reward","not counted as loss"]},

{b:"2 Corinthians",r:"2 Corinthians 4:16",t:3,p:"For which cause we faint not; but though our outward man perish, yet",a:"the inward man is renewed day by day",s:".",d:["the inner man is strengthened","the hidden man is kept","the new man is put on"]},
{b:"2 Corinthians",r:"2 Corinthians 5:21",t:3,p:"For he hath made him to be sin for us, who knew no sin; that we might be made",a:"the righteousness of God in him",s:".",d:["the children of God in him","the wisdom of God in him","the holiness of God in him"]},
{b:"2 Corinthians",r:"2 Corinthians 12:10",t:4,p:"Therefore I take pleasure in infirmities, in reproaches, in necessities, in persecutions, in distresses for Christ's sake: for when I am weak,",a:"then am I strong",s:".",d:["then is he strong","then am I content","then is grace sufficient"]},

{b:"Galatians",r:"Galatians 2:16",t:3,p:"Knowing that a man is not justified by the works of the law, but by the faith of Jesus Christ, even we have believed in Jesus Christ, that we might be justified by the faith of Christ, and not by the works of the law: for by the works of the law shall",a:"no flesh be justified",s:".",d:["no man be saved","none be counted righteous","no soul be made perfect"]},
{b:"Galatians",r:"Galatians 5:16",t:3,p:"This I say then, Walk in the Spirit, and ye shall not",a:"fulfil the lust of the flesh",s:".",d:["fulfil the works of darkness","fulfil the desires of the mind","fulfil the will of the world"]},
{b:"Galatians",r:"Galatians 6:2",t:3,p:"Bear ye one another's burdens, and so",a:"fulfil the law of Christ",s:".",d:["fulfil the royal law","fulfil the law of love","fulfil the will of God"]},

{b:"Ephesians",r:"Ephesians 3:16",t:4,p:"That he would grant you, according to the riches of his glory, to be strengthened with might by his Spirit",a:"in the inner man",s:".",d:["in the hidden man","in the new man","in the whole body"]},
{b:"Ephesians",r:"Ephesians 4:15",t:4,p:"But speaking the truth in love, may grow up into him in all things, which is",a:"the head, even Christ",s:".",d:["the head of the church","the chief corner stone","the firstborn from the dead"]},
{b:"Ephesians",r:"Ephesians 6:13",t:3,p:"Wherefore take unto you the whole armour of God, that ye may be able to withstand in the evil day, and having done all,",a:"to stand",s:".",d:["to fight","to overcome","to endure"]},

{b:"Philippians",r:"Philippians 1:6",t:3,p:"Being confident of this very thing, that he which hath begun a good work in you will perform it until",a:"the day of Jesus Christ",s:".",d:["the appearing of our Lord","the last trumpet","the redemption of the body"]},
{b:"Philippians",r:"Philippians 2:3",t:3,p:"Let nothing be done through strife or vainglory; but in lowliness of mind let each",a:"esteem other better than themselves",s:".",d:["esteem others as himself","esteem the weak as strong","esteem the least as greatest"]},
{b:"Philippians",r:"Philippians 2:5",t:3,p:"Let this mind be in you, which was also",a:"in Christ Jesus",s:".",d:["in the Son of God","in our Lord","in him that served"]},
{b:"Philippians",r:"Philippians 3:14",t:3,p:"I press toward the mark for the prize of",a:"the high calling of God in Christ Jesus",s:".",d:["the upward call of God","the heavenly calling in Christ","the prize of our high calling"]},

{b:"Colossians",r:"Colossians 1:13",t:4,p:"Who hath delivered us from the power of darkness, and hath translated us into",a:"the kingdom of his dear Son",s:".",d:["the kingdom of his Christ","the kingdom of light","the kingdom of heaven"]},
{b:"Colossians",r:"Colossians 3:16",t:3,p:"Let the word of Christ dwell in you richly in all wisdom; teaching and admonishing one another in psalms and hymns and spiritual songs, singing with grace in your hearts",a:"to the Lord",s:".",d:["to God","to one another","to the church"]},

{b:"1 Thessalonians",r:"1 Thessalonians 4:13",t:4,p:"But I would not have you to be ignorant, brethren, concerning them which are asleep, that ye sorrow not, even as others which",a:"have no hope",s:".",d:["have no God","have no comfort","have no resurrection"]},
{b:"2 Timothy",r:"2 Timothy 1:12",t:3,p:"For the which cause I also suffer these things: nevertheless I am not ashamed: for I know whom I have believed, and am persuaded that he is able to keep that which I have committed unto him",a:"against that day",s:".",d:["until the end","unto the coming of Christ","until I finish my course"]},
{b:"2 Timothy",r:"2 Timothy 2:13",t:4,p:"If we believe not, yet he abideth faithful:",a:"he cannot deny himself",s:".",d:["he cannot lie","he cannot fail","he cannot change"]},
{b:"2 Timothy",r:"2 Timothy 4:17",t:5,p:"Notwithstanding the Lord stood with me, and strengthened me; that by me the preaching might be fully known, and that all the Gentiles might hear: and I was delivered out of",a:"the mouth of the lion",s:".",d:["every evil work","the hand of Nero","the mouth of the accuser"]},

{b:"Hebrews",r:"Hebrews 10:23",t:3,p:"Let us hold fast the profession of our faith without wavering; (for",a:"he is faithful that promised",s:";)",d:["he is able that promised","he is true that called us","he is just that justifieth"]},
{b:"Hebrews",r:"Hebrews 11:6",t:2,p:"But without faith it is impossible to please him: for he that cometh to God must believe that he is, and that he is",a:"a rewarder of them that diligently seek him",s:".",d:["a rewarder of them that fear him","a keeper of them that trust him","a helper of them that wait for him"]},
{b:"Hebrews",r:"Hebrews 12:14",t:3,p:"Follow peace with all men, and holiness, without which",a:"no man shall see the Lord",s:".",d:["no man shall enter in","no man shall be justified","no man shall inherit the kingdom"]},
{b:"Hebrews",r:"Hebrews 13:5",t:2,p:"Let your conversation be without covetousness; and be content with such things as ye have: for he hath said,",a:"I will never leave thee, nor forsake thee",s:".",d:["I will never fail thee, nor forget thee","I am with you alway","I will be with thee, and will keep thee"]},

{b:"James",r:"James 1:2",t:3,p:"My brethren, count it all joy when ye fall into",a:"divers temptations",s:".",d:["divers trials","manifold temptations","fiery trials"]},
{b:"James",r:"James 1:12",t:3,p:"Blessed is the man that endureth temptation: for when he is tried, he shall receive the crown of life, which the Lord hath promised to them that",a:"love him",s:".",d:["fear him","wait for him","keep his word"]},
{b:"James",r:"James 2:17",t:3,p:"Even so faith, if it hath not works, is dead,",a:"being alone",s:".",d:["being barren","being empty","being vain"]},
{b:"James",r:"James 4:8",t:2,p:"Draw nigh to God, and he will draw nigh to you. Cleanse your hands, ye sinners; and",a:"purify your hearts, ye double minded",s:".",d:["humble yourselves in his sight","resist the devil, and he will flee","be afflicted, and mourn, and weep"]},

{b:"1 Peter",r:"1 Peter 5:8",t:3,p:"Be sober, be vigilant; because your adversary the devil, as a roaring lion, walketh about,",a:"seeking whom he may devour",s:".",d:["seeking whom he may sift","seeking whom he may accuse","seeking whom he may destroy"]},
{b:"1 John",r:"1 John 1:5",t:3,p:"This then is the message which we have heard of him, and declare unto you, that God is light, and",a:"in him is no darkness at all",s:".",d:["in him is no shadow of turning","in him is no unrighteousness","in him is no variableness"]},
{b:"1 John",r:"1 John 4:18",t:3,p:"There is no fear in love; but perfect love casteth out fear: because fear hath torment. He that feareth",a:"is not made perfect in love",s:".",d:["is not born of God","hath not known God","abideth in death"]},
{b:"1 John",r:"1 John 5:4",t:3,p:"For whatsoever is born of God overcometh the world: and this is the victory that overcometh the world, even",a:"our faith",s:".",d:["our love","our hope","our witness"]},

{b:"Revelation",r:"Revelation 1:18",t:3,p:"I am he that liveth, and was dead; and, behold, I am alive for evermore, Amen; and have",a:"the keys of hell and of death",s:".",d:["the keys of the kingdom","the keys of David","the keys of the bottomless pit"]},
{b:"Revelation",r:"Revelation 2:10",t:3,p:"Fear none of those things which thou shalt suffer: behold, the devil shall cast some of you into prison, that ye may be tried; and ye shall have tribulation ten days: be thou faithful unto death, and",a:"I will give thee a crown of life",s:".",d:["I will give thee the morning star","I will give thee a white stone","I will give thee power over the nations"]},
{b:"Revelation",r:"Revelation 3:11",t:4,p:"Behold, I come quickly: hold that fast which thou hast, that",a:"no man take thy crown",s:".",d:["no man deceive thee","no man steal thy reward","no man quench thy light"]},
{b:"Revelation",r:"Revelation 7:17",t:4,p:"For the Lamb which is in the midst of the throne shall feed them, and shall lead them unto living fountains of waters: and God shall wipe away",a:"all tears from their eyes",s:".",d:["all sorrow from their hearts","all night from their path","all fear from their souls"]},
{b:"Revelation",r:"Revelation 19:16",t:3,p:"And he hath on his vesture and on his thigh a name written,",a:"KING OF KINGS, AND LORD OF LORDS",s:".",d:["FAITHFUL AND TRUE","THE WORD OF GOD","ALPHA AND OMEGA"]},
{b:"Revelation",r:"Revelation 21:5",t:3,p:"And he that sat upon the throne said, Behold, I make all things new. And he said unto me, Write: for",a:"these words are true and faithful",s:".",d:["these sayings are faithful and true","this is the true sayings of God","the testimony of Jesus is the spirit of prophecy"]},
{b:"Revelation",r:"Revelation 22:20",t:3,p:"He which testifieth these things saith, Surely I come quickly. Amen.",a:"Even so, come, Lord Jesus",s:".",d:["Even so, come quickly","Come, Lord, and do not tarry","Amen. Come, thou King"]}
];

if(typeof module !== "undefined" && module.exports) module.exports = VERSES_ASCENT;
