/* ==================================================================
   TRUE / FALSE CLAIMS — the Judgement questions.
   Each claim is a standalone statement about scripture's people,
   places, numbers and events. The claim replaces the 7th verse
   question of every pilgrimage site (slot 6) and is drawn from the
   site's book territory where possible.

   Shape: { b: territory book (BOOKS_ORDER name),
            t: difficulty tier (1 = familiar, 2 = subtle, 3 = deep-cut),
            s: the claim shown to the player,
            v: true | false,
            why: the correction shown on a miss, with its reference }

   Authoring rules (enforced by test/truefalse.test.js):
   - statements are undisputed KJV facts — no debated authorship,
     no manuscript variants, no trick phrasing that could be read
     either way;
   - `why` always carries the anchor reference so a miss teaches;
   - `b` decides which sites surface the claim (territory match);
   - `t` biases claim draws toward the site's arc position.
   ================================================================== */
const TF_CLAIMS = [
{"b":"Genesis","t":1,"s":"Sarah was Abraham's wife.","v":true,"why":"God said: Sarah thy wife shall bear thee a son (Genesis 17:15-19)."},
{"b":"Genesis","t":1,"s":"Joseph's brothers sold him to the Ishmeelites for twenty pieces of silver.","v":true,"why":"They sold Joseph to the Ishmeelites for twenty pieces of silver (Genesis 37:28)."},
{"b":"Genesis","t":1,"s":"Benjamin was Rachel's son.","v":true,"why":"Benjamin was born of Rachel on the way to Ephrath (Genesis 35:16-18)."},
{"b":"Genesis","t":1,"s":"Adam called his wife's name Eve.","v":true,"why":"Adam called his wife's name Eve, because she was the mother of all living (Genesis 3:20)."},
{"b":"Genesis","t":1,"s":"Pharaoh set Joseph over all the land of Egypt.","v":true,"why":"Pharaoh said: thou shalt be over my house — without thee shall no man lift up his hand (Genesis 41:41-44)."},
{"b":"Genesis","t":1,"s":"Lot was Abraham's brother.","v":false,"why":"Lot was Abram's nephew — his brother Haran's son (Genesis 12:5)."},
{"b":"Genesis","t":1,"s":"Jacob was Isaac's father.","v":false,"why":"Isaac was Jacob's father — the elder bore the younger (Genesis 25:26)."},
{"b":"Genesis","t":1,"s":"Abel rose up against Cain and slew him.","v":false,"why":"Cain rose up against Abel his brother, and slew him (Genesis 4:8)."},
{"b":"Genesis","t":1,"s":"The ark rested upon the mountains of Sinai.","v":false,"why":"The ark rested upon the mountains of Ararat (Genesis 8:4)."},
{"b":"Genesis","t":1,"s":"Eve was formed before Adam.","v":false,"why":"Adam was formed first, then Eve — the rib taken from his side (Genesis 2:7, 21-22)."},
{"b":"Genesis","t":1,"s":"Esau sold his birthright for gold.","v":false,"why":"He sold it for bread and pottage of lentiles (Genesis 25:33-34)."},
{"b":"Genesis","t":1,"s":"Isaac blessed Esau with the firstborn blessing.","v":false,"why":"Jacob obtained the blessing of the firstborn through subtle deception (Genesis 27:35-36)."},
{"b":"Genesis","t":1,"s":"The forbidden fruit in Eden is identified in Genesis as an apple.","v":false,"why":"Genesis names only the fruit of the tree of knowledge — no apple is ever mentioned (Genesis 3:3-6)."},
{"b":"Genesis","t":2,"s":"Melchizedek was king of Salem and priest of the most high God.","v":true,"why":"Melchizedek king of Salem brought forth bread and wine (Genesis 14:18)."},
{"b":"Genesis","t":2,"s":"Rebekah was the sister of Laban.","v":true,"why":"Rebekah had a brother, and his name was Laban (Genesis 24:29)."},
{"b":"Genesis","t":2,"s":"Noah took two of every clean beast into the ark.","v":false,"why":"Clean beasts came in by sevens — two was the rule for unclean (Genesis 7:2)."},
{"b":"Genesis","t":2,"s":"Rachel was Jacob's daughter.","v":false,"why":"Rachel was Jacob's wife, given him in Haran (Genesis 29:28)."},
{"b":"Genesis","t":2,"s":"Haran was Lot's son.","v":false,"why":"Haran was Lot's father — Haran begat Lot (Genesis 11:27)."},
{"b":"Genesis","t":2,"s":"Leah was younger than Rachel.","v":false,"why":"Leah was the elder and Rachel the younger (Genesis 29:16)."},
{"b":"Genesis","t":2,"s":"Ishmael was born of Sarah.","v":false,"why":"Ishmael was the son of Hagar the Egyptian handmaid (Genesis 16:15)."},
{"b":"Genesis","t":2,"s":"Abraham was seventy years old when Isaac was born.","v":false,"why":"Abraham was an hundred years old when his son Isaac was born (Genesis 21:5)."},
{"b":"Genesis","t":2,"s":"Joseph had ten brothers in total.","v":false,"why":"Jacob had twelve sons — Joseph had eleven brothers (Genesis 35:22)."},
{"b":"Genesis","t":2,"s":"Cain was a keeper of sheep and Abel was a tiller of the ground.","v":false,"why":"Abel was a keeper of sheep, but Cain was a tiller of the ground (Genesis 4:2)."},
{"b":"Genesis","t":2,"s":"Joseph gave Benjamin five changes of raiment and three pieces of gold.","v":false,"why":"He gave him three hundred pieces of silver, and five changes of raiment (Genesis 45:22)."},
{"b":"Genesis","t":3,"s":"Methuselah lived nine hundred sixty and nine years.","v":true,"why":"And all the days of Methuselah were nine hundred sixty and nine years: and he died (Genesis 5:27)."},
{"b":"Genesis","t":3,"s":"Judah pledged his life for Benjamin before Joseph.","v":true,"why":"Judah said: I will be surety for him; of my hand shalt thou require him (Genesis 43:9)."},
{"b":"Genesis","t":3,"s":"Enoch died and was buried by Adam.","v":false,"why":"Enoch walked with God: and he was not; for God took him (Genesis 5:24)."},
{"b":"Genesis","t":3,"s":"Terah died in Ur of the Chaldees.","v":false,"why":"Terah died in Haran after journeying from Ur (Genesis 11:31-32)."},
{"b":"Exodus","t":1,"s":"Miriam was Aaron's sister.","v":true,"why":"Miriam the prophetess, sister to Aaron, led the women with timbrels (Exodus 15:20)."},
{"b":"Exodus","t":1,"s":"The golden calf was fashioned by Aaron.","v":true,"why":"Aaron fashioned it with a graving tool of the people's golden earrings (Exodus 32:2-4)."},
{"b":"Exodus","t":1,"s":"Moses was drawn out of the water by Pharaoh's daughter.","v":true,"why":"She called his name Moses — drawn out of the water (Exodus 2:5-10)."},
{"b":"Exodus","t":1,"s":"Moses was Jethro's father.","v":false,"why":"Jethro was Moses' father in law, priest of Midian (Exodus 3:1)."},
{"b":"Exodus","t":1,"s":"Aaron was Moses' son.","v":false,"why":"Aaron was Moses' brother — his mouth in Egypt (Exodus 4:14; 7:1)."},
{"b":"Exodus","t":1,"s":"Egypt was smitten with seven plagues.","v":false,"why":"Ten plagues fell — from blood to the death of the firstborn (Exodus 7-12)."},
{"b":"Exodus","t":1,"s":"Israel ate manna in the wilderness for twenty years.","v":false,"why":"Israel did eat manna forty years, until they came to Canaan's border (Exodus 16:35)."},
{"b":"Exodus","t":1,"s":"Pharaoh commanded all Hebrew baby girls to be drowned in the river.","v":false,"why":"Every son that is born ye shall cast into the river — girls were saved alive (Exodus 1:22)."},
{"b":"Exodus","t":1,"s":"Pharaoh drowned in the Red Sea alongside his chariots.","v":false,"why":"The scriptures state that the waters covered the chariots and horsemen, but never explicitly state Pharaoh himself drowned (Exodus 14:28)."},
{"b":"Exodus","t":1,"s":"The first plague upon Egypt was frogs in all the houses.","v":false,"why":"The first plague was turning all the waters of Egypt into blood (Exodus 7:20)."},
{"b":"Exodus","t":2,"s":"Moses was fourscore years old when he spake unto Pharaoh.","v":true,"why":"Aaron was three and eighty, and Moses fourscore, when they spake unto Pharaoh (Exodus 7:7)."},
{"b":"Exodus","t":2,"s":"The LORD led Israel by a pillar of cloud by day and fire by night.","v":true,"why":"The LORD went before them by day in a pillar of a cloud, and by night in a pillar of fire (Exodus 13:21)."},
{"b":"Exodus","t":2,"s":"The tabernacle was built by Moses's own hands alone.","v":false,"why":"Bezaleel and Aholiab were filled with the spirit to build it (Exodus 31:1-6)."},
{"b":"Exodus","t":2,"s":"The bush burned with fire and was consumed.","v":false,"why":"Behold, the bush burned with fire, and the bush was not consumed (Exodus 3:2)."},
{"b":"Exodus","t":2,"s":"The Israelites dwelt in Egypt fourscore years.","v":false,"why":"The sojourning of the children of Israel in Egypt was four hundred and thirty years (Exodus 12:40)."},
{"b":"Exodus","t":2,"s":"The ark of the covenant was placed in the outer court of the tabernacle.","v":false,"why":"It was placed in the most holy place within the vail (Exodus 26:33-34)."},
{"b":"Exodus","t":2,"s":"Aaron was forty days in Mount Sinai with the LORD.","v":false,"why":"Moses went into the midst of the cloud, and was in the mount forty days (Exodus 24:18)."},
{"b":"Exodus","t":3,"s":"Hur and Aaron held up Moses' hands at Rephidim.","v":true,"why":"Aaron and Hur stayed up his hands, the one on the one side, and the other on the other side (Exodus 17:12)."},
{"b":"Exodus","t":3,"s":"Moses' rod became a lion before Pharaoh.","v":false,"why":"Cast it before Pharaoh, and it shall become a serpent (Exodus 7:9)."},
{"b":"Leviticus","t":2,"s":"Nadab and Abihu offered strange fire before the LORD.","v":true,"why":"Nadab and Abihu offered strange fire before the LORD, and there went out fire and devoured them (Leviticus 10:1-2)."},
{"b":"Leviticus","t":2,"s":"The high priest entered the most holy place once every year on the Day of Atonement.","v":true,"why":"Once in the year shall he make atonement upon the horns of it (Leviticus 16:34; Exodus 30:10)."},
{"b":"Leviticus","t":2,"s":"Nadab and Abihu were sons of Moses.","v":false,"why":"Nadab and Abihu were the sons of Aaron the high priest (Leviticus 10:1)."},
{"b":"Leviticus","t":3,"s":"The scapegoat was sent away by the hand of a fit man into the wilderness.","v":true,"why":"He shall let go the goat in the wilderness... into a land not inhabited (Leviticus 16:21-22)."},
{"b":"Leviticus","t":3,"s":"The jubilee year was proclaimed every seventh year.","v":false,"why":"The fiftieth year was the jubilee — not every seventh (Leviticus 25:10-11)."},
{"b":"Numbers","t":1,"s":"The LORD opened the mouth of Balaam's ass.","v":true,"why":"The ass saw the angel, and the LORD opened her mouth to speak (Numbers 22:28)."},
{"b":"Numbers","t":1,"s":"The spies searched the land of Canaan forty days.","v":true,"why":"They returned from searching after forty days, bearing the cluster of Eschol (Numbers 13:25)."},
{"b":"Numbers","t":1,"s":"Israel wandered in the wilderness twenty years.","v":false,"why":"Forty years — a year for each day of searching (Numbers 14:33-34)."},
{"b":"Numbers","t":2,"s":"Aaron's rod budded and brought forth almonds.","v":true,"why":"Behold, the rod of Aaron for the house of Levi was budded... and yielded almonds (Numbers 17:8)."},
{"b":"Numbers","t":2,"s":"Korah and his company were swallowed by the earth.","v":true,"why":"The earth opened her mouth, and swallowed them up, and their houses (Numbers 16:32)."},
{"b":"Numbers","t":2,"s":"Moses sent twenty-four spies into the land of Canaan.","v":false,"why":"Twelve spies were sent — one from each tribe of Israel (Numbers 13:2-4)."},
{"b":"Numbers","t":2,"s":"Balaam blessed Balak and cursed Israel.","v":false,"why":"God turned the curse into a blessing — Balaam could only bless Israel (Numbers 23:11-12)."},
{"b":"Numbers","t":3,"s":"Moses set up a brazen eagle upon a pole.","v":false,"why":"Moses made a serpent of brass, and put it upon a pole (Numbers 21:9)."},
{"b":"Numbers","t":3,"s":"Balaam struck his ass five times before the LORD opened her mouth.","v":false,"why":"Balaam smote her three times (Numbers 22:28)."},
{"b":"Deuteronomy","t":1,"s":"Joshua was full of the spirit of wisdom when Moses laid hands on him.","v":true,"why":"Moses laid his hands upon him, and Israel hearkened unto him (Deuteronomy 34:9)."},
{"b":"Deuteronomy","t":1,"s":"Moses entered the land of Canaan with Israel.","v":false,"why":"Moses died in Moab upon Nebo, and was buried by the LORD — he saw the land, but did not cross (Deuteronomy 34:5)."},
{"b":"Deuteronomy","t":2,"s":"Moses died on Mount Nebo at the age of one hundred and twenty years.","v":true,"why":"Moses was an hundred and twenty years old when he died: his eye was not dim (Deuteronomy 34:7)."},
{"b":"Deuteronomy","t":2,"s":"The blessings of obedience were pronounced from Mount Ebal and curses from Mount Gerizim.","v":false,"why":"Blessings from Mount Gerizim, and curses from Mount Ebal (Deuteronomy 27:12-13)."},
{"b":"Deuteronomy","t":2,"s":"Moses died in the land of Canaan on Mount Carmel.","v":false,"why":"Moses died in Moab upon Mount Nebo (Deuteronomy 34:1, 5)."},
{"b":"Deuteronomy","t":3,"s":"Og king of Bashan had a bedstead of iron.","v":true,"why":"Behold, his bedstead was a bedstead of iron; is it not in Rabbath of the children of Ammon? (Deuteronomy 3:11)."},
{"b":"Deuteronomy","t":3,"s":"Moses' grave in the valley in the land of Moab is known to this day.","v":false,"why":"No man knoweth of his sepulchre unto this day (Deuteronomy 34:6)."},
{"b":"Joshua","t":1,"s":"Rahab hid the two spies upon the roof of her house.","v":true,"why":"She hid them with stalks of flax upon the roof (Joshua 2:4-6)."},
{"b":"Joshua","t":1,"s":"Achan took of the accursed thing at Jericho.","v":true,"why":"Achan took of the accursed thing, and Israel fell before Ai (Joshua 7:1)."},
{"b":"Joshua","t":1,"s":"Jericho's wall fell on the third day of circling.","v":false,"why":"On the seventh day they compassed the city seven times, and the wall fell (Joshua 6:15, 20)."},
{"b":"Joshua","t":1,"s":"Joshua was Moses' father.","v":false,"why":"Joshua was the son of Nun, Moses' minister (Joshua 1:1)."},
{"b":"Joshua","t":2,"s":"The sun stood still upon Gibeon at Joshua's command.","v":true,"why":"Sun, stand thou still upon Gibeon; and thou, Moon, in the valley of Ajalon (Joshua 10:12)."},
{"b":"Joshua","t":2,"s":"Caleb asked Joshua for the mountain of Hebron when he was eighty and five years old.","v":true,"why":"Now therefore give me this mountain... I am this day fourscore and five years old (Joshua 14:10-12)."},
{"b":"Joshua","t":2,"s":"The Gibeonites made peace with Joshua by threatening him with an army.","v":false,"why":"They worked wilily with old sacks, rent bottles, and mouldy bread (Joshua 9:4-6)."},
{"b":"Joshua","t":2,"s":"Joshua set up thirty-six stones in Gilgal.","v":false,"why":"Those twelve stones, which they took out of Jordan, did Joshua pitch in Gilgal (Joshua 4:20)."},
{"b":"Joshua","t":2,"s":"The city of Ai fell on the first attack by three thousand men.","v":false,"why":"Israel fled before the men of Ai because of Achan's sin (Joshua 7:4-5)."},
{"b":"Joshua","t":3,"s":"The stones taken from Jordan were pitched at Shiloh.","v":false,"why":"Those twelve stones, which they took out of Jordan, did Joshua pitch in Gilgal (Joshua 4:20)."},
{"b":"Judges","t":1,"s":"Samson slew a thousand men with the jawbone of an ass.","v":true,"why":"With the jawbone he slew a thousand men, and called the place Ramath-lehi (Judges 15:15-17)."},
{"b":"Judges","t":1,"s":"Deborah was a prophetess and a judge of Israel.","v":true,"why":"Deborah, a prophetess, judged Israel at that time under a palm tree (Judges 4:4-5)."},
{"b":"Judges","t":1,"s":"Gideon went to battle with thirty thousand men.","v":false,"why":"The LORD cut the army to three hundred men with lamps and trumpets (Judges 7:7, 16)."},
{"b":"Judges","t":1,"s":"Delilah cut Samson's hair with her own hands.","v":false,"why":"She called for a man, and caused him to shave off his seven locks (Judges 16:19)."},
{"b":"Judges","t":2,"s":"Jael drove a tent nail into Sisera's temples.","v":true,"why":"Jael took a nail of the tent, and smote the nail into his temples (Judges 4:21)."},
{"b":"Judges","t":2,"s":"Barak went to war against Sisera without Deborah.","v":false,"why":"Barak said unto her, If thou wilt go with me, then I will go (Judges 4:8)."},
{"b":"Judges","t":2,"s":"Samson told Delilah the secret of his strength on her first request.","v":false,"why":"He mocked her three times with green withs, new ropes, and weaving the locks of his head (Judges 16:7-14)."},
{"b":"Judges","t":2,"s":"Gideon was from the tribe of Judah.","v":false,"why":"My family is poor in Manasseh, and I am the least in my father's house (Judges 6:15)."},
{"b":"Judges","t":3,"s":"Ehud was left-handed and slew Eglon king of Moab.","v":true,"why":"The LORD raised them up a deliverer, Ehud... a man lefthanded (Judges 3:15)."},
{"b":"Judges","t":3,"s":"Shamgar slew six hundred Philistines with an ox goad.","v":true,"why":"Shamgar the son of Anath, which slew of the Philistines six hundred men with an ox goad (Judges 3:31)."},
{"b":"Ruth","t":1,"s":"Ruth was Naomi's daughter in law.","v":true,"why":"Ruth the Moabitess clave unto her, and returned with her to Bethlehem (Ruth 1:22)."},
{"b":"Ruth","t":1,"s":"Boaz was Ruth's brother.","v":false,"why":"Boaz took Ruth to wife, and Obed was born of the union (Ruth 4:13)."},
{"b":"Ruth","t":1,"s":"Ruth was a native of Bethlehem.","v":false,"why":"Ruth was a Moabitess — she came to Bethlehem with Naomi (Ruth 1:22)."},
{"b":"Ruth","t":2,"s":"Obed, Ruth's son, was the grandfather of David.","v":true,"why":"Obed begat Jesse, and Jesse begat David (Ruth 4:17)."},
{"b":"Ruth","t":2,"s":"Orpah returned to Moab while Ruth clave to Naomi.","v":true,"why":"Orpah kissed her mother in law; but Ruth clave unto her (Ruth 1:14)."},
{"b":"Ruth","t":2,"s":"Naomi's husband was named Boaz.","v":false,"why":"The name of the man was Elimelech, and the name of his wife Naomi (Ruth 1:2)."},
{"b":"1 Samuel","t":1,"s":"Jonathan was Saul's son.","v":true,"why":"Jonathan, Saul's son, delighted much in David (1 Samuel 19:1-2)."},
{"b":"1 Samuel","t":1,"s":"David told Saul he had slain both a lion and a bear.","v":true,"why":"Thy servant slew both the lion and the bear (1 Samuel 17:36)."},
{"b":"1 Samuel","t":1,"s":"Hannah brought young Samuel to the house of the LORD in Shiloh.","v":true,"why":"Hannah brought him unto the house of the LORD in Shiloh: and the child was young (1 Samuel 1:24)."},
{"b":"1 Samuel","t":1,"s":"David slew Goliath with a sword.","v":false,"why":"David slew him with a sling and a stone — the sword was only used to take off his head (1 Samuel 17:49-51)."},
{"b":"1 Samuel","t":1,"s":"Eli was high priest in Jerusalem.","v":false,"why":"Eli judged Israel and ministered in Shiloh before the temple existed (1 Samuel 1:3)."},
{"b":"1 Samuel","t":2,"s":"The ark of God was taken by the Philistines when Hophni and Phinehas died.","v":true,"why":"The ark of God was taken; and the two sons of Eli, Hophni and Phinehas, were slain (1 Samuel 4:11)."},
{"b":"1 Samuel","t":2,"s":"Goliath was a giant of Ashdod.","v":false,"why":"Goliath of Gath, six cubits and a span (1 Samuel 17:4)."},
{"b":"1 Samuel","t":2,"s":"David was Saul's grandson.","v":false,"why":"David became Saul's son in law, given Michal to wife (1 Samuel 18:27-28)."},
{"b":"1 Samuel","t":2,"s":"Saul was from the tribe of Judah.","v":false,"why":"Saul was the son of Kish, a Benjamite (1 Samuel 9:1-2)."},
{"b":"1 Samuel","t":2,"s":"David was the eldest son of Jesse.","v":false,"why":"David was the youngest of eight sons (1 Samuel 16:10-11)."},
{"b":"1 Samuel","t":2,"s":"Goliath fell backward when the stone struck his forehead.","v":false,"why":"The stone sunk into his forehead; and he fell upon his face to the earth (1 Samuel 17:49)."},
{"b":"1 Samuel","t":2,"s":"Jonathan threw a spear at David to kill him.","v":false,"why":"Saul cast a javelin at David — Jonathan loved David as his own soul (1 Samuel 18:11; 20:17)."},
{"b":"1 Samuel","t":3,"s":"Abigail brought provisions to David when Nabal refused him.","v":true,"why":"Abigail made haste, and took two hundred loaves... and met David (1 Samuel 25:18)."},
{"b":"1 Samuel","t":3,"s":"Dagon the idol fell on his face before the ark of the LORD in Ashdod.","v":true,"why":"Dagon was fallen upon his face to the earth before the ark of the LORD (1 Samuel 5:3)."},
{"b":"2 Samuel","t":1,"s":"David was anointed king over Judah in Hebron.","v":true,"why":"The men of Judah came, and there they anointed David king over the house of Judah (2 Samuel 2:4)."},
{"b":"2 Samuel","t":2,"s":"Absalom's head caught in an oak tree.","v":true,"why":"His head caught hold of the oak, and he was taken up between the heaven and the earth (2 Samuel 18:9)."},
{"b":"2 Samuel","t":2,"s":"Uzzah put forth his hand to the ark of God and died.","v":true,"why":"Uzzah put forth his hand to the ark of God... and God smote him there (2 Samuel 6:6-7)."},
{"b":"2 Samuel","t":2,"s":"Nathan rebuked David with the parable of the ewe lamb.","v":true,"why":"Nathan said to David, Thou art the man (2 Samuel 12:1-7)."},
{"b":"2 Samuel","t":2,"s":"Uriah the Hittite was David's general who commanded the army.","v":false,"why":"Joab was the captain of the host; Uriah was one of the thirty mighty men (2 Samuel 8:16; 23:39)."},
{"b":"2 Samuel","t":3,"s":"Benaiah the son of Jehoiada slew a lion in the midst of a pit in time of snow.","v":true,"why":"He went down also and slew a lion in the midst of a pit in time of snow (2 Samuel 23:20)."},
{"b":"2 Samuel","t":3,"s":"Joab was David's father.","v":false,"why":"Joab was David's nephew, the son of Zeruiah (2 Samuel 2:18)."},
{"b":"1 Kings","t":1,"s":"Solomon asked God for an understanding heart to judge the people.","v":true,"why":"Give therefore thy servant an understanding heart to judge thy people (1 Kings 3:9)."},
{"b":"1 Kings","t":1,"s":"Solomon built the ark of the covenant.","v":false,"why":"Bezaleel made the ark in the wilderness; Solomon built the temple that housed it (Exodus 37:1; 1 Kings 6)."},
{"b":"1 Kings","t":1,"s":"The queen of Sheba came to prove David with hard questions.","v":false,"why":"She came to prove Solomon with hard questions at Jerusalem (1 Kings 10:1)."},
{"b":"1 Kings","t":2,"s":"Solomon's temple was seven years in building.","v":true,"why":"He was seven years in building it (1 Kings 6:38)."},
{"b":"1 Kings","t":2,"s":"Jeroboam set up two calves of gold, one in Bethel and the other in Dan.","v":true,"why":"He set the one in Beth-el, and the other put he in Dan (1 Kings 12:28-29)."},
{"b":"1 Kings","t":2,"s":"Elijah called down fire on Mount Carmel against the prophets of Baal.","v":true,"why":"The fire of the LORD fell, and consumed the burnt sacrifice (1 Kings 18:38)."},
{"b":"1 Kings","t":2,"s":"Elijah confronted four hundred and fifty prophets of Baal on Mount Carmel.","v":true,"why":"The prophets of Baal four hundred and fifty, and the prophets of the groves four hundred (1 Kings 18:19)."},
{"b":"1 Kings","t":2,"s":"Rehoboam listened to the counsel of the old men.","v":false,"why":"He forsook the counsel of the old men and followed the young men (1 Kings 12:8-13)."},
{"b":"1 Kings","t":2,"s":"Jezebel was the daughter of the king of Judah.","v":false,"why":"Jezebel was the daughter of Ethbaal king of the Zidonians (1 Kings 16:31)."},
{"b":"1 Kings","t":3,"s":"The ravens fed Elijah with bread and flesh at the brook Cherith.","v":true,"why":"The ravens brought him bread and flesh in the morning, and bread and flesh in the evening (1 Kings 17:6)."},
{"b":"2 Kings","t":1,"s":"Elijah went up by a whirlwind into heaven.","v":true,"why":"A chariot of fire parted them, and Elijah went up by a whirlwind (2 Kings 2:11)."},
{"b":"2 Kings","t":1,"s":"Naaman the Syrian dipped himself six times in Jordan.","v":false,"why":"He dipped himself seven times, and his flesh came again like a child's (2 Kings 5:14)."},
{"b":"2 Kings","t":2,"s":"Josiah was eight years old when he began to reign.","v":true,"why":"Josiah was eight years old when he began to reign (2 Kings 22:1)."},
{"b":"2 Kings","t":2,"s":"An angel of the LORD slew 185,000 Assyrians in Sennacherib's camp in one night.","v":true,"why":"The angel of the LORD went out, and smote in the camp of the Assyrians an hundred fourscore and five thousand (2 Kings 19:35)."},
{"b":"2 Kings","t":2,"s":"Elisha was taken up in a chariot of fire instead of Elijah.","v":false,"why":"Elijah went up in the whirlwind; Elisha took up his mantle (2 Kings 2:11-13)."},
{"b":"2 Kings","t":2,"s":"Athaliah was a righteous queen who preserved the house of David.","v":false,"why":"She destroyed all the seed royal when her son Ahaziah died (2 Kings 11:1)."},
{"b":"2 Kings","t":3,"s":"Gehazi was smitten with the leprosy of Naaman for his greed.","v":true,"why":"The leprosy therefore of Naaman shall cleave unto thee... and he went out a leper as white as snow (2 Kings 5:27)."},
{"b":"1 Chronicles","t":2,"s":"Jabez prayed that God would enlarge his coast and keep him from evil.","v":true,"why":"Jabez called on the God of Israel, saying, Oh that thou wouldest bless me indeed (1 Chronicles 4:10)."},
{"b":"1 Chronicles","t":3,"s":"David was not permitted to build the temple because he had shed much blood upon the earth.","v":true,"why":"Thou shalt not build an house unto my name, because thou hast shed much blood upon the earth (1 Chronicles 22:8)."},
{"b":"2 Chronicles","t":2,"s":"Jehoshaphat sent singers before the army to praise the beauty of holiness.","v":true,"why":"He appointed singers unto the LORD... that should praise the beauty of holiness (2 Chronicles 20:21)."},
{"b":"2 Chronicles","t":3,"s":"King Uzziah was struck with leprosy when he went into the temple to burn incense.","v":true,"why":"While he was wroth with the priests, the leprosy even rose up in his forehead (2 Chronicles 26:19)."},
{"b":"Ezra","t":2,"s":"Cyrus king of Persia made a decree to rebuild the house of God in Jerusalem.","v":true,"why":"Cyrus king of Persia made a proclamation... to build him an house at Jerusalem (Ezra 1:1-3)."},
{"b":"Ezra","t":2,"s":"Ezra was a ready scribe in the law of Moses.","v":true,"why":"This Ezra went up from Babylon; and he was a ready scribe in the law of Moses (Ezra 7:6)."},
{"b":"Ezra","t":3,"s":"Tattenai the governor tried to hinder the rebuilding of the temple in Jerusalem.","v":true,"why":"Tattenai, governor on this side the river, and Shethar-boznai... came unto them, and said thus unto them, Who hath commanded you to build? (Ezra 5:3)."},
{"b":"Nehemiah","t":1,"s":"Nehemiah was the king's cupbearer.","v":true,"why":"I was the king's cupbearer (Nehemiah 1:11)."},
{"b":"Nehemiah","t":1,"s":"The wall of Jerusalem was finished in fifty and two days.","v":true,"why":"So the wall was finished... in fifty and two days, notwithstanding the enemies' plots (Nehemiah 6:15)."},
{"b":"Nehemiah","t":2,"s":"Sanballat and Tobiah helped Nehemiah rebuild the wall.","v":false,"why":"Sanballat and Tobiah mocked and conspired to fight against Jerusalem (Nehemiah 4:1-8)."},
{"b":"Nehemiah","t":3,"s":"Ezra read the law from a pulpit of wood from morning until midday.","v":true,"why":"Ezra the scribe stood upon a pulpit of wood... and read therein from the morning until midday (Nehemiah 8:3-4)."},
{"b":"Esther","t":1,"s":"Mordecai sat in the king's gate.","v":true,"why":"Mordecai sat in the king's gate, and discovered the plot of Bigthan and Teresh (Esther 2:19-21)."},
{"b":"Esther","t":1,"s":"Esther was king Ahasuerus's daughter.","v":false,"why":"Ahasuerus made Esther queen in Vashti's place — his wife, not his daughter (Esther 2:17)."},
{"b":"Esther","t":1,"s":"Haman was Esther's cousin.","v":false,"why":"Mordecai was her cousin — Haman was the Agagite who sought to destroy her people (Esther 2:7; 3:1)."},
{"b":"Esther","t":1,"s":"Vashti obeyed the king's commandment to come before his princes.","v":false,"why":"Queen Vashti refused to come at the king's commandment (Esther 1:12)."},
{"b":"Esther","t":2,"s":"Haman was hanged on the gallows he prepared for Mordecai.","v":true,"why":"So they hanged Haman on the gallows that he had prepared for Mordecai (Esther 7:10)."},
{"b":"Esther","t":3,"s":"The feast of Purim was instituted to commemorate the Jews' deliverance in Persia.","v":true,"why":"They called these days Purim after the name of Pur (Esther 9:26-28)."},
{"b":"Job","t":1,"s":"Job's friends sat with him seven days and seven nights without speaking.","v":true,"why":"They sat down with him upon the ground seven days and seven nights, and none spake a word (Job 2:13)."},
{"b":"Job","t":1,"s":"Job cursed God to his face.","v":false,"why":"In all this Job sinned not, nor charged God foolishly (Job 1:22)."},
{"b":"Job","t":2,"s":"The LORD spoke to Job out of the whirlwind.","v":true,"why":"Then the LORD answered Job out of the whirlwind, and said (Job 38:1)."},
{"b":"Job","t":2,"s":"Elihu was the oldest of Job's four visitors.","v":false,"why":"Elihu was young, and they were very old; wherefore he waited to speak (Job 32:4-6)."},
{"b":"Psalms","t":1,"s":"Psalm 23 begins 'The LORD is my shepherd'.","v":true,"why":"The LORD is my shepherd; I shall not want (Psalm 23:1)."},
{"b":"Psalms","t":1,"s":"Psalm 1 blesses the man who walks in the counsel of the ungodly.","v":false,"why":"Blessed is the man that walketh NOT in the counsel of the ungodly (Psalm 1:1)."},
{"b":"Psalms","t":1,"s":"Psalm 119 is the shortest chapter in the Bible.","v":false,"why":"Psalm 119 is the longest chapter in the Bible; Psalm 117 is the shortest (Psalm 117; Psalm 119)."},
{"b":"Psalms","t":1,"s":"David wrote every single psalm in the book of Psalms.","v":false,"why":"Psalms are authored by David, Asaph, the sons of Korah, Moses, and Solomon (Psalm 90:title; 72:20)."},
{"b":"Psalms","t":2,"s":"Psalm 90 is titled a prayer of Moses the man of God.","v":true,"why":"A Prayer of Moses the man of God — Lord, thou hast been our dwelling place (Psalm 90:1)."},
{"b":"Psalms","t":3,"s":"Asaph is named in the title of twelve psalms.","v":true,"why":"Psalm 50 and Psalms 73 through 83 bear the name of Asaph in their titles (Psalm 50:title; 73:title)."},
{"b":"Proverbs","t":1,"s":"The fear of the LORD is the beginning of knowledge.","v":true,"why":"The fear of the LORD is the beginning of knowledge (Proverbs 1:7)."},
{"b":"Proverbs","t":1,"s":"Proverbs teaches that a soft answer stirreth up wrath.","v":false,"why":"A soft answer turneth away wrath; grievous words stir up anger (Proverbs 15:1)."},
{"b":"Proverbs","t":2,"s":"Proverbs 31 describes the virtuous woman.","v":true,"why":"Who can find a virtuous woman? for her price is far above rubies (Proverbs 31:10)."},
{"b":"Ecclesiastes","t":1,"s":"Ecclesiastes opens with 'vanity of vanities... all is vanity'.","v":true,"why":"Vanity of vanities, saith the Preacher, vanity of vanities; all is vanity (Ecclesiastes 1:2)."},
{"b":"Ecclesiastes","t":2,"s":"Ecclesiastes declares that a threefold cord is quickly broken.","v":false,"why":"A threefold cord is not quickly broken (Ecclesiastes 4:12)."},
{"b":"Song of Solomon","t":2,"s":"The Song of Solomon describes love as strong as death.","v":true,"why":"For love is strong as death; jealousy is cruel as the grave (Song of Solomon 8:6)."},
{"b":"Song of Solomon","t":3,"s":"The Rose of Sharon is mentioned in the Song of Solomon.","v":true,"why":"I am the rose of Sharon, and the lily of the valleys (Song of Solomon 2:1)."},
{"b":"Isaiah","t":1,"s":"Isaiah saw the Lord on a throne in the year king Uzziah died.","v":true,"why":"In the year that king Uzziah died I saw also the Lord sitting upon a throne (Isaiah 6:1)."},
{"b":"Isaiah","t":1,"s":"Isaiah prophesied that a virgin shall conceive and bear a son named Immanuel.","v":true,"why":"Behold, a virgin shall conceive, and bear a son, and shall call his name Immanuel (Isaiah 7:14)."},
{"b":"Isaiah","t":1,"s":"Isaiah was three days and three nights in the fish's belly.","v":false,"why":"That was Jonah — Isaiah saw the Lord on His throne instead (Jonah 1:17; Isaiah 6:1)."},
{"b":"Isaiah","t":2,"s":"A seraphim touched Isaiah's lips with a live coal from the altar.","v":true,"why":"Then flew one of the seraphims unto me, having a live coal in his hand (Isaiah 6:6-7)."},
{"b":"Isaiah","t":2,"s":"Isaiah chapter 53 describes the Suffering Servant wounded for our transgressions.","v":true,"why":"He was wounded for our transgressions, he was bruised for our iniquities (Isaiah 53:5)."},
{"b":"Isaiah","t":3,"s":"Cyrus is named by Isaiah more than a century before his birth.","v":true,"why":"That saith of Cyrus, He is my shepherd, and shall perform all my pleasure (Isaiah 44:28; 45:1)."},
{"b":"Jeremiah","t":1,"s":"Jeremiah was cast into a dungeon.","v":true,"why":"They let him down with cords into the dungeon of Malchiah — he sank in the mire (Jeremiah 38:6)."},
{"b":"Jeremiah","t":1,"s":"Jeremiah was carried to Babylon with the captives.","v":false,"why":"Jeremiah was left in the land with the poor, and later taken into Egypt (Jeremiah 39:11-12; 43:5-7)."},
{"b":"Jeremiah","t":2,"s":"Baruch was Jeremiah's scribe who wrote the words of the LORD from his mouth.","v":true,"why":"Jeremiah called Baruch the son of Neriah: and Baruch wrote from the mouth of Jeremiah (Jeremiah 36:4)."},
{"b":"Jeremiah","t":2,"s":"King Jehoiakim cut Jeremiah's scroll with a penknife and burned it.","v":true,"why":"He cut it with the penknife, and cast it into the fire that was on the hearth (Jeremiah 36:23)."},
{"b":"Jeremiah","t":3,"s":"Ebed-melech the Ethiopian drew Jeremiah out of the mire of the dungeon with rotten rags.","v":true,"why":"Ebed-melech... took old cast clouts and old rotten rags, and let them down by cords... into the dungeon (Jeremiah 38:11-13)."},
{"b":"Lamentations","t":2,"s":"Lamentations proclaims that the LORD's compassions fail not and are new every morning.","v":true,"why":"His compassions fail not. They are new every morning: great is thy faithfulness (Lamentations 3:22-23)."},
{"b":"Lamentations","t":3,"s":"Lamentations is composed of five distinct poems matching its five chapters.","v":true,"why":"Each chapter is an independent lamentation poem in the Hebrew text (Lamentations 1-5)."},
{"b":"Ezekiel","t":1,"s":"Ezekiel prophesied to a valley of dry bones.","v":true,"why":"Prophesy upon these bones, and say unto them, O ye dry bones (Ezekiel 37:4)."},
{"b":"Ezekiel","t":2,"s":"Ezekiel was among the captives by the river of Chebar.","v":true,"why":"As I was among the captives by the river of Chebar, the heavens were opened (Ezekiel 1:1)."},
{"b":"Ezekiel","t":2,"s":"Ezekiel was commanded to eat a scroll sweet as honey.","v":true,"why":"Then did I eat it; and it was in my mouth as honey for sweetness (Ezekiel 3:3)."},
{"b":"Ezekiel","t":3,"s":"Ezekiel was commanded to lie upon his left side three hundred and ninety days.","v":true,"why":"Lie thou also upon thy left side... three hundred and ninety days (Ezekiel 4:4-5)."},
{"b":"Daniel","t":1,"s":"Daniel interpreted the handwriting on the wall.","v":true,"why":"MENE, MENE, TEKEL, UPHARSIN — this is the interpretation of the thing (Daniel 5:25-28)."},
{"b":"Daniel","t":1,"s":"Daniel's three friends came out of the fire without even the smell of flame.","v":true,"why":"Neither were their coats changed, nor had the smell of fire passed on them (Daniel 3:27)."},
{"b":"Daniel","t":1,"s":"Daniel was cast into the fiery furnace.","v":false,"why":"Daniel's three friends were cast into the furnace — Daniel was elsewhere (Daniel 3:21-26)."},
{"b":"Daniel","t":1,"s":"Shadrach, Meshach, and Abed-nego bowed down to the golden image.","v":false,"why":"They answered: we will not serve thy gods, nor worship the golden image (Daniel 3:18)."},
{"b":"Daniel","t":1,"s":"Daniel prayed toward Babylon three times a day.","v":false,"why":"His windows being open in his chamber toward Jerusalem, he kneeled three times a day (Daniel 6:10)."},
{"b":"Daniel","t":1,"s":"Daniel's three friends were renamed Belteshazzar, Shadrach, and Meshach.","v":false,"why":"Daniel was renamed Belteshazzar; his friends were Shadrach, Meshach, and Abednego (Daniel 1:7)."},
{"b":"Daniel","t":2,"s":"King Nebuchadnezzar ate grass as oxen for seven times.","v":true,"why":"He was driven from men, and did eat grass as oxen, and his body was wet with the dew of heaven (Daniel 4:33)."},
{"b":"Daniel","t":3,"s":"Belshazzar saw the fingers of a man's hand write upon the plaster of the wall.","v":true,"why":"In the same hour came forth fingers of a man's hand, and wrote over against the candlestick (Daniel 5:5)."},
{"b":"Hosea","t":2,"s":"Hosea took Gomer the daughter of Diblaim for a wife.","v":true,"why":"So he went and took Gomer the daughter of Diblaim (Hosea 1:3)."},
{"b":"Hosea","t":3,"s":"Hosea bought back his wife for fifteen pieces of silver and an homer and an half of barley.","v":true,"why":"So I bought her to me for fifteen pieces of silver, and for an homer of barley, and an half homer of barley (Hosea 3:2)."},
{"b":"Joel","t":2,"s":"Joel prophesied that the LORD would pour out His Spirit upon all flesh.","v":true,"why":"I will pour out my spirit upon all flesh; and your sons and your daughters shall prophesy (Joel 2:28)."},
{"b":"Joel","t":3,"s":"Joel mentions four kinds of locusts: palmerworm, locust, cankerworm, and caterpiller.","v":true,"why":"That which the palmerworm hath left hath the locust eaten; and that which the locust hath left hath the cankerworm eaten (Joel 1:4)."},
{"b":"Amos","t":2,"s":"Amos saw a vision of the Lord standing upon a wall with a plumbline.","v":true,"why":"The Lord stood upon a wall made by a plumbline, with a plumbline in his hand (Amos 7:7)."},
{"b":"Amos","t":2,"s":"Amos was a priest of Bethel.","v":false,"why":"I was no prophet, but an herdman of Tekoa (Amos 7:14)."},
{"b":"Obadiah","t":3,"s":"Obadiah prophesied against the nation of Edom for violence against Jacob.","v":true,"why":"For thy violence against thy brother Jacob shame shall cover thee (Obadiah 1:10)."},
{"b":"Jonah","t":1,"s":"A great fish swallowed Jonah.","v":true,"why":"The LORD had prepared a great fish to swallow up Jonah (Jonah 1:17)."},
{"b":"Jonah","t":1,"s":"God sent Jonah to preach to Tarshish.","v":false,"why":"Arise, go to Nineveh — Tarshish was the port he fled to (Jonah 1:2-3)."},
{"b":"Jonah","t":1,"s":"Jonah was joyful when Nineveh repented and was spared.","v":false,"why":"It displeased Jonah exceedingly, and he was very angry (Jonah 4:1)."},
{"b":"Jonah","t":2,"s":"The men of Nineveh repented in sackcloth and ashes at Jonah's preaching.","v":true,"why":"The people of Nineveh believed God, and proclaimed a fast, and put on sackcloth (Jonah 3:5)."},
{"b":"Micah","t":1,"s":"Micah foretold a ruler coming out of Bethlehem.","v":true,"why":"But thou, Bethlehem Ephratah — out of thee shall he come forth unto me that is to be ruler in Israel (Micah 5:2)."},
{"b":"Micah","t":2,"s":"Micah wrote that the LORD requires man to do justly, love mercy, and walk humbly.","v":true,"why":"What doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly? (Micah 6:8)."},
{"b":"Nahum","t":3,"s":"Nahum prophesied the total destruction of Nineveh.","v":true,"why":"The burden of Nineveh... She is empty, and void, and waste (Nahum 1:1; 2:10)."},
{"b":"Habakkuk","t":2,"s":"Habakkuk wrote 'the just shall live by his faith'.","v":true,"why":"Behold, his soul which is lifted up is not upright in him: but the just shall live by his faith (Habakkuk 2:4)."},
{"b":"Habakkuk","t":3,"s":"Habakkuk stood upon his watchtower to hear what God would speak.","v":true,"why":"I will stand upon my watch, and set me upon the tower, and will watch to see what he will say (Habakkuk 2:1)."},
{"b":"Zephaniah","t":3,"s":"Zephaniah prophesied that the LORD God in the midst of Zion will rejoice over her with joy.","v":true,"why":"The LORD thy God in the midst of thee is mighty; he will save, he will rejoice over thee with joy (Zephaniah 3:17)."},
{"b":"Haggai","t":3,"s":"Haggai proclaimed that the glory of the latter house shall be greater than of the former.","v":true,"why":"The glory of this latter house shall be greater than of the former, saith the LORD of hosts (Haggai 2:9)."},
{"b":"Zechariah","t":2,"s":"Zechariah foretold the king coming to Jerusalem riding upon an ass.","v":true,"why":"Rejoice greatly, O daughter of Zion... thy King cometh unto thee: he is just, and having salvation; lowly, and riding upon an ass (Zechariah 9:9)."},
{"b":"Malachi","t":2,"s":"Malachi prophesied that Elijah the prophet would be sent before the great and dreadful day of the LORD.","v":true,"why":"Behold, I will send you Elijah the prophet before the coming of the great and dreadful day of the LORD (Malachi 4:5)."},
{"b":"Malachi","t":2,"s":"Malachi challenged Israel concerning robbing God in tithes and offerings.","v":true,"why":"Will a man rob God? Yet ye have robbed me. But ye say, Wherein have we robbed thee? In tithes and offerings (Malachi 3:8)."},
{"b":"Matthew","t":1,"s":"John the Baptist did eat locusts and wild honey.","v":true,"why":"His meat was locusts and wild honey (Matthew 3:4)."},
{"b":"Matthew","t":1,"s":"Andrew was Peter's brother.","v":true,"why":"The first... Andrew, and Peter his brother (Matthew 10:2)."},
{"b":"Matthew","t":1,"s":"Jesus fed five thousand with five loaves and two fishes.","v":true,"why":"Five loaves and two fishes fed five thousand men, beside women and children (Matthew 14:19-21)."},
{"b":"Matthew","t":1,"s":"The wise men offered gold, frankincense, and myrrh.","v":true,"why":"They presented unto him gifts; gold, and frankincense, and myrrh (Matthew 2:11)."},
{"b":"Matthew","t":1,"s":"Peter walked on the water to go to Jesus.","v":true,"why":"And when Peter was come down out of the ship, he walked on the water (Matthew 14:29)."},
{"b":"Matthew","t":1,"s":"Peter betrayed Jesus for thirty pieces of silver.","v":false,"why":"Judas asked the chief priests for thirty pieces of silver (Matthew 26:14-15)."},
{"b":"Matthew","t":1,"s":"Jesus fasted in the wilderness thirty days and thirty nights.","v":false,"why":"He fasted forty days and forty nights (Matthew 4:2)."},
{"b":"Matthew","t":1,"s":"John the Baptist was Andrew's brother.","v":false,"why":"Andrew was Peter's brother (Matthew 10:2)."},
{"b":"Matthew","t":1,"s":"The Sermon on the Mount was delivered in the synagogue.","v":false,"why":"He went up into a mountain — and when he was set, he taught them (Matthew 5:1-2)."},
{"b":"Matthew","t":1,"s":"Herod was glad when the wise men told him of the King of the Jews.","v":false,"why":"When Herod the king had heard these things, he was troubled (Matthew 2:3)."},
{"b":"Matthew","t":1,"s":"Pilate found Jesus guilty of treason against Rome.","v":false,"why":"Pilate said: I find no fault in this man (Luke 23:4; Matthew 27:24)."},
{"b":"Matthew","t":1,"s":"An ox and a donkey are mentioned beside the manger at Jesus's birth.","v":false,"why":"No animals are mentioned in the gospel accounts of the nativity (Luke 2:7, 16; Matthew 2:1-11)."},
{"b":"Matthew","t":2,"s":"Jesus fed the four thousand with five loaves.","v":false,"why":"The four thousand were fed with seven loaves and a few little fishes (Matthew 15:34-38)."},
{"b":"Matthew","t":2,"s":"The gospel of Matthew names three wise men.","v":false,"why":"Their number is never given — only their three gifts are named (Matthew 2:1, 11)."},
{"b":"Matthew","t":2,"s":"Barabbas was a prophet of Galilee.","v":false,"why":"Barabbas was a notable prisoner and robber (Matthew 27:16; John 18:40)."},
{"b":"Matthew","t":2,"s":"Peter denied Jesus four times before the cock crew.","v":false,"why":"Verily I say unto thee, That this night, before the cock crow, thou shalt deny me thrice (Matthew 26:34, 75)."},
{"b":"Matthew","t":2,"s":"Jesus chose ten apostles to preach the kingdom.","v":false,"why":"He called unto him his twelve disciples (Matthew 10:1)."},
{"b":"Matthew","t":2,"s":"The star stood directly over the stable in Bethlehem.","v":false,"why":"The star stood over where the young child was in a house (Matthew 2:11)."},
{"b":"Matthew","t":3,"s":"Judas cast down the thirty pieces of silver in the temple and hanged himself.","v":true,"why":"He cast down the pieces of silver in the temple, and departed, and went and hanged himself (Matthew 27:5)."},
{"b":"Mark","t":1,"s":"Jesus stilled the storm with the words 'Peace, be still'.","v":true,"why":"And he arose, and rebuked the wind, and said unto the sea, Peace, be still (Mark 4:39)."},
{"b":"Mark","t":1,"s":"Mark was one of the twelve apostles.","v":false,"why":"He is not in the twelve — the lists name no Mark (Matthew 10:2-4)."},
{"b":"Mark","t":2,"s":"Bartimaeus was a blind man healed at Jericho.","v":true,"why":"Blind Bartimaeus sat by the highway side begging, and received his sight (Mark 10:46-52)."},
{"b":"Mark","t":2,"s":"The man possessed with a legion of demons lived in the tombs.","v":true,"why":"A man with an unclean spirit, who had his dwelling among the tombs (Mark 5:2-3)."},
{"b":"Mark","t":3,"s":"Jesus said to the daughter of Jairus, 'Talitha cumi'.","v":true,"why":"He took the damsel by the hand, and said unto her, Talitha cumi; which is, being interpreted, Damsel, I say unto thee, arise (Mark 5:41)."},
{"b":"Mark","t":3,"s":"Mark's gospel begins with the genealogy of Jesus from Abraham.","v":false,"why":"The beginning of the gospel of Jesus Christ, the Son of God — Matthew begins with the genealogy (Mark 1:1; Matthew 1:1)."},
{"b":"Luke","t":1,"s":"The shepherds came with haste to the manger.","v":true,"why":"They came with haste, and found Mary and Joseph, and the babe lying in a manger (Luke 2:16)."},
{"b":"Luke","t":1,"s":"Zacchaeus climbed up into a sycomore tree to see Jesus.","v":true,"why":"He ran before, and climbed up into a sycomore tree to see him (Luke 19:4)."},
{"b":"Luke","t":1,"s":"The prodigal son made himself a keeper of swine.","v":true,"why":"He sent him into his fields to feed swine, and he would fain have filled his belly with husks (Luke 15:15-16)."},
{"b":"Luke","t":1,"s":"Gabriel announced the birth of John to Zacharias in the temple.","v":true,"why":"I am Gabriel, that stand in the presence of God — thy wife Elisabeth shall bear thee a son (Luke 1:19-20)."},
{"b":"Luke","t":1,"s":"Luke's gospel is addressed to a man named Theophilus.","v":true,"why":"It seemed good to me also... most excellent Theophilus (Luke 1:3)."},
{"b":"Luke","t":1,"s":"Jesus was born in Nazareth.","v":false,"why":"He was born in Bethlehem of Judaea, the city of David (Luke 2:4-7)."},
{"b":"Luke","t":1,"s":"Zacharias doubted the angel and was struck blind.","v":false,"why":"He was struck dumb, and not able to speak, until the day John was named (Luke 1:20, 64)."},
{"b":"Luke","t":1,"s":"The innkeeper in Bethlehem told Joseph there was no room in the inn.","v":false,"why":"The gospel says only 'there was no room for them in the inn' — an innkeeper is never mentioned (Luke 2:7)."},
{"b":"Luke","t":2,"s":"Simeon took the infant Jesus in his arms in the temple.","v":true,"why":"Then took he him up in his arms, and blessed God (Luke 2:28)."},
{"b":"Luke","t":2,"s":"Jesus was twelve years old when he tarried behind in Jerusalem at the temple.","v":true,"why":"When he was twelve years old... the child Jesus tarried behind in Jerusalem (Luke 2:42-43)."},
{"b":"Luke","t":2,"s":"The good Samaritan poured in wine and vinegar into the wounded man's wounds.","v":false,"why":"Bound up his wounds, pouring in oil and wine (Luke 10:34)."},
{"b":"Luke","t":2,"s":"The elder brother rejoiced with music and dancing when the prodigal returned.","v":false,"why":"He was angry, and would not go in (Luke 15:28)."},
{"b":"Luke","t":3,"s":"Two disciples walked with the risen Jesus on the road to Emmaus.","v":true,"why":"Two of them went that same day to a village called Emmaus (Luke 24:13-15)."},
{"b":"John","t":1,"s":"Nicodemus came to Jesus by night.","v":true,"why":"The same came to Jesus by night, and said unto him, Rabbi (John 3:2)."},
{"b":"John","t":1,"s":"Mary Magdalene was the first to see the risen Jesus.","v":true,"why":"Jesus saith unto her, Mary — she turned and said Rabboni (John 20:16)."},
{"b":"John","t":1,"s":"Three crosses are described on Golgotha with Jesus in the midst.","v":true,"why":"They crucified him, and two other with him, on either side one, and Jesus in the midst (John 19:18)."},
{"b":"John","t":1,"s":"John's gospel begins 'In the beginning was the Word'.","v":true,"why":"In the beginning was the Word, and the Word was with God (John 1:1)."},
{"b":"John","t":1,"s":"Jesus turned water into blood at the marriage in Cana.","v":false,"why":"He turned water into wine — the first of his miracles (John 2:9, 11)."},
{"b":"John","t":1,"s":"Lazarus had lain in the grave five days when Jesus called him.","v":false,"why":"By this time he stinketh: for he hath been dead four days (John 11:39)."},
{"b":"John","t":1,"s":"Mary Magdalene was one of the twelve apostles.","v":false,"why":"She is never numbered among the twelve — she followed and ministered to them (Luke 8:1-3)."},
{"b":"John","t":1,"s":"Caiaphas was the Roman governor of Judaea.","v":false,"why":"Pontius Pilate was governor; Caiaphas was the high priest (Matthew 27:2; John 18:13-14)."},
{"b":"John","t":1,"s":"Jesus had children.","v":false,"why":"The scriptures never attribute children to Jesus — nothing in any gospel or epistle says so."},
{"b":"John","t":2,"s":"Thomas was called Didymus.","v":true,"why":"Thomas, which is called Didymus (John 11:16)."},
{"b":"John","t":2,"s":"Jesus talked with a Samaritan woman at Jacob's well.","v":true,"why":"There cometh a woman of Samaria to draw water: Jesus saith unto her, Give me to drink (John 4:7)."},
{"b":"John","t":3,"s":"Nathanael was sitting under a pomegranate tree when Philip called him.","v":false,"why":"Before that Philip called thee, when thou wast under the fig tree, I saw thee (John 1:48)."},
{"b":"Acts","t":1,"s":"Paul was one of the twelve apostles.","v":false,"why":"Matthias was chosen to fill Judas' bishoprick — Paul was called later (Acts 1:26; 9:15)."},
{"b":"Acts","t":1,"s":"Stephen wrote the book of Acts.","v":false,"why":"Acts opens as a continuation of Luke's gospel to Theophilus — Luke wrote both (Acts 1:1; Luke 1:3-4)."},
{"b":"Acts","t":1,"s":"Paul was born in Jerusalem.","v":false,"why":"I am a man which am a Jew of Tarsus — brought up in Jerusalem (Acts 22:3)."},
{"b":"Acts","t":1,"s":"Paul was thrown from a horse on the road to Damascus.","v":false,"why":"He fell to the earth, but scripture never mentions a horse or mount (Acts 9:4)."},
{"b":"Acts","t":1,"s":"Pentecost fell upon the disciples in Galilee.","v":false,"why":"They were all with one accord in one place at Jerusalem (Acts 2:1, 14)."},
{"b":"Acts","t":2,"s":"The believers were called Christians first in Rome.","v":false,"why":"The disciples were called Christians first in Antioch (Acts 11:26)."},
{"b":"Acts","t":2,"s":"About three hundred souls were added to the church on the day of Pentecost.","v":false,"why":"There were added unto them that day about three thousand souls (Acts 2:41)."},
{"b":"Romans","t":1,"s":"Romans was addressed to the church at Corinth.","v":false,"why":"To all that be at Rome — beloved of God, called to be saints (Romans 1:7)."},
{"b":"1 Corinthians","t":1,"s":"The phrase 'God helps those who help themselves' is found in the epistles of Paul.","v":false,"why":"This is a secular proverb from antiquity, not found in the scriptures."},
{"b":"1 Corinthians","t":3,"s":"Paul says he was baptized by Peter in Corinth.","v":false,"why":"I thank God that I baptized none of you, but Crispus and Gaius (1 Corinthians 1:14)."},
{"b":"Galatians","t":2,"s":"Galatians teaches that a man is justified by the works of the law.","v":false,"why":"Knowing that a man is not justified by the works of the law, but by the faith of Jesus Christ (Galatians 2:16)."},
{"b":"Ephesians","t":1,"s":"Ephesians teaches that salvation is earned by works.","v":false,"why":"For by grace are ye saved through faith... not of works, lest any man should boast (Ephesians 2:8-9)."},
{"b":"Philippians","t":2,"s":"Paul wrote Philippians from a palace in Babylon.","v":false,"why":"Paul wrote from his bonds in prison in Rome (Philippians 1:13)."},
{"b":"1 Timothy","t":2,"s":"Paul wrote that money itself is the root of all evil.","v":false,"why":"The LOVE of money is the root — not money itself (1 Timothy 6:10)."},
{"b":"Hebrews","t":1,"s":"The epistle to the Hebrews names Paul as its author in the opening verse.","v":false,"why":"Hebrews opens with God speaking by his Son — no human author is named (Hebrews 1:1-2)."},
{"b":"Revelation","t":1,"s":"The Revelation was given to Peter.","v":false,"why":"The Revelation of Jesus Christ... unto his servant John (Revelation 1:1)."},
{"b":"Revelation","t":1,"s":"The number of the beast is six hundred sixteen.","v":false,"why":"It is six hundred threescore and six — 666 (Revelation 13:18)."},
{"b":"Revelation","t":2,"s":"The seven seals of Revelation are opened by the archangel Michael.","v":false,"why":"The Lion of the tribe of Juda, the Lamb, opened the seals (Revelation 5:5; 6:1)."}
];

if (typeof module !== "undefined" && module.exports){
  module.exports = { TF_CLAIMS };
}
