/* GENERATED by scripts/build-nkjv.js from the licensed NKJV text in
   content/nkjv/source/. Do not edit by hand — rerun the generator.
   Valley questions and cinema captions */
const NKJV_BEAT = {
  "questions": [],
  "cinemaA": [],
  "cinemaB": []
};
if(typeof module !== "undefined") module.exports = { NKJV_BEAT };
