/* GENERATED by scripts/build-nkjv.js from the licensed NKJV text in
   content/nkjv/source/. Do not edit by hand — rerun the generator.
   the multi-blank passages */
const NKJV_PASSAGES = [
  {
    "b": "Psalms",
    "r": "Psalm 23:1-2",
    "t": 2,
    "parts": [
      "The LORD is my ",
      {
        "a": "shepherd",
        "d": [
          "keeper",
          "guardian",
          "strong tower"
        ]
      },
      "; I shall not ",
      {
        "a": "want",
        "d": [
          "fear",
          "fall",
          "stray"
        ]
      },
      ". He makes me to lie down in green pastures; He leads me beside the ",
      {
        "a": "still waters",
        "d": [
          "quiet waters",
          "living waters",
          "waters of rest"
        ]
      },
      "."
    ],
    "id": "P~psalm-23-1-2",
    "blanks": [
      {
        "a": "shepherd",
        "d": [
          "keeper",
          "guardian",
          "strong tower"
        ]
      },
      {
        "a": "want",
        "d": [
          "fear",
          "fall",
          "stray"
        ]
      },
      {
        "a": "still waters",
        "d": [
          "quiet waters",
          "living waters",
          "waters of rest"
        ]
      }
    ]
  },
  {
    "b": "John",
    "r": "John 3:16",
    "t": 1,
    "parts": [
      "For God so loved the world that He gave His ",
      {
        "a": "only begotten Son",
        "d": [
          "well beloved Son",
          "holy anointed Son",
          "first begotten Son"
        ]
      },
      ", that whoever believes in Him should not ",
      {
        "a": "perish",
        "d": [
          "fade",
          "fail",
          "die"
        ]
      },
      " but have ",
      {
        "a": "everlasting life",
        "d": [
          "eternal glory",
          "life eternal",
          "life everlasting"
        ]
      },
      "."
    ],
    "id": "P~john-3-16",
    "blanks": [
      {
        "a": "only begotten Son",
        "d": [
          "well beloved Son",
          "holy anointed Son",
          "first begotten Son"
        ]
      },
      {
        "a": "perish",
        "d": [
          "fade",
          "fail",
          "die"
        ]
      },
      {
        "a": "everlasting life",
        "d": [
          "eternal glory",
          "life eternal",
          "life everlasting"
        ]
      }
    ]
  },
  {
    "b": "Genesis",
    "r": "Genesis 1:1-2",
    "t": 2,
    "parts": [
      "In the beginning God created the ",
      {
        "a": "heavens and the earth",
        "d": [
          "earth and the heavens",
          "heavens and the land",
          "world and the sea"
        ]
      },
      ". The earth was ",
      {
        "a": "without form, and void",
        "d": [
          "without shape, and void",
          "formless, and empty",
          "without form, and dark"
        ]
      },
      "; and darkness was on the face of the deep. And the Spirit of God was hovering over the ",
      {
        "a": "face of the waters",
        "d": [
          "waters of the deep",
          "surface of the sea",
          "face of the flood"
        ],
        "qaOk": [
          "recycled"
        ]
      },
      "."
    ],
    "id": "P~genesis-1-1-2",
    "blanks": [
      {
        "a": "heavens and the earth",
        "d": [
          "earth and the heavens",
          "heavens and the land",
          "world and the sea"
        ]
      },
      {
        "a": "without form, and void",
        "d": [
          "without shape, and void",
          "formless, and empty",
          "without form, and dark"
        ]
      },
      {
        "a": "face of the waters",
        "d": [
          "waters of the deep",
          "surface of the sea",
          "face of the flood"
        ],
        "qaOk": [
          "recycled"
        ]
      }
    ]
  },
  {
    "b": "Psalms",
    "r": "Psalm 1:1",
    "t": 3,
    "parts": [
      "Blessed is the man Who walks not in the ",
      {
        "a": "counsel of the ungodly",
        "d": [
          "council of the ungodly",
          "counsel of the wicked",
          "way of the ungodly"
        ]
      },
      ", Nor stands in the ",
      {
        "a": "path of sinners",
        "d": [
          "seat of sinners",
          "way of the wicked",
          "path of the scornful"
        ]
      },
      ", Nor sits in the ",
      {
        "a": "seat of the scornful",
        "d": [
          "seat of the scoffers",
          "place of the scornful",
          "chair of the scornful"
        ]
      },
      ";"
    ],
    "id": "P~psalm-1-1",
    "blanks": [
      {
        "a": "counsel of the ungodly",
        "d": [
          "council of the ungodly",
          "counsel of the wicked",
          "way of the ungodly"
        ]
      },
      {
        "a": "path of sinners",
        "d": [
          "seat of sinners",
          "way of the wicked",
          "path of the scornful"
        ]
      },
      {
        "a": "seat of the scornful",
        "d": [
          "seat of the scoffers",
          "place of the scornful",
          "chair of the scornful"
        ]
      }
    ]
  },
  {
    "b": "Isaiah",
    "r": "Isaiah 40:31",
    "t": 2,
    "parts": [
      "But those who wait on the LORD Shall ",
      {
        "a": "renew their strength",
        "d": [
          "soar above the tempest",
          "walk and never faint",
          "restore their strength"
        ]
      },
      "; They shall mount up with ",
      {
        "a": "wings like eagles",
        "d": [
          "wings as the eagle",
          "eagles' wings",
          "wings of a dove"
        ]
      },
      ", They shall run and not be weary, They shall walk and not ",
      {
        "a": "faint",
        "d": [
          "fail",
          "fall",
          "tire"
        ]
      },
      "."
    ],
    "id": "P~isaiah-40-31",
    "blanks": [
      {
        "a": "renew their strength",
        "d": [
          "soar above the tempest",
          "walk and never faint",
          "restore their strength"
        ]
      },
      {
        "a": "wings like eagles",
        "d": [
          "wings as the eagle",
          "eagles' wings",
          "wings of a dove"
        ]
      },
      {
        "a": "faint",
        "d": [
          "fail",
          "fall",
          "tire"
        ]
      }
    ]
  },
  {
    "b": "Proverbs",
    "r": "Proverbs 3:5-6",
    "t": 1,
    "parts": [
      "Trust in the LORD with ",
      {
        "a": "all your heart",
        "d": [
          "all your soul",
          "your whole heart",
          "all your strength"
        ]
      },
      ", And lean not on ",
      {
        "a": "your own understanding",
        "d": [
          "your own wisdom",
          "your own counsel",
          "your own insight"
        ]
      },
      "; In all your ways acknowledge Him, And He shall ",
      {
        "a": "direct your paths",
        "d": [
          "make straight your paths",
          "direct your steps",
          "establish your paths"
        ]
      },
      "."
    ],
    "id": "P~proverbs-3-5-6",
    "blanks": [
      {
        "a": "all your heart",
        "d": [
          "all your soul",
          "your whole heart",
          "all your strength"
        ]
      },
      {
        "a": "your own understanding",
        "d": [
          "your own wisdom",
          "your own counsel",
          "your own insight"
        ]
      },
      {
        "a": "direct your paths",
        "d": [
          "make straight your paths",
          "direct your steps",
          "establish your paths"
        ]
      }
    ]
  },
  {
    "b": "Romans",
    "r": "Romans 8:28",
    "t": 3,
    "parts": [
      "And we know that all things ",
      {
        "a": "work together for good",
        "d": [
          "work for eternal glory",
          "prosper in righteousness",
          "work together for glory"
        ]
      },
      " to those who ",
      {
        "a": "love God",
        "d": [
          "prosper in righteousness",
          "fear God",
          "serve God"
        ]
      },
      ", to those who are the called according to ",
      {
        "a": "His purpose",
        "d": [
          "prosper in righteousness",
          "his good pleasure",
          "his counsel"
        ]
      },
      "."
    ],
    "id": "P~romans-8-28",
    "blanks": [
      {
        "a": "work together for good",
        "d": [
          "work for eternal glory",
          "prosper in righteousness",
          "work together for glory"
        ]
      },
      {
        "a": "love God",
        "d": [
          "prosper in righteousness",
          "fear God",
          "serve God"
        ]
      },
      {
        "a": "His purpose",
        "d": [
          "prosper in righteousness",
          "his good pleasure",
          "his counsel"
        ]
      }
    ]
  },
  {
    "b": "Matthew",
    "r": "Matthew 5:3-4",
    "t": 2,
    "parts": [
      "\"Blessed are the ",
      {
        "a": "poor in spirit",
        "d": [
          "pure in spirit",
          "meek in spirit",
          "lowly in spirit"
        ]
      },
      ", For theirs is the ",
      {
        "a": "kingdom of heaven",
        "d": [
          "kingdom of God",
          "kingdom of the Father",
          "house of heaven"
        ]
      },
      ". Blessed are those who mourn, For they shall be ",
      {
        "a": "comforted",
        "d": [
          "consoled",
          "made glad",
          "lifted up"
        ]
      },
      "."
    ],
    "id": "P~matthew-5-3-4",
    "blanks": [
      {
        "a": "poor in spirit",
        "d": [
          "pure in spirit",
          "meek in spirit",
          "lowly in spirit"
        ]
      },
      {
        "a": "kingdom of heaven",
        "d": [
          "kingdom of God",
          "kingdom of the Father",
          "house of heaven"
        ]
      },
      {
        "a": "comforted",
        "d": [
          "consoled",
          "made glad",
          "lifted up"
        ]
      }
    ]
  },
  {
    "b": "Psalms",
    "r": "Psalm 46:1-2",
    "t": 3,
    "parts": [
      "God is our ",
      {
        "a": "refuge and strength",
        "d": [
          "rock and refuge",
          "strength and shield",
          "refuge and fortress"
        ]
      },
      ", A ",
      {
        "a": "very present help",
        "d": [
          "ever present help",
          "sure and present help",
          "very present hope"
        ]
      },
      " in trouble. Therefore we will not fear, Even though the earth be removed, And though the mountains be carried into the ",
      {
        "a": "midst of the sea",
        "d": [
          "depths of the sea",
          "heart of the sea",
          "midst of the waters"
        ]
      },
      ";"
    ],
    "id": "P~psalm-46-1-2",
    "blanks": [
      {
        "a": "refuge and strength",
        "d": [
          "rock and refuge",
          "strength and shield",
          "refuge and fortress"
        ]
      },
      {
        "a": "very present help",
        "d": [
          "ever present help",
          "sure and present help",
          "very present hope"
        ]
      },
      {
        "a": "midst of the sea",
        "d": [
          "depths of the sea",
          "heart of the sea",
          "midst of the waters"
        ]
      }
    ]
  },
  {
    "b": "1 Corinthians",
    "r": "1 Corinthians 13:4",
    "t": 3,
    "parts": [
      "Love ",
      {
        "a": "suffers long",
        "d": [
          "bears long",
          "endures long",
          "beareth long"
        ]
      },
      " and is kind; love ",
      {
        "a": "does not envy",
        "d": [
          "does not mourn",
          "does not boast",
          "does not wander"
        ]
      },
      "; love does not parade itself, is not ",
      {
        "a": "puffed up",
        "d": [
          "lifted up",
          "made proud",
          "exalted"
        ]
      },
      ";"
    ],
    "id": "P~1-corinthians-13-4",
    "blanks": [
      {
        "a": "suffers long",
        "d": [
          "bears long",
          "endures long",
          "beareth long"
        ]
      },
      {
        "a": "does not envy",
        "d": [
          "does not mourn",
          "does not boast",
          "does not wander"
        ]
      },
      {
        "a": "puffed up",
        "d": [
          "lifted up",
          "made proud",
          "exalted"
        ]
      }
    ]
  },
  {
    "b": "Ephesians",
    "r": "Ephesians 6:11-12",
    "t": 4,
    "parts": [
      "Put on the ",
      {
        "a": "whole armor of God",
        "d": [
          "full armor of God",
          "whole armor of light",
          "armor of righteousness"
        ]
      },
      ", that you may be able to stand against the ",
      {
        "a": "wiles of the devil",
        "d": [
          "works of the devil",
          "snares of the devil",
          "ways of the devil"
        ]
      },
      ". For we do not wrestle against ",
      {
        "a": "flesh and blood",
        "d": [
          "blood and flesh",
          "flesh and bone",
          "men of flesh"
        ]
      },
      ", but against principalities, against powers, against the rulers of the darkness of this age, against spiritual hosts of wickedness in the heavenly places."
    ],
    "id": "P~ephesians-6-11-12",
    "blanks": [
      {
        "a": "whole armor of God",
        "d": [
          "full armor of God",
          "whole armor of light",
          "armor of righteousness"
        ]
      },
      {
        "a": "wiles of the devil",
        "d": [
          "works of the devil",
          "snares of the devil",
          "ways of the devil"
        ]
      },
      {
        "a": "flesh and blood",
        "d": [
          "blood and flesh",
          "flesh and bone",
          "men of flesh"
        ]
      }
    ]
  },
  {
    "b": "Philippians",
    "r": "Philippians 4:6-7",
    "t": 3,
    "parts": [
      "Be anxious for nothing, but in everything by ",
      {
        "a": "prayer and supplication",
        "d": [
          "prayer and thanksgiving",
          "supplication and fasting",
          "prayer and petition"
        ]
      },
      ", with thanksgiving, let your requests be made known to God; and the ",
      {
        "a": "peace of God",
        "d": [
          "peace of Christ",
          "grace of God",
          "comfort of God"
        ]
      },
      ", which ",
      {
        "a": "surpasses all understanding",
        "d": [
          "passes all understanding",
          "passes all knowledge",
          "passes understanding"
        ]
      },
      ", will guard your hearts and minds through Christ Jesus."
    ],
    "id": "P~philippians-4-6-7",
    "blanks": [
      {
        "a": "prayer and supplication",
        "d": [
          "prayer and thanksgiving",
          "supplication and fasting",
          "prayer and petition"
        ]
      },
      {
        "a": "peace of God",
        "d": [
          "peace of Christ",
          "grace of God",
          "comfort of God"
        ]
      },
      {
        "a": "surpasses all understanding",
        "d": [
          "passes all understanding",
          "passes all knowledge",
          "passes understanding"
        ]
      }
    ]
  },
  {
    "b": "Psalms",
    "r": "Psalm 91:1-2",
    "t": 4,
    "parts": [
      "He who dwells in the ",
      {
        "a": "secret place of the Most High",
        "d": [
          "secret place of the Almighty",
          "holy place of the most High",
          "hidden place of the most High"
        ]
      },
      " Shall abide under the ",
      {
        "a": "shadow of the Almighty",
        "d": [
          "shadow of his wings",
          "shelter of the Almighty",
          "shadow of the most High"
        ]
      },
      ". I will say of the LORD, \"He is my ",
      {
        "a": "refuge and my fortress",
        "d": [
          "fortress and my refuge",
          "refuge and my rock",
          "shield and my fortress"
        ]
      },
      "; My God, in Him I will trust.\""
    ],
    "id": "P~psalm-91-1-2",
    "blanks": [
      {
        "a": "secret place of the Most High",
        "d": [
          "secret place of the Almighty",
          "holy place of the most High",
          "hidden place of the most High"
        ]
      },
      {
        "a": "shadow of the Almighty",
        "d": [
          "shadow of his wings",
          "shelter of the Almighty",
          "shadow of the most High"
        ]
      },
      {
        "a": "refuge and my fortress",
        "d": [
          "fortress and my refuge",
          "refuge and my rock",
          "shield and my fortress"
        ]
      }
    ]
  },
  {
    "b": "John",
    "r": "John 14:6",
    "t": 1,
    "parts": [
      "Jesus said to him, \"I am ",
      {
        "a": "the way",
        "d": [
          "without my grace",
          "the door",
          "the light"
        ]
      },
      ", the truth, and ",
      {
        "a": "the life",
        "d": [
          "without my grace",
          "the light",
          "the resurrection"
        ]
      },
      ". No one comes to the Father ",
      {
        "a": "except through Me",
        "d": [
          "but by my word",
          "without my grace",
          "save through the cross"
        ]
      },
      "."
    ],
    "id": "P~john-14-6",
    "blanks": [
      {
        "a": "the way",
        "d": [
          "without my grace",
          "the door",
          "the light"
        ]
      },
      {
        "a": "the life",
        "d": [
          "without my grace",
          "the light",
          "the resurrection"
        ]
      },
      {
        "a": "except through Me",
        "d": [
          "but by my word",
          "without my grace",
          "save through the cross"
        ]
      }
    ]
  },
  {
    "b": "Joshua",
    "r": "Joshua 1:9",
    "t": 2,
    "parts": [
      "Have I not commanded you? Be strong and ",
      {
        "a": "of good courage",
        "d": [
          "of good cheer",
          "of a good spirit",
          "of great courage"
        ]
      },
      "; do not be afraid, nor be ",
      {
        "a": "dismayed",
        "d": [
          "discouraged",
          "troubled",
          "confused"
        ]
      },
      ", for the LORD your God is with you ",
      {
        "a": "wherever you go",
        "d": [
          "in all your ways",
          "through the deep waters",
          "faint-hearted"
        ]
      },
      ".\""
    ],
    "id": "P~joshua-1-9",
    "blanks": [
      {
        "a": "of good courage",
        "d": [
          "of good cheer",
          "of a good spirit",
          "of great courage"
        ]
      },
      {
        "a": "dismayed",
        "d": [
          "discouraged",
          "troubled",
          "confused"
        ]
      },
      {
        "a": "wherever you go",
        "d": [
          "in all your ways",
          "through the deep waters",
          "faint-hearted"
        ]
      }
    ]
  },
  {
    "b": "Hebrews",
    "r": "Hebrews 11:1",
    "t": 4,
    "parts": [
      "Now faith is the ",
      {
        "a": "substance",
        "d": [
          "assurance",
          "foundation",
          "evidence"
        ]
      },
      " of things hoped for, the ",
      {
        "a": "evidence",
        "d": [
          "substance",
          "witness",
          "proof"
        ]
      },
      " of things ",
      {
        "a": "not seen",
        "d": [
          "unseen",
          "not yet come",
          "not known"
        ]
      },
      "."
    ],
    "id": "P~hebrews-11-1",
    "blanks": [
      {
        "a": "substance",
        "d": [
          "assurance",
          "foundation",
          "evidence"
        ]
      },
      {
        "a": "evidence",
        "d": [
          "substance",
          "witness",
          "proof"
        ]
      },
      {
        "a": "not seen",
        "d": [
          "unseen",
          "not yet come",
          "not known"
        ]
      }
    ]
  },
  {
    "b": "Revelation",
    "r": "Revelation 21:4",
    "t": 3,
    "parts": [
      "And God will ",
      {
        "a": "wipe away every tear",
        "d": [
          "take away all tears",
          "wipe all tears away",
          "banish every sorrow"
        ]
      },
      " from their eyes; there shall be ",
      {
        "a": "no more death",
        "d": [
          "no more sorrow",
          "death no more",
          "no more dying"
        ]
      },
      ", nor sorrow, nor crying. There shall be no more pain, for the ",
      {
        "a": "former things have passed away",
        "d": [
          "former things are done away",
          "first things are passed away",
          "old things have vanished"
        ]
      },
      ".\""
    ],
    "id": "P~revelation-21-4",
    "blanks": [
      {
        "a": "wipe away every tear",
        "d": [
          "take away all tears",
          "wipe all tears away",
          "banish every sorrow"
        ]
      },
      {
        "a": "no more death",
        "d": [
          "no more sorrow",
          "death no more",
          "no more dying"
        ]
      },
      {
        "a": "former things have passed away",
        "d": [
          "former things are done away",
          "first things are passed away",
          "old things have vanished"
        ]
      }
    ]
  },
  {
    "b": "Psalms",
    "r": "Psalm 51:10-11",
    "t": 3,
    "parts": [
      "Create in me a ",
      {
        "a": "clean heart",
        "d": [
          "pure heart",
          "new heart",
          "whole heart"
        ]
      },
      ", O God, And renew a ",
      {
        "a": "steadfast spirit",
        "d": [
          "righteous spirit",
          "willing spirit",
          "clean spirit"
        ]
      },
      " within me. Do not cast me away from Your presence, And do not take ",
      {
        "a": "Your Holy Spirit",
        "d": [
          "your spirit of grace",
          "your own spirit",
          "Your Righteous Spirit"
        ]
      },
      " from me."
    ],
    "id": "P~psalm-51-10-11",
    "blanks": [
      {
        "a": "clean heart",
        "d": [
          "pure heart",
          "new heart",
          "whole heart"
        ]
      },
      {
        "a": "steadfast spirit",
        "d": [
          "righteous spirit",
          "willing spirit",
          "clean spirit"
        ]
      },
      {
        "a": "Your Holy Spirit",
        "d": [
          "your spirit of grace",
          "your own spirit",
          "Your Righteous Spirit"
        ]
      }
    ]
  },
  {
    "b": "Isaiah",
    "r": "Isaiah 53:5",
    "t": 4,
    "parts": [
      "But He was wounded for ",
      {
        "a": "our transgressions",
        "d": [
          "our trespasses",
          "our rebellions",
          "our sins"
        ],
        "qaOk": [
          "recycled"
        ]
      },
      ", He was bruised for ",
      {
        "a": "our iniquities",
        "d": [
          "our offences",
          "our wickedness",
          "our sins"
        ],
        "qaOk": [
          "recycled"
        ]
      },
      "; The chastisement for our peace was upon Him, And by His stripes ",
      {
        "a": "we are healed",
        "d": [
          "we are made whole",
          "we are redeemed",
          "we are restored"
        ]
      },
      "."
    ],
    "id": "P~isaiah-53-5",
    "blanks": [
      {
        "a": "our transgressions",
        "d": [
          "our trespasses",
          "our rebellions",
          "our sins"
        ],
        "qaOk": [
          "recycled"
        ]
      },
      {
        "a": "our iniquities",
        "d": [
          "our offences",
          "our wickedness",
          "our sins"
        ],
        "qaOk": [
          "recycled"
        ]
      },
      {
        "a": "we are healed",
        "d": [
          "we are made whole",
          "we are redeemed",
          "we are restored"
        ]
      }
    ]
  },
  {
    "b": "Matthew",
    "r": "Matthew 6:9-10",
    "t": 2,
    "parts": [
      "In this manner, therefore, pray: Our Father in heaven, ",
      {
        "a": "Hallowed be Your name",
        "d": [
          "Holy be your name",
          "Blessed be your name",
          "Hallowed be your word"
        ]
      },
      ". ",
      {
        "a": "Your kingdom come",
        "d": [
          "Your kingdom reign",
          "Let your kingdom come",
          "Your kingdom stand"
        ]
      },
      ". Your will be done On earth ",
      {
        "a": "as it is in heaven",
        "d": [
          "even as in heaven",
          "as in the heavens",
          "as it is above"
        ]
      },
      "."
    ],
    "id": "P~matthew-6-9-10",
    "blanks": [
      {
        "a": "Hallowed be Your name",
        "d": [
          "Holy be your name",
          "Blessed be your name",
          "Hallowed be your word"
        ]
      },
      {
        "a": "Your kingdom come",
        "d": [
          "Your kingdom reign",
          "Let your kingdom come",
          "Your kingdom stand"
        ]
      },
      {
        "a": "as it is in heaven",
        "d": [
          "even as in heaven",
          "as in the heavens",
          "as it is above"
        ]
      }
    ]
  },
  {
    "b": "2 Timothy",
    "r": "2 Timothy 1:7",
    "t": 2,
    "parts": [
      "For God has not given us a ",
      {
        "a": "spirit of fear",
        "d": [
          "spirit of bondage",
          "spirit of dread",
          "spirit of weakness"
        ]
      },
      ", but of ",
      {
        "a": "power",
        "d": [
          "might",
          "strength",
          "glory"
        ]
      },
      " and of love and of a ",
      {
        "a": "sound mind",
        "d": [
          "sober mind",
          "steadfast mind",
          "quiet mind"
        ]
      },
      "."
    ],
    "id": "P~2-timothy-1-7",
    "blanks": [
      {
        "a": "spirit of fear",
        "d": [
          "spirit of bondage",
          "spirit of dread",
          "spirit of weakness"
        ]
      },
      {
        "a": "power",
        "d": [
          "might",
          "strength",
          "glory"
        ]
      },
      {
        "a": "sound mind",
        "d": [
          "sober mind",
          "steadfast mind",
          "quiet mind"
        ]
      }
    ]
  },
  {
    "b": "James",
    "r": "James 1:2-3",
    "t": 4,
    "parts": [
      "My brethren, count it ",
      {
        "a": "all joy",
        "d": [
          "great joy",
          "pure joy",
          "all gladness"
        ]
      },
      " when you fall into ",
      {
        "a": "various trials",
        "d": [
          "many temptations",
          "various temptations",
          "various tribulations"
        ]
      },
      ", knowing that the testing of your faith ",
      {
        "a": "produces patience",
        "d": [
          "brings patience",
          "worketh endurance",
          "bringeth patience"
        ]
      },
      "."
    ],
    "id": "P~james-1-2-3",
    "blanks": [
      {
        "a": "all joy",
        "d": [
          "great joy",
          "pure joy",
          "all gladness"
        ]
      },
      {
        "a": "various trials",
        "d": [
          "many temptations",
          "various temptations",
          "various tribulations"
        ]
      },
      {
        "a": "produces patience",
        "d": [
          "brings patience",
          "worketh endurance",
          "bringeth patience"
        ]
      }
    ]
  },
  {
    "b": "Galatians",
    "r": "Galatians 5:22-23",
    "t": 3,
    "parts": [
      "But the fruit of the Spirit is ",
      {
        "a": "love, joy, peace",
        "d": [
          "joy, love, peace",
          "love, peace, joy",
          "love, hope, peace"
        ]
      },
      ", ",
      {
        "a": "longsuffering",
        "d": [
          "forbearance",
          "patience",
          "gentleness"
        ]
      },
      ", kindness, goodness, faithfulness, gentleness, self-control. Against such there is ",
      {
        "a": "no law",
        "d": [
          "no judgment",
          "no condemnation",
          "no commandment"
        ]
      },
      "."
    ],
    "id": "P~galatians-5-22-23",
    "blanks": [
      {
        "a": "love, joy, peace",
        "d": [
          "joy, love, peace",
          "love, peace, joy",
          "love, hope, peace"
        ]
      },
      {
        "a": "longsuffering",
        "d": [
          "forbearance",
          "patience",
          "gentleness"
        ]
      },
      {
        "a": "no law",
        "d": [
          "no judgment",
          "no condemnation",
          "no commandment"
        ]
      }
    ]
  },
  {
    "b": "Romans",
    "r": "Romans 12:2",
    "t": 4,
    "parts": [
      "And do not be ",
      {
        "a": "conformed to this world",
        "d": [
          "conformed to the world",
          "fashioned to this world",
          "yoked to this world"
        ]
      },
      ", but be transformed by the ",
      {
        "a": "renewing of your mind",
        "d": [
          "renewal of your mind",
          "washing of your mind",
          "renewing of your heart"
        ]
      },
      ", that you may prove what is that good and acceptable and ",
      {
        "a": "perfect will of God",
        "d": [
          "holy, will of God",
          "perfect, way of God",
          "complete, will of God"
        ]
      },
      "."
    ],
    "id": "P~romans-12-2",
    "blanks": [
      {
        "a": "conformed to this world",
        "d": [
          "conformed to the world",
          "fashioned to this world",
          "yoked to this world"
        ]
      },
      {
        "a": "renewing of your mind",
        "d": [
          "renewal of your mind",
          "washing of your mind",
          "renewing of your heart"
        ]
      },
      {
        "a": "perfect will of God",
        "d": [
          "holy, will of God",
          "perfect, way of God",
          "complete, will of God"
        ]
      }
    ]
  },
  {
    "b": "Psalms",
    "r": "Psalm 139:13-14",
    "t": 5,
    "parts": [
      "For You ",
      {
        "a": "formed my inward",
        "d": [
          "possessed my reins",
          "possessed my heart",
          "fashioned my reins"
        ]
      },
      " parts; You covered me in my ",
      {
        "a": "mother's womb",
        "d": [
          "mother's arms",
          "mother's house",
          "secret place"
        ]
      },
      ". I will praise You, for I am ",
      {
        "a": "fearfully and wonderfully made",
        "d": [
          "wonderfully and fearfully made",
          "fearfully and marvellously made",
          "fearfully and wondrously made"
        ]
      },
      "; Marvelous are Your works, And that my soul knows very well."
    ],
    "id": "P~psalm-139-13-14",
    "blanks": [
      {
        "a": "formed my inward",
        "d": [
          "possessed my reins",
          "possessed my heart",
          "fashioned my reins"
        ]
      },
      {
        "a": "mother's womb",
        "d": [
          "mother's arms",
          "mother's house",
          "secret place"
        ]
      },
      {
        "a": "fearfully and wonderfully made",
        "d": [
          "wonderfully and fearfully made",
          "fearfully and marvellously made",
          "fearfully and wondrously made"
        ]
      }
    ]
  },
  {
    "b": "Ecclesiastes",
    "r": "Ecclesiastes 3:1-2",
    "t": 3,
    "parts": [
      "To everything there is ",
      {
        "a": "a season",
        "d": [
          "an hour",
          "a due season",
          "an age"
        ]
      },
      ", A time for every purpose ",
      {
        "a": "under heaven",
        "d": [
          "under the sun",
          "beneath the heavens",
          "on the earth"
        ]
      },
      ": A time to be born, And ",
      {
        "a": "a time to die",
        "d": [
          "a time to perish",
          "a time to depart",
          "a time to be gathered"
        ]
      },
      "; A time to plant, And a time to pluck what is planted;"
    ],
    "id": "P~ecclesiastes-3-1-2",
    "blanks": [
      {
        "a": "a season",
        "d": [
          "an hour",
          "a due season",
          "an age"
        ]
      },
      {
        "a": "under heaven",
        "d": [
          "under the sun",
          "beneath the heavens",
          "on the earth"
        ]
      },
      {
        "a": "a time to die",
        "d": [
          "a time to perish",
          "a time to depart",
          "a time to be gathered"
        ]
      }
    ]
  },
  {
    "b": "Matthew",
    "r": "Matthew 28:19-20",
    "t": 4,
    "parts": [
      "Go therefore and make disciples of ",
      {
        "a": "all the nations",
        "d": [
          "teach all nations",
          "preach to all nations",
          "preach the gospel"
        ]
      },
      ", baptizing them in the name of the Father and of the Son and of the ",
      {
        "a": "Holy Spirit",
        "d": [
          "Spirit of God",
          "Comforter",
          "Spirit of truth"
        ]
      },
      ", teaching them to observe all things that I have commanded you; and lo, I am with you always, even to the ",
      {
        "a": "end of the age",
        "d": [
          "ends of the earth",
          "end of all things",
          "close of the age"
        ]
      },
      ".\" Amen."
    ],
    "id": "P~matthew-28-19-20",
    "blanks": [
      {
        "a": "all the nations",
        "d": [
          "teach all nations",
          "preach to all nations",
          "preach the gospel"
        ]
      },
      {
        "a": "Holy Spirit",
        "d": [
          "Spirit of God",
          "Comforter",
          "Spirit of truth"
        ]
      },
      {
        "a": "end of the age",
        "d": [
          "ends of the earth",
          "end of all things",
          "close of the age"
        ]
      }
    ]
  }
];
if(typeof module !== "undefined") module.exports = { NKJV_PASSAGES };
