/* GENERATED by scripts/build-nkjv.js from the licensed NKJV text in
   content/nkjv/source/. Do not edit by hand — rerun the generator.
   the six onboarding lessons */
const NKJV_TUTORIAL_QUESTIONS = [
  {
    "id": "tutorial-choice",
    "b": "Psalms",
    "r": "Psalm 23:1",
    "t": 1,
    "p": "The LORD is my shepherd; I",
    "a": "shall not want",
    "s": ".",
    "d": [
      "shall not fear",
      "shall not faint",
      "shall not wander"
    ]
  },
  {
    "id": "tutorial-passage-ref",
    "b": "Proverbs",
    "r": "Proverbs 3:5",
    "t": 1,
    "p": "Trust in the LORD with all your heart, And lean not on your",
    "a": "own understanding",
    "s": ";",
    "d": [
      "carnal wisdom",
      "earthly counsel",
      "proud imagination"
    ],
    "mechanic": "passage-ref"
  },
  {
    "id": "tutorial-cloze",
    "b": "Genesis",
    "r": "Genesis 1:1",
    "t": 1,
    "p": "In the beginning",
    "a": "God created the heavens and the earth",
    "s": ".",
    "d": [
      "the Word formed the light and land",
      "the Almighty established the deep",
      "God created the skies and the earth"
    ],
    "mechanic": "cloze"
  },
  {
    "id": "tutorial-duel",
    "b": "John",
    "r": "John 1:1",
    "t": 1,
    "p": "In the beginning was the Word, and the Word was with God, and the Word",
    "a": "was God",
    "s": ".",
    "d": [
      "was divine",
      "became flesh",
      "dwelt in light"
    ],
    "mechanic": "duel"
  },
  {
    "id": "tutorial-fade",
    "b": "Philippians",
    "r": "Philippians 4:13",
    "t": 1,
    "p": "I can do all things through Christ who",
    "a": "strengthens me",
    "s": ".",
    "d": [
      "keeps me",
      "comforts me",
      "teaches me"
    ],
    "mechanic": "fade"
  },
  {
    "id": "tutorial-assemble",
    "b": "Psalms",
    "r": "Psalm 118:24",
    "t": 1,
    "p": "This is the day the LORD has made; We will",
    "a": "rejoice and be glad in it",
    "s": ".",
    "d": [
      "sing and give thanks",
      "stand and praise his name",
      "remember and be glad"
    ],
    "typed": true
  }
];
if(typeof module !== "undefined") module.exports = { NKJV_TUTORIAL_QUESTIONS };
